---
title: "Lab 10: Model Comparison"
format:
  html:
    toc: true
---

In this Lab, you will analyze the "hospital_sim" dataset. It contains simulated (i.e., fake) data about 2000 patients with recent visits to 40 hospitals. On level 1, it includes each patient’s customer satisfaction (`satisfaction`, continuous), time waiting for the doctor (`wait_time`, continuous), and type of visit (`visit_type`, discrete: Emergency vs. Routine); and on level 2, it includes each hospital’s identifier (`hospital`, discrete: H01 to H40), ratio of nurses to patients (`nurse_ratio`, continuous), and type (`hospital_type`, discrete: Teaching or Non-Teaching).

## Data Prep (0.5 pts)

Download the "hospital_sim.csv" dataset from Canvas, add it to your project folder, and read it into R as a tibble called `dat_raw`. Use the code below to prepare the data for multilevel analysis. In your Quarto file, annotate this code by adding comments explaining what each line does.

```{r}
#| eval: false

dat_l2 <- 
  dat_raw |>
  summarize(
    # COMMENT
    .by = hospital,
    # COMMENT
    nurse_ratio = first(nurse_ratio),
    # COMMENT
    hospital_type = first(hospital_type),
    # COMMENT
    wait_time_b = mean(wait_time, na.rm = TRUE)
  ) |> 
  mutate(
    # COMMENT
    nurse_ratio_c = center(nurse_ratio),
    # COMMENT
    wait_time_bc = center(wait_time_b)
  ) |> 
  print()

dat <- 
  dat_raw |> 
  # COMMENT
  select(-c(nurse_ratio, hospital_type)) |> 
  # COMMENT
  left_join(dat_l2, by = "hospital") |>
  # COMMENT
  mutate(wait_time_wc = wait_time - wait_time_b) |> 
  print()
```

## Step 1 (0.5 pts)

Complete Step 1 of our modeling approach by fitting a null model to `dat` using `glmmTMB()` (and FML); the outcome variable should be `satisfaction` and there should be random intercepts per `hospital`. Calculate the unconditional ICC.

## Step 2 (1.0 pts)

Complete Step 2 by adding fixed slopes of the L1 predictors (i.e., `wait_time_within` and `visit_type`). Compare the Step 1 and Step 2 models using the LRT. Are these predictors worth including?

## Step 3 (1.0 pts)
Complete Step 3 by adding fixed slopes of all the L2 predictors (i.e., `wait_time_between`, `nurse_ratio`, and `hospital_type`). Compare the Step 2 and Step 3 models using LRT. Are these predictors worth including?

## Step 4 (1.0 pts)
Complete Step 4 by adding random slopes of both L1 predictors (i.e., `wait_time_within` and `visit_type`). Compare the Step 3 and Step 4 models using LRT. Are these random slopes worth including? If not, try them one at a time (instead of both together) to decide if either is worth including on its own.

## Step 5 (1.0 pts)
Complete Step 5 by adding a cross-level interaction between `hospital_type` and `visit_type`. Compare the Step 4 and Step 5 models using LRT. Is this interaction worth including?

## Final LRT Model (0.5 pts)
What is the final model that LRT prefers? Print its parameter table and interpret all of the fixed effects. What does each result tell us about patient satisfaction? *(Hint: Assume a strict $\alpha=.05$ and remember what happens to the interpretation of slopes in a regression with multiple predictors.)*

## Information Criteria (0.5 pts)
Compare all five models using AIC and BIC. Which model does each metric prefer?
