---
title: "Week 07: Random Slopes Models"
---

<!-- 07a -->

## [07a] Random Slopes

### Topics
- Conceptual Foundations: Defining Models and Assumptions
- Application and Interpretation: Fitting and Visualizing Models

### File Downloads
- [heck2011.csv](../../data/heck2011.csv){download="heck2011.csv"}

### Readings
- [S\&F Chapter 6: Random Effects and Cross-level Interactions](https://www.learn-mlms.com/06-module-6.html){target="_blank"}
- [HMV Sections 2.1--2.2: The Basic Two-level Regression Model](https://canvas.ku.edu/courses/182539/pages/07a-random-slopes-2?module_item_id=4317566){target="_blank"}

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[07a] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::


<!-- 07b -->

## [07b] Cross-level Interactions

### Topics
- Conceptual Foundations: Cross-level Interactions
- Application and Interpretation: Fitting and Interpreting Models

### File Downloads
- [heck2011.csv](../../data/heck2011.csv){download="heck2011.csv"}

### Readings
- [Aguinis, Gottfredson, \& Culpepper (2013)](https://canvas.ku.edu/courses/182539/pages/07b-cross-level-interactions-+-lab-2){target="_blank"}
- [Heisig \& Schaeffer (2019)](https://canvas.ku.edu/courses/182539/pages/07b-cross-level-interactions-+-lab-2){target="_blank"}


### Slides
```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[07b] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../06/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Week 06</a>

  <a href="../08/index.html" class="btn btn-primary" role="button">Week 08&nbsp;&nbsp;&raquo;</a>
</div>
```
