---
title: "Week 11: Longitudinal Analysis 1"
---

<!-- Lecture a -->

## [11a] Repeated Measures

### Topics
1. Within-Person Variance
    + *Trial-level Analysis*
    + *Task-by-Person Effects*
  
2. The Structure of Error
    + *Autocorrelation Tests*
    + *Drift vs. White Noise*

### File Downloads
- [intell_sim.csv](../../data/intell_sim.csv){download="intell_sim.csv"}

### Readings
- [S\&F Chapter 9: Multilevel modeling with repeated measures data](https://www.learn-mlms.com/09-module-9.html){target="_blank"}
- [Brauer \& Curtin (2018)](https://canvas.ku.edu/courses/182539/pages/11a-repeated-measures){target="_blank"}
- [Hoffman Chapter 4](https://canvas.ku.edu/courses/182539/pages/11a-repeated-measures){target="_blank"}

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[11a] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::


<!-- Lecture b -->

## [11b] Longitudinal Fluctuation

### Topics
1. Longitudinal Fluctuation
    + *Longitudinal Taxonomy*
    + *State vs. Trait Predictors*
  
2. Advanced Applications
    + *State--Trait Automoderation*
    + *Spatial Exponential Errors*

### File Downloads
- [ema_sim.csv](../../data/ema_sim.csv){download="ema_sim.csv"}

### Readings
- [HMV Chapter 5: Analyzing Longitudinal Data](https://canvas.ku.edu/courses/182539/pages/11b-longitudinal-fluctuation-+-lab?module_item_id=4317586){target="_blank"}
- [Hoffman Chapter 1: Introduction to the Analysis of Longitudinal Data](https://canvas.ku.edu/courses/182539/pages/11b-longitudinal-fluctuation-+-lab){target="_blank"}
- [Hoffman Chapter 4: Describing Within-Person Fluctuation Over Time](https://canvas.ku.edu/courses/182539/pages/11b-longitudinal-fluctuation-+-lab){target="_blank"}
- [Hoffman Chapter 8: Time-Varying Predictors in Models of Within-Person Fluctuation](https://canvas.ku.edu/courses/182539/pages/11b-longitudinal-fluctuation-+-lab){target="_blank"}

### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[11b] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../10/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Week 10</a>

  <a href="../12/index.html" class="btn btn-primary" role="button">Week 12&nbsp;&nbsp;&raquo;</a>
</div>
```
