{
  "hash": "5e320b373c0349f1204a56e6dd5c632c",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlecture: \"14b\"\nmetadata-files:\n  - ../../_slide-settings.yml\nformat:\n  revealjs:\n    theme: default\n---\n\n::: {.my-title}\n# [Multilevel Modeling]{.blue}\nPower Analysis\n\n::: {.my-grey}\n[{{< meta semester >}} | CLAS | {{< meta course >}}]{}<br />\n[Jeffrey M. Girard | Lecture {{< meta lecture >}}]{}\n:::\n\n![](../../img/city-girl.svg){.absolute bottom=30 right=0 width=\"400\"}\n:::\n\n\n::: {.cell}\n\n:::\n\n\n## Roadmap\n\n::: {.columns .pv4}\n\n::: {.column width=\"60%\"}\n1. The Power Problem in MLMs\n    + *Why G\\*Power isn't enough*\n    + *The simulation solution*\n    \n2. The `simr` Workflow\n    + *Building dummy models*\n    + *Simulating and extending power*\n    \n:::\n\n::: {.column .tc .pv4 width=\"40%\"}\n{{< lif \"../../icons/map.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n\n:::\n\n# The Power Problem\n\n## What is Statistical Power? {.fs80}\n\n:::{.columns}\n:::{.column width=\"60%\"}\n- **Power** is the probability of correctly rejecting a false null hypothesis.\n- In simpler terms: If a true effect exists in the real world, what are the chances your study will actually find it?\n- The standard benchmark in psychology is 80% power.\n- Power depends heavily on sample size, effect size, and your chosen alpha level (usually .05).\n:::\n:::{.column .tc .pv4 width=\"40%\"}\n{{< lif \"../../icons/power.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n:::\n\n## The Limits of Traditional Tools {.fs80}\n\n- Many of you have used programs like G\\*Power for simple regressions or ANOVAs.\n- These tools use closed-form mathematical equations to calculate exact sample size needs.\n- **The Problem:** MLMs are too complex for these simple equations.\n- In an MLM, power is not just about the total number of people. It depends on the number of clusters, the number of observations per cluster, the ICC, and the variance of your random slopes.\n\n## The Two Dimensions of N {.fs80}\n\n- If you want to increase your power in an MLM, you have two choices:\n  1. Add more Level-1 observations (e.g., recruit more patients per hospital).\n  2. Add more Level-2 clusters (e.g., recruit more hospitals).\n- These two choices do not increase power equally.\n- The most effective strategy depends entirely on the level at which your focal predictor is measured.\n\n## The Simulation Solution {.fs80}\n\nIf we cannot use a simple equation to calculate power, we simulate.\n\n**The Logic of Simulation:**\n\n1. We invent a hypothetical \"true\" effect size.\n2. We generate a fake dataset that mimics our planned study structure.\n3. We run our planned MLM on this fake data and check the *p*-value.\n4. We repeat this process 1,000 times.\n5. If 850 of those models yield a significant *p*-value, our power is 85%.\n\n# Introduction to simr\n\n## The simr Package {.fs80}\n\n- \\{simr\\} is an R package designed specifically to automate power simulations for generalized linear mixed models.\n- It is highly flexible and allows you to test power for fixed effects, random effects, and interactions.\n- **One important note:** `simr` was built to work with the `lme4` package. \n- While we used `glmmTMB` in previous lectures, we will need to use `lme4` syntax (like `lmer()` and `glmer()`) for our simulations today. The math is identical for our purposes.\n\n## The Workflow Template {.fs80}\n\nWe are going to learn a highly adaptable template that you can reuse for your own research. It involves four main steps:\n\n1. **Design the Data:** Create a grid of your planned sample sizes.\n2. **Set the Parameters:** Define your expected effect sizes and variances.\n3. **Build the Dummy Model:** Assemble the data and parameters into an artificial model object.\n4. **Run the Simulation:** Test the power and adjust your sample sizes until you reach 80%.\n\n# Building the<br> Dummy Model\n\n## Step 1: Design the Data\n\n:::{.fs80}\nLet us imagine we are planning a cluster-randomized trial. We want to test a new training program for nurses across 30 hospitals. We plan to survey 10 patients per hospital. We start by creating our planned data structure.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(simr)\n\nplanned_data <- \n  expand_grid(\n    hospital = 1:30,       # 30 hospitals (Level 2)\n    patient = 1:10         # 10 patients per hospital (Level 1)\n  ) |> \n  mutate(\n    # Assign the first half to treatment and second half to control\n    treatment = if_else(hospital <= 15, true = 1, false = 0),\n    hospital = factor(hospital)\n  )\n```\n:::\n\n\n## Viewing the Planned Data\n\n:::{.fs80}\nWe now have an empty shell of a dataset with 300 rows. It contains our clustering structure and our predictors, but no outcome variable yet.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplanned_data\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 300 × 3\n   hospital patient treatment\n   <fct>      <int>     <dbl>\n 1 1              1         1\n 2 1              2         1\n 3 1              3         1\n 4 1              4         1\n 5 1              5         1\n 6 1              6         1\n 7 1              7         1\n 8 1              8         1\n 9 1              9         1\n10 1             10         1\n# ℹ 290 more rows\n```\n\n\n:::\n:::\n\n\n## Step 2: Set the Fixed Effects\n\n:::{.fs80}\nNext, we tell `simr` what we believe the \"true\" effect sizes are. These are our Betas (fixed effects). \nWe need a value for the Intercept and a value for our `treatment` slope. \n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Let's assume the baseline satisfaction score is 5.0 (out of 10)\n# Let's assume the treatment increases satisfaction by 0.8 points\nmy_fixed_effects <- c(5.0, 0.8) \n```\n:::\n\n\n:::{.fs80}\n*Tip: Where do these numbers come from? You should pull them from pilot data, previous literature, or by defining the smallest effect size of clinical interest.*\n:::\n\n## Step 3: Set the Random Effects\n\n:::{.fs80}\n- Now we define our variance components. How much do the hospital baselines differ from one another?\nWe provide the variance for our random intercepts.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Let's assume the variance between hospitals is 0.5\nmy_random_variance <- 0.5 \n```\n:::\n\n\n:::{.fragment .mt4}\n:::{.fs80}\n- Finally, we must define the Level-1 residual variance. How much do patients within the same hospital differ from one another?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Let's assume the variance within hospitals is 2.0\nmy_residual_variance <- 2.0 \n```\n:::\n\n\n:::{.fs80}\n*(Note: An intercept variance of 0.5 and a residual variance of 2.0 gives us an ICC of 0.20, which is very typical for organizational data).*\n:::\n:::\n\n## Step 4: Assemble the Model\n\n:::{.fs80}\nWe now use the `makeLmer()` function from \\{simr\\} to smash all these pieces together. We provide a model formula, our fixed effects, our random effects, and our residual variance.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndummy_model <- makeLmer(\n  formula = satisfaction ~ treatment + (1 | hospital),\n  fixef = my_fixed_effects,\n  VarCorr = my_random_variance,\n  sigma = sqrt(my_residual_variance), # simr wants standard deviation here!\n  data = planned_data\n)\n```\n:::\n\n\n# Running the Simulation\n\n## A Single Power Test {.fs90}\n\n:::{.fs80}\nNow we ask the critical question: With 30 hospitals and 10 patients per hospital, do we have enough power to detect our 0.8 point treatment effect?\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(123)\nsim_result <- powerSim(dummy_model, test = fixed(\"treatment\"), \n                       nsim = 1000, progress = FALSE)\nprint(sim_result)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nPower for predictor 'treatment', (95% confidence interval):\n      71.30% (68.39, 74.09)\n\nTest: Kenward Roger (package pbkrtest)\n      Effect size for treatment is 0.80\n\nBased on 1000 simulations, (0 errors, 0 warnings, 1 message)\n\nTime elapsed: 0 h 1 m 22 s\n```\n\n\n:::\n:::\n\n\n:::{.fs80}\n- The result is 71.3% power, 95% CI: (68.4, 74.1). We are underpowered!\n:::\n\n## How to Fix Underpowered Studies \n\nWe have two options to reach 80% power:\n\n1. Increase the number of patients per hospital.\n2. Increase the number of hospitals.\n\nInstead of guessing and re-running the simulation manually, \\{simr\\} allows us to \"extend\" our dummy model and test a range of sample sizes automatically.\n\n## Step 5: Extending L2 (Hospitals)\n\n:::{.fs80}\nLet us first see what happens if we increase our study to 40 hospitals. We use the `extend()` function to add more hospitals.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extend the model to have 40 hospitals total\nextended_model_l2 <- extend(dummy_model, along = \"hospital\", n = 42)\n```\n:::\n\n\n:::{.fs80}\nThis automatically generates new hospital IDs and populates them with the correct ratio of patients and treatments, maintaining our data structure.\n:::\n\n## Step 6: The L2 Power Curve\n\n:::{.fs80}\nNow we use `powerCurve()` to test a sequence of hospital sample sizes.\n\nLet us test power at 30, 34, 38, 42 hospitals.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# We test the extended model across a sequence of hospital counts\ncurve_result_l2 <- powerCurve(\n  extended_model_l2, \n  test = fixed(\"treatment\"), \n  along = \"hospital\", \n  breaks = c(30, 34, 38, 42),\n  nsim = 1000\n)\nprint(curve_result_l2)\n```\n:::\n\n\n## Interpreting the L2 Power Curve\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPower for predictor 'treatment', (95% confidence interval),\nby number of levels in hospital:\n     30: 70.30% (67.36, 73.12) - 300 rows\n     34: 75.20% (72.40, 77.85) - 340 rows\n     38: 78.20% (75.51, 80.72) - 380 rows\n     42: 82.50% (80.00, 84.81) - 420 rows\n\n(0 errors, 1 warning, 0 messages)\n\nTime elapsed: 0 h 4 m 2 s\n```\n\n\n:::\n:::\n\n\n:::{.fs80}\nWe can now see exactly when we cross the 80% threshold. \n\nWe need at least 42 hospitals to do so (at 10 patients each).\n:::\n\n## Plotting the L2 Power Curve\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(curve_result_l2)\n```\n\n::: {.cell-output-display}\n![](b_Slides_files/figure-revealjs/unnamed-chunk-9-1.png){width=960}\n:::\n:::\n\n\n## Step 7: Extending L1 (Patients)\n\n:::{.fs80}\nWhat if we cannot recruit more hospitals? Let us see what happens if we keep our study at 30 hospitals, but try to recruit more patients per hospital instead.\n\nWe use `extend()` again, but we change the `along` argument to target our Level-1 ID.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Extend the model to have up to 20 patients per hospital\nextended_model_l1 <- extend(dummy_model, along = \"patient\", n = 20)\n```\n:::\n\n\n## Step 8: The L1 Power Curve\n\n:::{.fs80}\nWe test this new extended model across a sequence of patient sample sizes. Let us test power at 10, 15, and 20 patients per hospital.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncurve_result_l1 <- powerCurve(\n  extended_model_l1, \n  test = fixed(\"treatment\"), \n  along = \"patient\", \n  breaks = c(10, 15, 20),\n  nsim = 1000\n)\nprint(curve_result_l1)\n```\n:::\n\n\n## Interpreting the L1 Power Curve\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPower for predictor 'treatment', (95% confidence interval),\nby largest value of patient:\n     10: 70.40% (67.46, 73.22) - 300 rows\n     15: 75.70% (72.92, 78.33) - 450 rows\n     20: 78.40% (75.72, 80.91) - 600 rows\n\n(0 errors, 1 warning, 0 messages)\n\nTime elapsed: 0 h 3 m 17 s\n```\n\n\n:::\n:::\n\n\n:::{.fs80}\nNotice the diminishing returns. Even with 20 patients per hospital, our power is only about 78%. At 30 hospitals, we never reach 80%.\n:::\n\n## Plotting the L1 Power Curve\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(curve_result_l1)\n```\n\n::: {.cell-output-display}\n![](b_Slides_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n## The Lesson: Match the Level {.fs80}\n\nWhy did adding hospitals work, but adding patients failed? \n\n- **Level-2 Predictors:** Our `treatment` variable is assigned at the hospital level. Because we are testing a difference between clusters, we must add more clusters to increase our statistical power for that effect.\n- **Level-1 Predictors:** If we were testing a Level-1 predictor (e.g., randomizing patients to treatments *within* the same hospital), then adding patients would have been highly effective.\n\n**Takeaway:** Adding observations always increases power the most when added at the level of the predictor you are testing. For cluster-randomized trials, L2 always beats L1.\n\n# Sensitivity Analysis\n\n## Beyond Sample Size {.fs80}\n\n- We have spent all our time manipulating sample size ($N$) to reach 80% power.\n- However, power is equally dependent on the **effect size**.\n- In Step 2, we assumed our treatment would increase satisfaction by 0.8 points. \n- What if previous literature was overly optimistic? What if the true effect is only 0.5 points?\n- We need to conduct a **sensitivity analysis** to see how our power holds up if the effect is smaller than expected.\n\n## Modifying the Dummy Model\n\n:::{.fs80}\nWe do not have to rebuild our entire dataset and model from scratch. We can modify the fixed effects of our existing `dummy_model` directly using the `fixef()` function.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Change the treatment effect from 0.8 to 0.5\nfixef(dummy_model)[\"treatment\"] <- 0.5\n```\n:::\n\n\n## Re-Testing Power\n\n:::{.fs80}\nNow we can re-run our power simulation on the modified model. Let us see what happens to our power (at 30 hospitals and 10 patients) when the effect size shrinks.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(321)\nsens_result <- powerSim(dummy_model, test = fixed(\"treatment\"), nsim = 1000)\nprint(sens_result)\n```\n:::\n\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n\n```\nPower for predictor 'treatment', (95% confidence interval):\n      34.90% (31.94, 37.95)\n\nTest: Kenward Roger (package pbkrtest)\n      Effect size for treatment is 0.50\n\nBased on 1000 simulations, (0 errors, 0 warnings, 0 messages)\n\nTime elapsed: 0 h 1 m 24 s\n```\n\n\n:::\n:::\n\n\n## The Value of Sensitivity {.fs80}\n\n- By dropping the effect size from 0.8 to 0.5, our power plummeted from 71% to roughly 35%.\n- **The Takeaway:** When writing a grant or a pre-registration, it is highly recommended to report power across a *range* of plausible effect sizes. \n- It proves to reviewers that you understand the uncertainty in your assumptions and have planned accordingly.\n\n# Practical Tips\n\n## Start Small {.fs80}\n\n- Power simulations are computationally heavy.\n- When you are writing your code and testing to see if things work, keep `nsim` low (e.g., 10 or 50).\n- Once you are sure your code is error-free and your model is specified correctly, increase `nsim` to 1000 for your final, official power estimate.\n- Run the 1000-simulation version before you go to bed and let your computer work overnight.\n\n## Where to get the parameters? {.fs80}\n\nThe hardest part of simulation is knowing what numbers to plug in.\n\n- **Pilot Data:** The absolute best source. Fit an MLM to a small pilot sample and use those fixed effects and variances as your parameters.\n- **Literature Review:** Find a similar study and extract their effect sizes, variances, and ICCs.\n- **The \"Smallest Meaningful\" Approach:** If no data exists, ask yourself: \"What is the smallest effect size that would actually matter in the real world?\" Power your study to detect that.\n\n## Be Pessimistic {.fs80}\n\n- Simulations assume perfect conditions: perfect reliability, no missing data, and perfect compliance.\n- The real world is messy.\n- If your simulation says you need 25 clusters to achieve 80% power, you should aim to recruit 28 to 30 clusters. \n- Always build a buffer into your sample size justifications to account for attrition and messy data.\n\n## Handling Unbalanced Data {.fs80}\n\n- In our example, we used `expand_grid()` to create a perfectly balanced design (exactly 10 patients per hospital).\n- Real-world data is rarely this clean. You might have 5 patients in one hospital and 40 in another.\n- The \\{simr\\} package handles unbalanced data seamlessly. \n- You simply construct your `planned_data` data frame to reflect the unequal group sizes you realistically expect to collect. The `makeLmer()` function will adapt perfectly to whatever structure you provide.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}