{
  "hash": "a5c1d8ae44416f22e51c1a80ca83f78e",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlecture: \"11b\"\nmetadata-files:\n  - ../../_slide-settings.yml\nformat:\n  revealjs:\n    theme: default\n---\n\n::: {.my-title}\n# [Multilevel Modeling]{.blue}\nLongitudinal Fluctuation\n\n::: {.my-grey}\n[{{< meta semester >}} | CLAS | {{< meta course >}}]{}<br />\n[Jeffrey M. Girard | Lecture {{< meta lecture >}}]{}\n:::\n\n![](../../img/city-girl.svg){.absolute bottom=30 right=0 width=\"400\"}\n:::\n\n\n::: {.cell}\n\n:::\n\n\n## Roadmap\n\n::: {.columns .pv4}\n\n::: {.column width=\"60%\"}\n1. Longitudinal Fluctuation\n    + *Longitudinal Taxonomy*\n    + *State vs. Trait Predictors*\n  \n2. Advanced Applications\n    + *State--Trait Automoderation*\n    + *Spatial Exponential Errors*\n    \n:::\n\n::: {.column .tc .pv4 width=\"40%\"}\n{{< lif \"../../icons/map.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n\n:::\n\n# Longitudinal Concepts\n\n## Taxonomy of Longitudinal Models\n\n:::{.fsmaller}\n- [Fluctuation Models:]{.b .blue} The outcome rises and falls around a stable baseline. There is no systematic long-term trajectory. (Covered this week)\n    + *Example: Daily mood, daily stress, heart rate.*\n\n:::{.fragment}\n- [Growth Curve Models:]{.b .red} The outcome systematically changes over time,<br>\ne.g., increasing, decreasing, or curving. (Covered next week)\n    + *Example: Child vocabulary acquisition, therapy outcomes.*\n    \n:::\n\n:::{.fragment}\n- **Lagged Change Models:** We care about how the outcome at Time *t* predicts the outcome at Time *t+1*. (Not covered in this course, difficult with MLM)\n    + *Example: Does poor sleep tonight predict lower mood tomorrow?*\n    \n:::\n:::\n\n## Visualizing Fluctuation and Growth\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](b_Slides_files/figure-revealjs/unnamed-chunk-1-1.png){width=1056}\n:::\n:::\n\n\n\n# Modeling Fluctuation\n\n## Overview\n\n- Fluctuation models are perfect for Ecological Momentary Assessment (EMA) or daily diary designs.\n- We want to know how temporary changes in a predictor (a state) relate to temporary changes in an outcome.\n- To do this correctly, we must decompose our Level 1 predictors.\n\n## The EMA Example\n\n**Main Variables**\n\n- Outcome = `performance` (numeric score on a daily task)\n- Predictor = `stress` (self-reported daily stress)\n- Time = `studyday` (the day of the study)\n\n**Research Question**\n\n- Does a person's *daily stress* (state) predict their *daily performance*, and does their *average stress* (trait) predict their *average performance*?\n\n## Example Data\n\n\n::: {.cell replace_path='[\"../../data/\",\"\"]'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(glmmTMB)\nlibrary(easystats)\n\nema <- read_csv(\"ema_sim.csv\")\nglimpse(ema)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 984\nColumns: 4\n$ subject     <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2…\n$ studyday    <dbl> 1, 2, 3, 4, 5, 6, 8, 9, 11, 12, 13, 14, 2, 4, 6, 7, 8, 9, …\n$ performance <dbl> 2.5176277, 2.7333135, 0.7773803, 4.6899620, 1.4511123, 10.…\n$ stress      <dbl> 7.905561, 6.861336, 7.377380, 5.361727, 7.055506, 5.036938…\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\n- We plan to predict `performance` (L1) from `stress` (L1) for each subject.\n- Notice the jumps in `studyday`. Participants may not respond *every* day.\n:::\n\n## L1 Predictor Decomposition\n\n:::{.fsmaller}\nIf we use `stress` as a predictor, its slope will be an *uninterpretable blend* of the within-person and between-person effects. We must first decompose it!\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nema_prep <- ema |> \n  mutate(\n    .by = subject,\n    stress_b = mean(stress, na.rm = TRUE), # Trait (L2)\n    stress_w = stress - stress_b           # State (L1)\n  ) |> \n  print(n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 984 × 6\n  subject studyday performance stress stress_b stress_w\n    <dbl>    <dbl>       <dbl>  <dbl>    <dbl>    <dbl>\n1       1        1       2.52    7.91     6.41    1.50 \n2       1        2       2.73    6.86     6.41    0.455\n3       1        3       0.777   7.38     6.41    0.971\n# ℹ 981 more rows\n```\n\n\n:::\n:::\n\n\n## How important was this?\n\n:::{.fsmaller}\nCalculating the predictor's ICC can help us understand its multilevel structure\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_stress <- glmmTMB(stress ~ 1 + (1 | subject), data = ema)\nicc(fit_stress)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Intraclass Correlation Coefficient\n\n    Adjusted ICC: 0.644\n  Unadjusted ICC: 0.644\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller .mt4}\n- **ICC near 0:** The variable is almost entirely a *state*. Everyone has the same baseline, and all the action is in day-to-day fluctuation.\n- **ICC near 1:** The variable is almost entirely a *trait*. People differ from one another, but their daily scores never change from their baseline.\n- **ICC in between:** The variable has meaningful variance at both levels.<br>We **must** decompose it to avoid an uninterpretable, blended slope.\n\n:::\n\n## Multilevel Equation\n\n:::{.tc .b}\nLevel One (Observation)\n:::\n\n$$y_{ti} = \\beta_{0i} + \\beta_{1i} x_{ti}^{(w)} + \\color{#4daf4a}{e_{ti}}$$\n\n:::{.tc .b}\nLevel Two (Cluster)\n:::\n\n$$\\begin{align}\n\\beta_{0i} &= \\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} x_{i}^{(b)} +  \\color{#e41a1c}{u_{0i}} \\\\\n\\beta_{1i} &= \\color{#377eb8}{\\gamma_{10}} + \\color{#e41a1c}{u_{1i}}\n\\end{align}$$\n\n## Path Diagram\n\n![](../../diagrams/fluctuation1.png)\n\n## Mixed (or Reduced) Equation\n\nSubstitute the L2 equations directly into the L1 equation:\n\n$$y_{ti} = (\\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} x_{i}^{(b)} + \\color{#e41a1c}{u_{0i}}) + (\\color{#377eb8}{\\gamma_{10}} + \\color{#e41a1c}{u_{1i}}) x_{ti}^{(w)} + \\color{#4daf4a}{e_{ti}}$$\n\n:::{.fragment}\nDistribute and rearrange to group the fixed and random parts:\n\n$$y_{ti} = \\underbrace{\\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} x_{i}^{(b)} + \\color{#377eb8}{\\gamma_{10}} x_{ti}^{(w)}}_{\\text{Fixed}} + \\underbrace{\\color{#e41a1c}{u_{0i}} + \\color{#e41a1c}{u_{1i}} x_{ti}^{(w)}}_{\\text{Random}} + \\color{#4daf4a}{e_{ti}}$$\n:::\n\n## Formula\n\n:::{.fsmaller}\n$$y_{ti} = \\underbrace{\\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} x_{i}^{(b)} + \\color{#377eb8}{\\gamma_{10}} x_{ti}^{(w)}}_{\\text{Fixed}} + \\underbrace{\\color{#e41a1c}{u_{0i}} + \\color{#e41a1c}{u_{1i}} x_{ti}^{(w)}}_{\\text{(Random)}} + \\color{#4daf4a}{e_{ti}}$$\n\n**Generic**\n\n:::{.tc}\n`y ~ 1 + x_b + x_w + (1 + x_w | cluster)`\n\nwhere the [1 + x_b + x_w]{.blue} part is fixed<br>\nand the [(1 + x_w | cluster)]{.red} part is random\n:::\n\n:::{.fragment}\n**Example**\n\n:::{.tc}\n`performance ~ 1 + stress_b + stress_w`<br>\n`+ (1 + stress_w | subject)`\n:::\n:::\n:::\n\n## Fitting the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_base <- glmmTMB(\n  formula = performance ~ 1 + stress_b + stress_w + (1 + stress_w | subject),\n  data = ema_prep\n)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(fit_base, effects = \"fixed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Fixed Effects\n\nParameter   | Coefficient |   SE |         95% CI |      z |      p\n-------------------------------------------------------------------\n(Intercept) |       11.26 | 1.82 | [ 7.70, 14.82] |   6.20 | < .001\nstress b    |       -2.17 | 0.36 | [-2.88, -1.46] |  -5.99 | < .001\nstress w    |       -2.44 | 0.11 | [-2.65, -2.23] | -22.78 | < .001\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller .fragment .mt4}\nBoth traits and states matter. People with higher average stress perform worse overall $(\\gamma_{01}=-2.06)$. Additionally, on days when a person is more stressed than their own baseline, their performance drops further $(\\gamma_{10}=-0.96)$.\n:::\n\n## Interpreting the Random Effects {.smaller}\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(fit_base, effects = \"random\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Random Effects\n\nParameter                         | Coefficient | 95% CI\n--------------------------------------------------------\nSD (Intercept: subject)           |        4.94 |       \nSD (stress_w: subject)            |        0.64 |       \nCor (Intercept~stress_w: subject) |        0.01 |       \nSD (Residual)                     |        2.78 |       \n```\n\n\n:::\n:::\n\n\n- `SD (Intercept)` ($\\tau_{00}=4.94$): Even after accounting for trait stress, there is substantial variation in people's baseline performance. \n- `SD (stress_w)` ($\\tau_{11}=0.64$): The penalty for a stressful day is not identical for everyone. Some people are more reactive to daily stress than others.\n- `Cor (Intercept~stress_w)` ($\\tau_{10}=0.01$): There is virtually no correlation between baseline performance and stress reactivity.\n- `SD (Residual)` ($\\sigma=2.78$): The remaining daily fluctuation in performance that is not explained by state stress.\n\n## Visualizing Random Effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_relation(fit_base, by = c(\"stress_w\", \"subject=[sample 6]\")) |> plot()\n```\n\n::: {.cell-output-display}\n![](b_Slides_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n# Auto-Moderation\n\n## Stress Reactivity\n\n:::{.fsmaller}\nNow that we have separated stress into Trait (L2) and State (L1) components, we can ask a more complex theoretical question.\n\n:::{.fragment .mt4}\n> Does a person's average stress level (Trait) moderate their reactivity to daily stress fluctuations (State)?\n\n:::\n\n:::{.fragment .mt4}\n*Hypothesis: People who are chronically stressed may lack the coping resources to handle bad days. Therefore, the negative effect of daily stress on performance will be even stronger (steeper) for individuals with high average stress.*\n:::\n:::\n\n## Multilevel Equation\n\n:::{.tc .b}\nLevel One (Observation)\n:::\n\n$$y_{ti} = \\beta_{0i} + \\beta_{1i} x_{ti}^{(w)} + \\color{#4daf4a}{e_{ti}}$$\n\n:::{.tc .b}\nLevel Two (Cluster)\n:::\n\n$$\\begin{align}\n\\beta_{0i} &= \\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} x_{i}^{(b)} +  \\color{#e41a1c}{u_{0i}} \\\\\n\\beta_{1i} &= \\color{#377eb8}{\\gamma_{10}} + \\underbrace{\\color{#377eb8}{\\gamma_{11}} x_{i}^{(b)}}_{\\text{New}} + \\color{#e41a1c}{u_{1i}}\n\\end{align}$$\n\n## Path Diagram\n\n![](../../diagrams/fluctuation2.png)\n\n## Fitting the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_auto <- glmmTMB(\n  formula = performance ~ 1 + stress_b * stress_w + (1 + stress_w | subject),\n  data = ema_prep\n)\nmodel_parameters(fit_auto, effects = \"fixed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Fixed Effects\n\nParameter           | Coefficient |   SE |         95% CI |     z |      p\n--------------------------------------------------------------------------\n(Intercept)         |       11.32 | 1.61 | [ 8.17, 14.47] |  7.05 | < .001\nstress b            |       -2.18 | 0.32 | [-2.80, -1.56] | -6.89 | < .001\nstress w            |       -0.71 | 0.32 | [-1.34, -0.08] | -2.22 | 0.026 \nstress b × stress w |       -0.35 | 0.06 | [-0.47, -0.23] | -5.63 | < .001\n```\n\n\n:::\n:::\n\n\n## Simple Slopes Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_slopes(fit_auto, slope = \"stress_w\", by = \"stress_b=[quartiles]\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated Marginal Effects\n\nstress_b | Slope |   SE |         95% CI |      z |      p\n----------------------------------------------------------\n3.94     | -2.09 | 0.11 | [-2.31, -1.87] | -18.53 | < .001\n4.74     | -2.37 | 0.09 | [-2.56, -2.19] | -25.01 | < .001\n5.93     | -2.79 | 0.11 | [-3.01, -2.57] | -24.79 | < .001\n\nMarginal effects estimated for stress_w\nType of slope was dY/dX\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\nThe performance cost of daily (state) stress is largest for those with higher average (trait) stress. There is evidence of a \"compounding\" effect.\n:::\n\n## Visualizing the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_relation(fit_auto, by = c(\"stress_w\", \"stress_b=[quartiles]\")) |> plot()\n```\n\n::: {.cell-output-display}\n![](b_Slides_files/figure-revealjs/unnamed-chunk-11-1.png){width=960}\n:::\n:::\n\n\n# Continuous Time\n\n## The Unequal Time Problem\n\n:::{.fsmaller}\n- In the last lecture, we used an AR(1) structure to handle autocorrelation.\n- Discrete AR(1) assumes that the time interval between step 1 and step 2 is identical to the interval between step 2 and step 3.\n- In EMA and daily diary research, this is almost never true. Participants miss surveys, or surveys are triggered randomly.\n:::\n\n:::{.fragment}\n\n::: {.cell}\n\n```{.r .cell-code}\nema_prep |> filter(subject == 1) |> pull(studyday)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1]  1  2  3  4  5  6  8  9 11 12 13 14\n```\n\n\n:::\n:::\n\n:::{.fsmaller}\nA discrete AR(1) model would treat the jump from Day 6 to Day 8 exactly the same as the jump from Day 1 to Day 2.\n:::\n:::\n\n## The Spatial Exponential Model\n\n:::{.fsmaller}\n- Just like our discrete AR(1) model, we partition the error into white noise $(e_{ti})$ and autocorrelated error $(v_{ti})$. \n- However, the Spatial Exponential structure calculates the **true time gap** between any two observations ($t$ and $t'$) to handle unequal intervals.\n:::\n\n:::{.fragment}\n$$\\color{#4daf4a}{\\mathbf{v}_i} \\sim \\text{EXP}(0, \\color{#4daf4a}{\\sigma_v}, \\color{#4daf4a}{\\rho})$$\n:::\n\n:::{.fragment}\n$$\\text{Corr}(v_{ti}, v_{t'i}) = \\color{#4daf4a}{\\rho}^{|t - t'|}$$\n\n:::{.fsmaller}\n- If $\\rho = 0.5$ and the gap is **1 day**, the correlation is $0.5^1 = 0.50$.\n- If the gap is **3 days**, the correlation decays to $0.5^3 = 0.125$.\n:::\n:::\n\n## Prepping the Time Factor\n\n:::{.fsmaller}\nTo use the `exp()` covariance structure in `glmmTMB`, we need to convert our numeric time variable into a special sorted factor using `numFactor()`. \n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nema_clean <- \n  ema_prep |> \n  # Sort by studyday within subjects\n  arrange(subject, studyday) |> \n  # Create a numFactor for exp()\n  mutate(time = numFactor(studyday)) |> \n  print(n = 4)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 984 × 7\n  subject studyday performance stress stress_b stress_w time \n    <dbl>    <dbl>       <dbl>  <dbl>    <dbl>    <dbl> <fct>\n1       1        1       2.52    7.91     6.41    1.50  (1)  \n2       1        2       2.73    6.86     6.41    0.455 (2)  \n3       1        3       0.777   7.38     6.41    0.971 (3)  \n4       1        4       4.69    5.36     6.41   -1.04  (4)  \n# ℹ 980 more rows\n```\n\n\n:::\n:::\n\n\n\n## Fitting the Exponential Model\n\n:::{.fsmaller}\nInstead of `ar1()`, we simply add the `exp()` term to the formula.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_exp <- glmmTMB(\n  formula = performance ~ \n    1 + stress_b * stress_w +  # fixed Effects\n    (1 + stress_w | subject) + # random Effects\n    exp(0 + time | subject),   # exp by time (no intercept)\n  data = ema_clean\n)\nmodel_parameters(fit_exp, effects = \"fixed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Fixed Effects\n\nParameter           | Coefficient |   SE |         95% CI |     z |      p\n--------------------------------------------------------------------------\n(Intercept)         |       11.57 | 1.60 | [ 8.44, 14.71] |  7.24 | < .001\nstress b            |       -2.23 | 0.31 | [-2.84, -1.61] | -7.07 | < .001\nstress w            |       -0.90 | 0.28 | [-1.46, -0.35] | -3.18 | 0.001 \nstress b × stress w |       -0.31 | 0.05 | [-0.42, -0.20] | -5.65 | < .001\n```\n\n\n:::\n:::\n\n\n## Exponential Parameters {.smaller}\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVarCorr(fit_exp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nConditional model:\n Groups    Name        Std.Dev. Corr                                                      \n subject   (Intercept) 4.72949                                                            \n           stress_w    0.47192  -0.035                                                    \n subject.1 time(1)     2.93399                                                            \n           time(2)     2.93399  0.646                                                     \n           time(3)     2.93399  0.417  0.646                                              \n           time(4)     2.93399  0.269  0.417 0.646                                        \n           time(5)     2.93399  0.174  0.269 0.417 0.646                                  \n           time(6)     2.93399  0.112  0.174 0.269 0.417 0.646                            \n           time(7)     2.93399  0.072  0.112 0.174 0.269 0.417 0.646                      \n           time(8)     2.93399  0.047  0.072 0.112 0.174 0.269 0.417 0.646                \n           time(9)     2.93399  0.030  0.047 0.072 0.112 0.174 0.269 0.417 0.646          \n           time(10)    2.93399  0.020  0.030 0.047 0.072 0.112 0.174 0.269 0.417 0.646    \n           ...         ...      ...    ...   ...   ...   ...   ...   ...   ...   ...   ...\n Residual              0.93007                                                            \n```\n\n\n:::\n:::\n\n\n\n\n- $\\color{#4daf4a}{\\sigma_v}=2.96431$: The magnitude of the drift\n- $\\color{#4daf4a}{\\rho}=0.645$: The carryover (or memory) of the drift\n\n## The Exponential Decay in Action\n\n:::{.fsmaller}\nLook closely at the correlation matrix for `subject.1`. The model calculates a baseline 1-day correlation ($\\rho$) of **0.645**. \n:::\n\n:::{.fragment .fsmaller}\nBecause we used `exp()`, the correlation for a gap of $t$ days is exactly $\\rho^t$.\n\n- **1-Day Gap** (e.g., Day 1 to Day 2): $\\rho^1 = 0.645$\n- **2-Day Gap** (e.g., Day 1 to Day 3): $0.645^2 = 0.416$\n- **3-Day Gap** (e.g., Day 1 to Day 4): $0.645^3 = 0.269$\n- **4-Day Gap** (e.g., Day 1 to Day 5): $0.645^4 = 0.173$\n\nThe model automatically handles the missing days by applying the correct mathematical decay to the gaps!\n:::\n\n## Visualizing the Decay\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](b_Slides_files/figure-revealjs/unnamed-chunk-18-1.png){width=960}\n:::\n:::\n\n\n## Did the Exponential Decay Help?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_lrt(fit_auto, fit_exp)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName     |   Model | df | df_diff |   Chi2 |      p\n---------------------------------------------------\nfit_auto | glmmTMB |  8 |         |        |       \nfit_exp  | glmmTMB | 10 |       2 | 199.61 | < .001\n```\n\n\n:::\n\n```{.r .cell-code}\ncompare_performance(fit_auto, fit_exp, metrics = c(\"AIC\", \"BIC\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Comparison of Model Performance Indices\n\nName     |   Model |  AIC (weights) |  BIC (weights)\n----------------------------------------------------\nfit_auto | glmmTMB | 5182.6 (<.001) | 5221.8 (<.001)\nfit_exp  | glmmTMB | 4987.0 (>.999) | 5035.9 (>.999)\n```\n\n\n:::\n:::\n\n",
    "supporting": [
      "b_Slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}