<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-494df7ee9f4d3fbed323cea6af7dcc0b.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/quarto-contrib/lordicon-bundle-1.9.0/bundle.js"></script><meta charset="utf-8">
  <meta name="generator" content="quarto-1.9.37">

  <meta name="author" content="Jeffrey Girard">
  <title>PSYC894 – Multilevel Modeling</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #cccccc; background-color: #303030; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ffcfaf; } /* Alert */
    code span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
    code span.at { } /* Attribute */
    code span.bn { color: #dca3a3; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #f0dfaf; } /* ControlFlow */
    code span.ch { color: #dca3a3; } /* Char */
    code span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
    code span.co { color: #7f9f7f; } /* Comment */
    code span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
    code span.do { color: #7f9f7f; } /* Documentation */
    code span.dt { color: #dfdfbf; } /* DataType */
    code span.dv { color: #dcdccc; } /* DecVal */
    code span.er { color: #c3bf9f; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #c0bed1; } /* Float */
    code span.fu { color: #efef8f; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #7f9f7f; font-weight: bold; } /* Information */
    code span.kw { color: #f0dfaf; } /* Keyword */
    code span.op { color: #f0efd0; } /* Operator */
    code span.ot { color: #efef8f; } /* Other */
    code span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
    code span.sc { color: #dca3a3; } /* SpecialChar */
    code span.ss { color: #cc9393; } /* SpecialString */
    code span.st { color: #cc9393; } /* String */
    code span.va { } /* Variable */
    code span.vs { color: #cc9393; } /* VerbatimString */
    code span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-53e3d2ac1773787e2a3f577cd3a68c1f.css">
  <link rel="stylesheet" href="../../styles.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section class="title-slide slide level1 my-title center">
<h1><span class="blue">Multilevel Modeling</span></h1>
<p>Characterizing Change</p>
<div class="my-grey">
<p><span>Spring 2026 | CLAS | PSYC 894</span><br> <span>Jeffrey M. Girard | Lecture 12a</span></p>
</div>
<p><img data-src="../../img/city-girl.svg" class="absolute" style="bottom: 30px; right: 0px; width: 400px; "></p>
</section>

<section class="slide level2">
<h2>Roadmap</h2>
<div class="columns pv4">
<div class="column" style="width:60%;">
<ol type="1">
<li>Linear Trajectories
<ul>
<li><em>Structuring Time</em></li>
<li><em>Growth Modeling</em></li>
</ul></li>
<li>Nonlinear Trajectories
<ul>
<li><em>Transforming Time</em></li>
<li><em>Instantaneous Change</em></li>
</ul></li>
</ol>
</div><div class="column tc pv4" style="width:40%;">
<p><lord-icon src="../../icons/map.json" colors="secondary:#2a76dd" trigger="hover" class="rc"></lord-icon></p>
</div></div>
</section>
<section>
<section class="title-slide slide level1 center">
<h1>Linear Trajectories</h1>

</section>
<section class="slide level2">
<h2>Fluctuation vs.&nbsp;Growth</h2>

<img data-src="a_Slides_files/figure-revealjs/unnamed-chunk-1-1.png" width="1056" class="r-stretch"></section>
<section class="slide level2">
<h2>Modeling the Trajectory</h2>
<div class="fsmaller">
<ul>
<li>In Week 11, we treated the baseline as stable. We were most interested in the observation-specific fluctuations around that baseline.</li>
<li>Moving forward with longitudinal change models, we are now most interested in the <strong>shape of change</strong> over the entire assessment period.</li>
<li>We want to know the <em>starting point</em>, the overall <em>trajectory</em>, and the overall <em>shape</em> (e.g., linear, quadratic, or logarithmic).</li>
<li>To capture this shape, we simply <strong>add a time variable (or variables) to the model as a Level 1 predictor</strong>.</li>
<li>Random intercepts will allow each participant to have their own starting point and random time slopes will allow each to have their own trajectory.</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Centering Time</h2>
<div class="fsmaller">
<ul>
<li>The <strong>intercept</strong> represents the expected outcome when all predictors equal zero. Therefore, we need to be mindful about what zero represents for <em>time</em>.</li>
<li><em>If we study grades 9 through 12, then using the numbers <code>9</code> to <code>12</code> will result in an intercept corresponding to grade 0, which isn’t very meaningful here.</em></li>
</ul>
<div class="fragment mt1">
<ul>
<li>We usually <span class="b blue">center</span> time so that <code>0</code> and the intercept represent a meaningful starting point such as the first or baseline assessment in the study.</li>
<li><em>We can re-code time (by subtracting 9) so that <code>0</code> and the intercept represent grade 9, and <code>1</code>, <code>2</code>, and <code>3</code> represent grades 10, 11, and 12, respectively.</em></li>
</ul>
</div>
</div>
</section>
<section class="slide level2">
<h2>Scaling Time</h2>
<div class="fsmaller">
<ul>
<li>The <strong>slope</strong> of a predictor represents the expected change in the outcome for a 1-unit increase in that predictor. Therefore, we need to be mindful about what a 1-unit increase actually represents for <em>time</em>.</li>
<li><em>If a 10-year study records time in days (from <code>0</code> to <code>3650</code>), the slope will represent daily growth. This coefficient might be uninterpretable or confusingly small (e.g., a gain of 0.002).</em></li>
</ul>
<div class="fragment mt1">
<ul>
<li>We usually <span class="b blue">scale</span> time so that <code>1</code> represents a meaningful, intuitive interval like “one year” or “one academic semester”.</li>
<li><em>We can re-code time (by dividing days by 365) so that <code>1</code> represents a full year. The slope now reflects a much more intuitive gain of 0.73 per year.</em></li>
</ul>
</div>
</div>
</section>
<section class="slide level2">
<h2>Example Data</h2>
<div class="cell" data-replace_path="[&quot;../../data/&quot;,&quot;&quot;]">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a>vocab_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"vocab_sim.csv"</span>)</span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(vocab_raw)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 900
Columns: 5
$ subject    &lt;dbl&gt; 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, …
$ program    &lt;chr&gt; "B", "B", "B", "B", "B", "B", "A", "A", "A", "A", "A",…
$ age_months &lt;dbl&gt; 120, 132, 144, 156, 168, 180, 120, 132, 144, 156, 168,…
$ vocab      &lt;dbl&gt; 45.38913, 59.32121, 72.81737, 82.83264, 88.51938, 93.2…
$ hours_read &lt;dbl&gt; 3.399861, 2.572877, 1.571513, 2.955250, 3.413900, 3.60…</code></pre>
</div>
</div>
<div class="fsmaller">
<p>Each of 150 subjects was assessed for vocabulary size annually. Notice that our time variable is <code>age_months</code>, starting at 120 months (10 years old).</p>
</div>
</section>
<section class="slide level2">
<h2>Preparing the Time Variable</h2>
<div class="fsmaller">
<p>If we use <code>age_months</code> as our predictor, our intercept will represent vocabulary at an age of 0 months, and our slope will represent month-to-month growth. We need to fix this!</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a aria-hidden="true" tabindex="-1"></a>vocab <span class="ot">&lt;-</span> vocab_raw <span class="sc">|&gt;</span> </span>
<span id="cb3-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb3-3"><a aria-hidden="true" tabindex="-1"></a>    <span class="co"># Center at 120 months (Baseline), then scale by 12 (Years)</span></span>
<span id="cb3-4"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">time =</span> (age_months <span class="sc">-</span> <span class="dv">120</span>) <span class="sc">/</span> <span class="dv">12</span></span>
<span id="cb3-5"><a aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb3-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">3</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 900 × 6
  subject program age_months vocab hours_read  time
    &lt;dbl&gt; &lt;chr&gt;        &lt;dbl&gt; &lt;dbl&gt;      &lt;dbl&gt; &lt;dbl&gt;
1       1 B              120  45.4       3.40     0
2       1 B              132  59.3       2.57     1
3       1 B              144  72.8       1.57     2
# ℹ 897 more rows</code></pre>
</div>
</div>
</section>
<section class="slide level2">
<h2>Multilevel Equation (Linear)</h2>
<div class="tc b">
<p>Level One (Observation)</p>
</div>
<p><span class="math display">\[y_{ti} = \beta_{0i} + \beta_{1i} T_{ti} + \color{#4daf4a}{e_{ti}}\]</span></p>
<div class="tc b">
<p>Level Two (Cluster)</p>
</div>
<p><span class="math display">\[\begin{align}
\beta_{0i} &amp;= \color{#377eb8}{\gamma_{00}} + \color{#e41a1c}{u_{0i}} \\
\beta_{1i} &amp;= \color{#377eb8}{\gamma_{10}} + \color{#e41a1c}{u_{1i}}
\end{align}\]</span></p>
<div class="fsmaller mt4">
<p>Notice that time is the only predictor in the model. We are just defining the average starting point (<span class="math inline">\(\color{#377eb8}{\gamma_{00}}\)</span>) and the average rate of linear change (<span class="math inline">\(\color{#377eb8}{\gamma_{10}}\)</span>), along with how much different people vary around those averages.</p>
</div>
</section>
<section class="slide level2 fsmaller">
<h2>Multilevel Equation Part 2</h2>
<div class="tc b">
<p>Level One (Observation)</p>
</div>
<p><span class="math display">\[
\color{#4daf4a}{e_{ti}} \sim \text{Normal}(0, \color{#4daf4a}{\sigma})
\]</span></p>
<div class="tc b">
<p>Level Two (Cluster)</p>
</div>
<p><span class="math display">\[
\begin{bmatrix}\color{#e41a1c}{u_{0i}}\\ \color{#e41a1c}{u_{1i}}\end{bmatrix} \sim \text{MVN}\left(\begin{bmatrix}0\\0\end{bmatrix}, \begin{bmatrix}\color{#e41a1c}{\tau_{00}} &amp; \\ \color{#e41a1c}{\tau_{10}} &amp; \color{#e41a1c}{\tau_{11}}\end{bmatrix}\right)
\]</span></p>
<div class="mt4">
<ul>
<li><span class="math inline">\(\color{#4daf4a}{\sigma}\)</span>: The within-person spread around their own trajectory.</li>
<li><span class="math inline">\(\color{#e41a1c}{\tau_{00}}\)</span>: The between-person spread in starting points at baseline.</li>
<li><span class="math inline">\(\color{#e41a1c}{\tau_{11}}\)</span>: The between-person spread in the rate of growth over time.</li>
<li><span class="math inline">\(\color{#e41a1c}{\tau_{10}}\)</span>: The correlation between a person’s starting point and rate of growth.</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Path Diagram</h2>

<img data-src="../../diagrams/longitudinal_change.png" class="r-stretch"></section>
<section class="slide level2">
<h2>Formula</h2>
<div class="fsmaller">
<p><span class="math display">\[y_{ti} = \underbrace{\color{#377eb8}{\gamma_{00}} + \color{#377eb8}{\gamma_{10}} T_{ti}}_{\text{Fixed}} + \underbrace{\color{#e41a1c}{u_{0i}} + \color{#e41a1c}{u_{1i}} T_{ti}}_{\text{(Random)}} + \color{#4daf4a}{e_{ti}}\]</span></p>
<p><strong>Generic</strong></p>
<div class="tc">
<p><code>y ~ 1 + T + (1 + T | person)</code></p>
<p>where the <span class="blue">1 + T</span> part is fixed<br> and the <span class="red">(1 + T | person)</span> part is random</p>
</div>
<div class="fragment">
<p><strong>Example</strong></p>
<div class="tc">
<p><code>vocab ~ 1 + time + (1 + time | subject)</code></p>
</div>
</div>
</div>
</section>
<section class="slide level2">
<h2>Fitting the Linear Model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a>fit_linear <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(</span>
<span id="cb5-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> vocab <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> time <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> time <span class="sc">|</span> subject),</span>
<span id="cb5-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> vocab</span>
<span id="cb5-4"><a aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="fragment">
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit_linear, <span class="at">effects =</span> <span class="st">"fixed"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter   | Coefficient |   SE |         95% CI |     z |      p
------------------------------------------------------------------
(Intercept) |       53.33 | 0.56 | [52.23, 54.42] | 95.54 | &lt; .001
time        |        8.06 | 0.24 | [ 7.59,  8.54] | 33.27 | &lt; .001</code></pre>
</div>
</div>
<div class="fsmaller">
<ul>
<li><code>(Intercept)</code> (<span class="math inline">\(\gamma_{00}\)</span>): The average expected vocabulary score at Baseline.</li>
<li><code>time</code> (<span class="math inline">\(\gamma_{10}\)</span>): The average expected annual change in vocabulary score.</li>
</ul>
</div>
</div>
</section>
<section class="slide level2">
<h2>Interpreting the Linear Model</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit_linear, <span class="at">effects =</span> <span class="st">"random"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Random Effects

Parameter                     | Coefficient | 95% CI
----------------------------------------------------
SD (Intercept: subject)       |        5.24 |       
SD (time: subject)            |        2.59 |       
Cor (Intercept~time: subject) |        0.68 |       
SD (Residual)                 |        6.06 |       </code></pre>
</div>
</div>
<div class="fsmaller">
<ul>
<li><code>SD (Intercept)</code> (<span class="math inline">\(\tau_{00}\)</span>): The variation in starting scores among subjects.</li>
<li><code>SD (time)</code> (<span class="math inline">\(\tau_{11}\)</span>): The variation in the rate of linear growth among subjects.</li>
<li><code>Cor (Intercept~time)</code> (<span class="math inline">\(\tau_{10}\)</span>): A negative correlation suggests that those who start lower tend to grow faster.</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Visualizing Fixed Effects</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the growth curve for the average subject</span></span>
<span id="cb10-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_relation</span>(fit_linear, <span class="at">by =</span> <span class="st">"time"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="a_Slides_files/figure-revealjs/unnamed-chunk-7-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">
<h2>Visualizing Trajectories</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the growth curves for six randomly selected subjects</span></span>
<span id="cb11-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_relation</span>(fit_linear, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"time"</span>, <span class="st">"subject=[sample 6]"</span>)) <span class="sc">|&gt;</span> <span class="fu">plot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="a_Slides_files/figure-revealjs/unnamed-chunk-8-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">
<h2>Linear Slopes</h2>
<div class="fsmaller">
<p>In a linear model, the growth rate stays constant over time. Here, vocab growth is always 8.06 per year with no acceleration or deceleration possible.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_slopes</span>(fit_linear, <span class="at">trend =</span> <span class="st">"time"</span>, <span class="at">by =</span> <span class="st">"time"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Estimated Marginal Effects

time | Slope |   SE |       95% CI |     z |      p
---------------------------------------------------
0    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | &lt; .001
1    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | &lt; .001
2    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | &lt; .001
3    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | &lt; .001
4    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | &lt; .001
5    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | &lt; .001

Marginal effects estimated for time
Type of slope was dY/dX</code></pre>
</div>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Nonlinear Trajectories</h1>

</section>
<section class="slide level2">
<h2>Beyond Linear Growth</h2>
<div class="fsmaller">
<ul>
<li>Linear models assume a constant rate of change. They force a straight line through the data.</li>
<li>However, human behavior, learning, and biological processes rarely grow at exactly the same speed forever.</li>
<li>To allow our trajectories to bend and take on nonlinear shapes, we simply apply <strong>mathematical transformations</strong> to our time variable.</li>
<li>Instead of just predicting the outcome from raw Time, we can predict it from the Square of Time, the Logarithm of Time, the Exponentiation of Time, etc.</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Visualizing the Shapes</h2>

<img data-src="a_Slides_files/figure-revealjs/unnamed-chunk-10-1.png" width="1152" class="r-stretch"><div class="fsmaller">
<ul>
<li><strong>Quadratic:</strong> acceleration, deceleration, or reversal (e.g., marital satisfaction)</li>
<li><strong>Logarithmic:</strong> rapid early growth that plateaus (e.g., therapy response)</li>
<li><strong>Exponential:</strong> slow early growth that compounds (e.g., viral outbreak)</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Returning to Our Data</h2>
<div class="fsmaller">
<ul>
<li>Let’s apply this theory to our <code>vocab</code> dataset. We are modeling vocabulary growth in children from Baseline (Age 10) to Year 5 (Age 15).</li>
<li>Before we just test every math function in R, we should ask:<br> <span class="b blue"><em>Which shapes make theoretical sense for this process?</em></span></li>
</ul>
<div class="fragment mt4">
<ul>
<li><span class="b dark-red">Exponential:</span> Unlikely. Human vocabulary does not compound toward infinity; there are natural cognitive and linguistic ceilings.</li>
<li><span class="b orange">Quadratic:</span> Possible. Growth might be fast early on and then slow down significantly as they get older and possibly even reverse in old age.</li>
<li><span class="b dark-green">Logarithmic:</span> Highly likely. Language acquisition often follows a rapid early learning phase that gradually plateaus as ceilings are approached.</li>
</ul>
</div>
</div>
</section>
<section class="slide level2">
<h2>Our Testing Plan</h2>
<div class="fsmaller">
<ul>
<li>Based on our developmental theory, we will drop the Exponential model.</li>
<li>We will formally test a <strong>Quadratic</strong> model and a <strong>Logarithmic</strong> model against our standard <strong>Linear</strong> baseline to see which shape best fits the actual data.</li>
<li>Let’s start by building the Quadratic model. We need to add a new predictor to our equation: <strong>Time-Squared</strong>.</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Quadratic Equations</h2>
<div class="tc b">
<p>Level One (Observation)</p>
</div>
<p><span class="math display">\[y_{ti} = \beta_{0i} + \beta_{1i} T_{ti} + \beta_{2i} T_{ti}^2 + \color{#4daf4a}{e_{ti}}\]</span></p>
<div class="tc b">
<p>Level Two (Cluster)</p>
</div>
<p><span class="math display">\[\begin{align}
\beta_{0i} &amp;= \color{#377eb8}{\gamma_{00}} + \color{#e41a1c}{u_{0i}} \\
\beta_{1i} &amp;= \color{#377eb8}{\gamma_{10}} + \color{#e41a1c}{u_{1i}} \\
\beta_{2i} &amp;= \color{#377eb8}{\gamma_{20}} + \color{#e41a1c}{u_{2i}}
\end{align}\]</span></p>
</section>
<section class="slide level2">
<h2>Orthogonal Polynomials</h2>
<ul>
<li>Using raw polynomials can introduce multicollinearity problems when <span class="math inline">\(T\)</span> and <span class="math inline">\(T^2\)</span> are highly correlated.</li>
</ul>
<div class="fragment">
<ul>
<li><strong>The Solution:</strong> We use <span class="b blue">Orthogonal Polynomials</span> via the <code>poly()</code> function to transform our time variable into fully uncorrelated linear and quadratic components.</li>
</ul>
</div>
<div class="fragment">
<ul>
<li><strong>The Catch:</strong> The components are centered and re-scaled,<br>so the coefficient values cannot be interpreted normally.</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>Quadratic Modeling</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a aria-hidden="true" tabindex="-1"></a>fit_quad <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(</span>
<span id="cb14-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> vocab <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> <span class="fu">poly</span>(time, <span class="dv">2</span>) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">poly</span>(time, <span class="dv">2</span>) <span class="sc">|</span> subject),</span>
<span id="cb14-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> vocab</span>
<span id="cb14-4"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit_quad, <span class="at">effects =</span> <span class="st">"fixed"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter         | Coefficient |    SE |            95% CI |      z |      p
-----------------------------------------------------------------------------
(Intercept)       |       73.48 |  0.90 | [  71.71,  75.25] |  81.49 | &lt; .001
time [1st degree] |      413.03 | 12.42 | [ 388.70, 437.37] |  33.27 | &lt; .001
time [2nd degree] |     -107.38 |  4.65 | [-116.50, -98.26] | -23.08 | &lt; .001</code></pre>
</div>
</div>
<div class="fsmaller fragment">
<p>The intercept is the overall average vocabulary score across all time points (due to centering). The significant and positive 1st degree term indicates the overall average growth trend is increasing. The significant and negative 2nd degree term indicates the trajectory is curved downwards (growth is slowing).</p>
</div>
</section>
<section class="slide level2">
<h2>Quadratic Visualization</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the growth curve for the average subject</span></span>
<span id="cb16-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_relation</span>(fit_quad, <span class="at">by =</span> <span class="st">"time"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="a_Slides_files/figure-revealjs/unnamed-chunk-12-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">
<h2>Quadratic Visualization</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the growth curve for six randomly selected subjects</span></span>
<span id="cb17-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_relation</span>(fit_quad, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"time"</span>, <span class="st">"subject=[sample 6]"</span>)) <span class="sc">|&gt;</span> <span class="fu">plot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="a_Slides_files/figure-revealjs/unnamed-chunk-13-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">
<h2>Quadratic Slopes</h2>
<div class="fsmaller">
<p>In a quadratic model, the growth rate is accelerating or decelerating by a fixed, constant amount per one-unit increase in time. Here, vocab growth is always decelerating by 2.87 per year (see the diff column).</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_slopes</span>(fit_quad, <span class="at">trend =</span> <span class="st">"time"</span>, <span class="at">by =</span> <span class="st">"time"</span>) <span class="sc">|&gt;</span></span>
<span id="cb18-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> <span class="fu">diff</span>(<span class="fu">c</span>(<span class="cn">NA</span>, Slope)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>time | Slope |   SE |             CI |     z |      p |  diff
-------------------------------------------------------------
0    | 15.24 | 0.46 | [14.34, 16.13] | 33.42 | &lt; .001 |      
1    | 12.37 | 0.35 | [11.67, 13.06] | 34.97 | &lt; .001 | -2.87
2    |  9.50 | 0.27 | [ 8.97, 10.03] | 35.13 | &lt; .001 | -2.87
3    |  6.63 | 0.23 | [ 6.18,  7.07] | 29.04 | &lt; .001 | -2.87
4    |  3.76 | 0.25 | [ 3.27,  4.24] | 15.09 | &lt; .001 | -2.87
5    |  0.89 | 0.32 | [ 0.26,  1.52] |  2.77 |  0.006 | -2.87</code></pre>
</div>
</div>
</section>
<section class="slide level2">
<h2>Logarithmic Equations</h2>
<div class="tc b">
<p>Level One (Observation)</p>
</div>
<p><span class="math display">\[y_{ti} = \beta_{0i} + \beta_{1i} \log(T_{ti}+1) + \color{#4daf4a}{e_{ti}}\]</span></p>
<div class="tc b">
<p>Level Two (Cluster)</p>
</div>
<p><span class="math display">\[\begin{align}
\beta_{0i} &amp;= \color{#377eb8}{\gamma_{00}} + \color{#e41a1c}{u_{0i}} \\
\beta_{1i} &amp;= \color{#377eb8}{\gamma_{10}} + \color{#e41a1c}{u_{1i}}
\end{align}\]</span></p>

<aside><div>
<p><strong><em>Note:</em></strong> In R, <code>log()</code> defaults to the natural logarithm (base <span class="math inline">\(e\)</span>). We add <span class="math inline">\(+1\)</span> to our time variable for two reasons. First, <span class="math inline">\(\log(0)\)</span> is undefined. Second, <span class="math inline">\(\log(1)=0\)</span>, which ensures that our intercept still represents the expected outcome at <span class="math inline">\(T=0\)</span>.</p>
</div></aside></section>
<section class="slide level2">
<h2>Logarithmic Modeling</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a aria-hidden="true" tabindex="-1"></a>fit_log <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(</span>
<span id="cb20-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> vocab <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> <span class="fu">log</span>(time <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">+</span> (<span class="dv">1</span> <span class="sc">+</span> <span class="fu">log</span>(time <span class="sc">+</span> <span class="dv">1</span>) <span class="sc">|</span> subject),</span>
<span id="cb20-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> vocab</span>
<span id="cb20-4"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb20-5"><a aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit_log, <span class="at">effects =</span> <span class="st">"fixed"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter      | Coefficient |   SE |         95% CI |     z |      p
---------------------------------------------------------------------
(Intercept)    |       47.62 | 0.54 | [46.55, 48.68] | 87.59 | &lt; .001
time + 1 [log] |       23.59 | 0.69 | [22.24, 24.94] | 34.27 | &lt; .001</code></pre>
</div>
</div>
<div class="fsmaller fragment">
<p>The intercept represents the expected vocabulary score exactly at Baseline (Age 10). The significant and positive logarithmic term indicates that vocabulary size increases over time. This growth is modeled as fastest at the beginning and gradually slowing down over time.</p>
</div>
</section>
<section class="slide level2">
<h2>Logarithmic Visualization</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the growth curve for the average subject</span></span>
<span id="cb22-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_relation</span>(fit_log, <span class="at">by =</span> <span class="st">"time"</span>) <span class="sc">|&gt;</span> <span class="fu">plot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="a_Slides_files/figure-revealjs/unnamed-chunk-16-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">
<h2>Logarithmic Visualization</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># Plot the growth curve for six randomly selected subjects</span></span>
<span id="cb23-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_relation</span>(fit_log, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"time"</span>, <span class="st">"subject=[sample 6]"</span>)) <span class="sc">|&gt;</span> <span class="fu">plot</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>

</div>
<img data-src="a_Slides_files/figure-revealjs/unnamed-chunk-17-1.png" width="960" class="r-stretch"></section>
<section class="slide level2">
<h2>Logarithmic Slopes</h2>
<div class="fsmaller">
<p>In a logarithmic model, the growth rate changes non-uniformly over time, following a pattern of diminishing returns. Here, vocab growth decelerates rapidly at first and then more gradually over time (see the diff column).</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">estimate_slopes</span>(fit_log, <span class="at">trend =</span> <span class="st">"time"</span>, <span class="at">by =</span> <span class="st">"time"</span>) <span class="sc">|&gt;</span></span>
<span id="cb24-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">diff =</span> <span class="fu">diff</span>(<span class="fu">c</span>(<span class="cn">NA</span>, Slope)))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>time | Slope |   SE |             CI |     z |      p |   diff
--------------------------------------------------------------
0    | 23.59 | 0.69 | [22.24, 24.94] | 34.27 | &lt; .001 |       
1    | 11.79 | 0.34 | [11.12, 12.47] | 34.27 | &lt; .001 | -11.79
2    |  7.86 | 0.23 | [ 7.41,  8.31] | 34.27 | &lt; .001 |  -3.93
3    |  5.90 | 0.17 | [ 5.56,  6.23] | 34.27 | &lt; .001 |  -1.97
4    |  4.72 | 0.14 | [ 4.45,  4.99] | 34.25 | &lt; .001 |  -1.18
5    |  3.93 | 0.11 | [ 3.71,  4.16] | 34.27 | &lt; .001 |  -0.79</code></pre>
</div>
</div>
</section>
<section class="slide level2">
<h2>Model Comparison</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">compare_performance</span>(fit_linear, fit_quad, fit_log, <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">"AIC"</span>, <span class="st">"BIC"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Comparison of Model Performance Indices

Name       |   Model |  AIC (weights) |  BIC (weights)
------------------------------------------------------
fit_linear | glmmTMB | 6323.5 (&lt;.001) | 6352.3 (&lt;.001)
fit_quad   | glmmTMB | 5860.0 (&lt;.001) | 5908.0 (&lt;.001)
fit_log    | glmmTMB | 5793.0 (&gt;.999) | 5821.8 (&gt;.999)</code></pre>
</div>
</div>
<div class="fsmaller pv4">
<p>In our simulated data, the Logarithmic change model has the lowest AIC and BIC, suggesting it provides the best fit for this specific process. Note as well that the weights for both metrics are overwhelmingly in favor of this model.</p>
</div>
</section>
<section class="slide level2">
<h2>What about Autocorrelation?</h2>
<ul>
<li><p>In Fluctuation models, it was important to use the AR1 or EXP covariance structure because we had no other way to explain why “today” looked like “yesterday”</p></li>
<li><p>In Growth models, we have a systematic trend. We expect Year 2 to be related to Year 1 because they both sit on the same developmental path</p></li>
<li><p>Usually, once the shape of the growth is correctly specified, the remaining residuals are independent enough that we don’t need the extra complexity of AR1 or EXP</p></li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>

    document.addEventListener("DOMContentLoaded", function() {

      // 1. Re-classify stderr to warnings and messages and strip empty lines

      document.querySelectorAll('.cell-output-stderr').forEach(function(output) {

        // Strip invisible zero-width spaces Quarto sometimes inserts

        const text = output.textContent.replace(/[\u200B-\u200D\uFEFF]/g, '').trim();

    

        // Remove completely empty blocks to fix the gaps

        if (text === '') {

          output.remove();

          return;

        }

    

        if (output.textContent.includes('Warning:')) {

          output.classList.replace('cell-output-stderr', 'cell-output-warning');

        } else {

          output.classList.replace('cell-output-stderr', 'cell-output-message');

        }

      });

    

      // 2. Physically merge adjacent blocks into one seamless block

      ['.cell-output-message', '.cell-output-warning'].forEach(function(selector) {

        const elements = document.querySelectorAll(selector);

        elements.forEach(function(current) {

          if (!current.parentNode) return; // Skip if it was already merged and removed

    

          let next = current.nextElementSibling;

          while (next && next.classList.contains(selector.substring(1))) {

            let currentCode = current.querySelector('pre code');

            let nextCode = next.querySelector('pre code');

    

            if (currentCode && nextCode) {

               // Clean up formatting and append to the primary block

               let appendText = nextCode.innerHTML.replace(/^\n+|\n+$/g, '');

               if (appendText !== '') {

                 currentCode.innerHTML += '\n' + appendText;

               }

            }

    

            let toRemove = next;

            next = next.nextElementSibling;

            toRemove.remove();

          }

        });

      });

    });

    </script>

    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/jmgirard\.github\.io\/psyc894\/");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>