---
title: "Week 12: Longitudinal Analysis 2"
---

<!-- Lecture a -->

## [12a] Characterizing Change

### Topics
1. Linear Trajectories
    + *Structuring Time*
    + *Growth Modeling*
    
2. Nonlinear Trajectories
    + *Transforming Time*
    + *Instantaneous Change*

### File Downloads
- [vocab_sim.csv](../../data/vocab_sim.csv){download="vocab_sim.csv"}

### Readings
- [S\&F Chapter 10: Multilevel modeling with longitudinal data](https://www.learn-mlms.com/10-module-10.html){target="_blank"}
- [Hoffman Chapter 6: Describing within-person change over time](https://canvas.ku.edu/courses/182539/pages/12a-characterizing-change){target="_blank"}
- [Hox et al. (2012): Growth Curve Modeling from a MLM Perspective](https://canvas.ku.edu/courses/182539/pages/12a-characterizing-change){target="_blank}

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[12a] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::


<!-- Lecture b -->

## [12b] Predicting Change

### Topics
1. Time-Invariant Predictors
    + *Explaining the Baseline*
    + *Explaining the Growth Rate*
    
2. Time-Varying Predictors
    + *Decomposing Predictors*
    + *Explaining the Fluctuations*

### File Downloads
- [vocab_sim.csv](../../data/vocab_sim.csv){download="vocab_sim.csv"}

### Readings
- [Hoffman Chapter 7: Time-invariant predictors in longitudinal models](https://canvas.ku.edu/courses/182539/pages/12b-predicting-change-+-lab){target="_blank"}
- [Hoffman Chapter 9: Time-varying predictors in models of within-person change](https://canvas.ku.edu/courses/182539/pages/12b-predicting-change-+-lab){target="_blank"}


### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[12b] Slideshow">
</iframe>
```

::: {.fs80}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../11/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Week 11</a>

  <a href="../../D/13/index.html" class="btn btn-primary" role="button">Week 13&nbsp;&nbsp;&raquo;</a>
</div>
```
