{
  "hash": "1197be306a5f67136e3f0d38c36a9c17",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlecture: \"14a\"\nmetadata-files:\n  - ../../_slide-settings.yml\nformat:\n  revealjs:\n    theme: default\n---\n\n::: {.my-title}\n# [Multilevel Modeling]{.blue}\nEffect Sizes & Reporting\n\n::: {.my-grey}\n[{{< meta semester >}} | CLAS | {{< meta course >}}]{}<br />\n[Jeffrey M. Girard | Lecture {{< meta lecture >}}]{}\n:::\n\n![](../../img/city-girl.svg){.absolute bottom=30 right=0 width=\"400\"}\n:::\n\n\n::: {.cell}\n\n:::\n\n\n## Roadmap\n\n::: {.columns .pv4}\n\n::: {.column width=\"60%\"}\n1. Effect Sizes\n    + *Marginal vs. Conditional R²*\n    + *StdX and StdYX Effects*\n    \n2. The Reporting Checklist\n    + *Intro and Methods*\n    + *Results and Discussion*\n    \n:::\n\n::: {.column .tc .pv4 width=\"40%\"}\n{{< lif \"../../icons/map.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n\n:::\n\n# Effect Sizes in MLMs\n\n## Beyond *p*-Values {.fsmaller}\n\n:::{.columns}\n:::{.column width=\"60%\"}\n- Statistical significance tells us if an effect exists. It does not tell us if the effect is meaningful.\n- **Effect sizes** contextualize the magnitude of results from your model.\n- They answer the question: \"What is the practical significance of this result?\"\n- Reviewers and journal editors increasingly demand effect sizes for all key findings.\n:::\n:::{.column .tc .pv4 width=\"40%\"}\n{{< lif \"../../icons/rulers.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n:::\n\n## Two Types of Effect Sizes {.fsmaller}\n\n**Unstandardized Effect Sizes**\n\n- Expressed in the raw units of the dependent variable\n- *e.g., For every extra year of service, salary increases by $1000*\n- Useful when the outcome variable has an intuitive metric\n\n**Standardized Effect Sizes**\n\n- Measure magnitude without units\n- *e.g., The model explains 24 percent of the variance in patient satisfaction*\n- Useful when the original metrics are abstract\n\n## The R-squared Metric {.fsmaller}\n\n- The most common standardized effect size is R²\n- It represents the proportion of variance in the outcome variable explained by the model and all its included effects\n- In single-level regression, the math is straightforward:\n$$R^2 = \\frac{\\text{Explained Variance}}{\\text{Total Variance}}$$\n- It yields an intuitive measure ranging from:<br>\n0 (nothing explained) to 1 (everything explained)\n- However, applying this to Multilevel Models is notoriously difficult\n\n## The Multilevel Variance Problem {.fsmaller}\n\nWhy can't we just use a single R² for an MLM?\n\n- **Multiple Denominators:**<br>\nTotal variance is partitioned. Do we want to explain total outcome variance, within-cluster variance, or between-cluster variance?\n- **Multiple Numerators:**<br>\nWe have multiple sources of explained variance. We have fixed effects at Level-1, fixed effects at Level-2, random intercepts, and random slopes.\n- Summing these up into a single neat number obscures the complexity of the data structure and can be misleading.\n\n## The Rights & Sterba Framework {.fsmaller}\n\n- Rights \\& Sterba (2019) developed a complex framework for R² in MLMs.\n- Because there are so many combinations of numerators and denominators, their framework yields **12 different R-squared measures** for a single model.\n- For example:\n  - Proportion of total variance explained by Level-1 fixed effects.\n  - Proportion of within-cluster variance explained by random slopes.\n  - Proportion of between-cluster variance explained by random intercepts.\n\n## Practical Constraints {.fsmaller}\n\n- This framework is academically rigorous and statistically exact.\n- If your research question relies on isolating exactly how much Level-2 variance is explained by a Level-1 random slope, it is the tool to use.\n- However, for most applied researchers, reporting 12 effect sizes per model is overwhelming for both the author and the reader.\n- Most journals expect a simpler, two-part summary of model performance.\n\n## The Nakagawa Framework {.fsmaller}\n\n- The widely accepted standard for applied MLMs is the framework developed by Nakagawa \\& Schielzeth (2013).\n- It simplifies the problem by providing two metrics:\n  - **Marginal R²:** Variance explained by only the fixed effects.\n  - **Conditional R²:** Variance explained by the entire model<br>(fixed effects plus random effects).\n- This is what we will usually report in practice.\n\n# Calculating<br> R-squared\n\n## Setup and Data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(glmmTMB)\nlibrary(easystats)\n```\n:::\n\n\n\n::: {.cell replace_path='[\"../../data/\",\"\"]'}\n\n```{.r .cell-code}\nhospital <- read_csv(\"hospital_sim.csv\")\nglimpse(hospital)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 2,000\nColumns: 6\n$ satisfaction  <dbl> -0.30518145, 0.18461383, 1.28090155, 0.35863181, 0.…\n$ wait_time     <dbl> 0.35091220, -0.53187051, -0.36259725, -1.04860229, …\n$ visit_type    <chr> \"Emergency\", \"Emergency\", \"Routine\", \"Routine\", \"Em…\n$ hospital      <chr> \"H01\", \"H01\", \"H01\", \"H01\", \"H01\", \"H01\", \"H01\", \"H…\n$ nurse_ratio   <dbl> -0.6830383, -0.6830383, -0.6830383, -0.6830383, -0.…\n$ hospital_type <chr> \"Non-Teaching\", \"Non-Teaching\", \"Non-Teaching\", \"No…\n```\n\n\n:::\n:::\n\n\n## Preparing the Data\n\n:::{.fsmaller}\nTo calculate accurate R-squared values, we do not need to standardize or center our Level-2 predictors. However, we **must** decompose our Level-1 predictors to properly isolate the within-cluster and between-cluster variance.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nl2_means <- hospital |> \n  summarize(.by = hospital, wait_b = mean(wait_time))\n\ndat_unstd <- hospital |> \n  left_join(l2_means, by = \"hospital\") |> \n  mutate(wait_w = wait_time - wait_b)\n```\n:::\n\n\n## Fitting the Baseline Model\n\n:::{.fsmaller}\nNow we fit our model using our unstandardized, centered predictors.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_unstd <- glmmTMB(\n  formula = satisfaction ~ 1 + wait_b + wait_w + nurse_ratio + \n    (1 + wait_w | hospital), \n  data = dat_unstd,\n  REML = TRUE\n)\n```\n:::\n\n\n## Extracting R-squared\n\n:::{.fsmaller}\nWe can extract our Nakagawa R² values cleanly using the \\{performance\\} package from the \\{easystats\\} ecosystem.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nr2(fit_unstd)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# R2 for Mixed Models\n\n  Conditional R2: 0.642\n     Marginal R2: 0.176\n```\n\n\n:::\n:::\n\n\n## Interpreting R-squared {.fsmaller}\n\n- **Marginal R² (0.176):** Fixed effects explain ~17.6% of the variance.\n  - *Prediction Framing:* How well we predict a new observation from a **new, unseen cluster**. We must rely solely on the population averages.\n- **Conditional R² (0.642):** The entire model (fixed + random) explains ~64.2% of the variance.\n  - *Prediction Framing:* How well we predict a new observation from an **existing, known cluster**. We can fine-tune the prediction using that cluster's random effects.\n- **The Difference:** The random effects alone account for roughly 46.6% of the variance (Conditional minus Marginal).\n\n# Standardized Effects\n\n## To Standardize Y or Not? \n\n:::{.fsmaller}\nBefore we standardize our slopes, we must ask a theoretical question about our outcome variable (Y).\n\n- **Meaningful Outcomes:** If Y has a well understood and intuitive metric (e.g., dollars, days, blood pressure), we leave it in its raw units. We only standardize the predictors, yielding [StdX]{.b .blue} slopes.\n- **Arbitrary Outcomes:** If Y is an abstract scale (e.g., a satisfaction survey, an anxiety inventory), raw points are less intuitive. We standardize the predictors AND the outcome, yielding [StdYX]{.b .blue} slopes.\n:::\n\n## The Predictor Trap \n\n:::{.fsmaller}\nRegardless of using StdX or StdYX, we must be incredibly careful about how we standardize our multilevel predictors (X).\n\n- **The \"Global\" Trap:** Standard software defaults to standardizing based on the total sample's mean and SD. Here is why that fails:\n    + **Mixing Levels:** A Level-1 predictor can only explain within-cluster variance. Dividing its slope by the total SD (which includes between-cluster differences) unfairly penalizes it, making strong local effects look artificially weak.\n    + **Cluster Weighting:** Level-2 predictors are attributes of the cluster. If you standardize across all data rows, a cluster with 500 observations influences the math 10x more than a cluster with 50 observations, distorting the meaning of a \"standard unit\" for that variable.\n    \n:::\n\n## StdX: Data Preparation (L2)\n\n:::{.fsmaller}\nTo avoid mixing levels, we create a distinct Level-2 dataset using summarize. Standardizing within this dataset uses the correct means and SDs.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Create a distinct Level-2 dataset\nl2_std <- hospital |> \n  summarize(\n    wait_b = mean(wait_time),\n    nurse_ratio = first(nurse_ratio),\n    .by = hospital\n  ) |> \n  mutate(\n    # 2. Standardize across the Level-2 clusters\n    wait_b_z = standardize(wait_b),\n    nurse_z = standardize(nurse_ratio)\n  )\n```\n:::\n\n\n## StdX: Data Preparation (L1)\n\n:::{.fsmaller}\nNext, we join those standardized L2 variables back to our L1 data and strictly standardize the within-cluster variance.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat_stdx <- hospital |> \n  # 3. Join the Level-2 data back to the main dataset\n  left_join(l2_std, by = \"hospital\") |> \n  mutate(\n    # 4. Isolate and standardize the within-cluster variance\n    wait_w = wait_time - wait_b,\n    wait_w_z = standardize(wait_w)\n  )\n```\n:::\n\n\n## StdX: Model & Interpretation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_stdx <- glmmTMB(\n  formula = satisfaction ~ 1 + wait_b_z + wait_w_z + nurse_z + \n    (1 + wait_w_z | hospital), \n  data = dat_stdx,\n  REML = TRUE\n)\nmodel_parameters(fit_stdx, effects = \"fixed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Fixed Effects\n\nParameter   | Coefficient |   SE |         95% CI |         z |      p\n----------------------------------------------------------------------\n(Intercept) |   -6.20e-17 | 0.11 | [-0.21,  0.21] | -5.90e-16 | > .999\nwait b z    |        0.02 | 0.11 | [-0.19,  0.23] |      0.18 | 0.860 \nwait w z    |       -0.37 | 0.03 | [-0.43, -0.31] |    -11.90 | < .001\nnurse z     |        0.19 | 0.14 | [-0.08,  0.47] |      1.41 | 0.158 \n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\n- A one *SD* increase in a patient's wait time (relative to their hospital's average) significantly decreases their satisfaction by 0.37 *raw points*.\n:::\n\n## The Problem with Global StdYX {.fsmaller}\n\nIf Y is an arbitrary scale, you might be tempted to standardize Y globally before fitting your model (like you would for OLS). [Do not do this for multilevel data!]{.b .dark-red} \n\n- **The ICC Penalty:** If you standardize Y globally, the denominator includes both Level-1 and Level-2 variance. \n- **The Trap:** A Level-1 predictor can only explain Level-1 variance. By dividing its effect by the *total* variance pool, you mathematically penalize it. \n- **The Result:** If your model has high Level-2 variance (high ICC), your Level-1 StdYX effects will look artificially tiny.\n- **The Solution:** We must use [Level-Specific Standardization]{.b .blue}.\n\n## Level-Specific StdYX \n\n:::{.fsmaller}\nThere is no automated R package for this (yet). We manually take the coefficients from our **StdX model** (where X is standardized but Y is raw) and divide them by the level-specific standard deviations of Y.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1. Calculate the standard deviation of the hospital means (Level 2 SD)\nsd_y_b <- hospital |> \n  summarize(sat_b = mean(satisfaction), .by = hospital) |> \n  pull(sat_b) |> sd() |> print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7003727\n```\n\n\n:::\n\n```{.r .cell-code}\n# 2. Calculate the standard deviation of the within-cluster scores (Level 1 SD)\nsd_y_w <- hospital |> \n  mutate(sat_b = mean(satisfaction), .by = hospital) |> \n  mutate(sat_w = satisfaction - sat_b) |> \n  pull(sat_w) |> sd() |> print()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.7221508\n```\n\n\n:::\n:::\n\n\n## Calculating & Interpreting StdYX\n\n:::{.fsmaller}\nWe divide the slopes from our `fit_stdx` model by the matching SD of Y.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# L2 StdYX Slope = (L2 StdX Slope) / (L2 SD of Y)\n0.19 / 0.700 # nurse_z\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.2714286\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\n- A one *between-hospital* SD increase in nurse ratio was associated with a non-significant increase in satisfaction of 0.27 *between-hospital* SDs.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# L1 StdYX Slope = (L1 StdX Slope) / (L1 SD of Y)\n-0.37 / 0.722 # wait_w_z\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.5124654\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\n- A one *within-hospital* SD increase in wait time was associated with a significant decrease in satisfaction of 0.51 *within-hospital* SDs.\n:::\n\n# The Reporting<br> Checklist\n\n## The Goal of Reporting {.fsmaller}\n\n- Multilevel modeling involves dozens of minor analytical decisions. \n- Centering, random effect structures, and estimation algorithms all drastically change your results.\n- Your goal in a manuscript is not just to report the p-values, but to provide enough transparent detail that another researcher could perfectly replicate your model from your raw data.\n\n## IMRD: Introduction {.fsmaller}\n\nThe justification for an MLM should begin before the Methods section.\n\n**What to include:**\n\n- Acknowledge the nested structure of your data in your hypotheses.\n- Clearly state the levels of analysis (e.g., L1 is patients, L2 is hospitals).\n- Distinguish between within-cluster and between-cluster hypotheses. Do not hypothesize a generic \"effect of wait time\" if you specifically mean \"when a patient waits longer than their hospital's average.\"\n\n## IMRD: Methods (Data) {.fsmaller}\n\nThe participants section must describe the sample sizes at all levels.\n\n**What to include:**\n\n- Total number of Level-1 observations (e.g., N = 2,000 patients).\n- Total number of Level-2 clusters (e.g., J = 40 hospitals).\n- The average cluster size, minimum cluster size, and maximum cluster size (e.g., an average of 50 patients per hospital, ranging from 12 to 89).\n\n## IMRD: Methods (Variables) {.fsmaller}\n\nYou must explicitly state how every variable was handled.\n\n**What to include:**\n\n- Identify which variables were measured at Level-1 and Level-2.\n- Explicitly state your centering decisions. Did you grand-mean center? Did you group-mean center (cluster-mean center)? \n- State why you chose that centering method. Did you want to isolate the purely within-cluster effect, or were you aiming for a blended effect?\n\n## IMRD: Methods (Modeling) {.fsmaller}\n\nClearly identify the mathematical tools you used.\n\n**What to include:**\n\n- Software and packages with version numbers (e.g., R version 4.3.1, glmmTMB version 1.1.8).\n- The estimation method used. Did you use Restricted Maximum Likelihood (REML) or standard Maximum Likelihood (ML)? \n- Mention the specific optimizer if you had to change it from the default to achieve convergence.\n\n## IMRD: Methods (Structure) {.fsmaller}\n\nExplain how you built your equations.\n\n**What to include:**\n\n- Describe the random effects structure. Did you include random intercepts? Random slopes?\n- State whether you allowed the random intercepts and slopes to correlate.\n- If you had to simplify your random effects structure due to singular fits or convergence issues, document that process here. Explain what was dropped and why.\n\n## IMRD: Methods (Descriptives & Reliability) {.fsmaller}\n\nYou cannot simply present a correlation matrix for a multilevel dataset.\n\n**What to include:**\n\n- A table of means, standard deviations, and correlations for all Level-1 variables.\n- A completely separate table of descriptives and correlations for all Level-2 variables, calculated at the cluster level.\n- Evidence of reliability for your continuous predictors. Predictors measured with high error will bias your regression coefficients.\n\n## IMRD: Methods (Missing Data) {.fsmaller}\n\nMissing data is especially dangerous in MLMs. Deleting one Level-2 cluster due to a missing covariate takes all of its Level-1 observations down with it.\n\n**What to include:**\n\n- The exact percentage of missing data reported separately for Level-1 variables and Level-2 variables.\n- The method used to handle missingness (e.g., Full Information Maximum Likelihood or Multiple Imputation).\n- If using listwise deletion, explicitly state the final analytical sample size and justify why deletion was acceptable.\n\n## IMRD: Results (The Null Model) {.fsmaller}\n\nAlways report the baseline before adding predictors.\n\n**What to include:**\n\n- Report the unconditional ICC from the null model.\n- Provide a plain language interpretation: \"The ICC was 0.22, indicating that 22 percent of the variance in patient satisfaction is attributable to differences between hospitals.\"\n- This justifies the need for multilevel modeling in the first place.\n\n## IMRD: Results (Fixed Effects) {.fsmaller}\n\nReport the focal tests of your hypotheses.\n\n**What to include:**\n\n- The unstandardized coefficient estimate.\n- The 95% Confidence Interval for the estimate.\n- The standard error.\n- The exact p-value.\n- A plain language interpretation of the direction and magnitude of the effect.\n\n## IMRD: Results (Random Effects) {.fsmaller}\n\nDo not ignore the random portion of the model.\n\n**What to include:**\n\n- The variance (or standard deviation) of the random intercepts.\n- The variance (or standard deviation) of any random slopes.\n- The correlation between random intercepts and random slopes.\n- The residual (Level-1) variance.\n\n## IMRD: Results (Effect Sizes) {.fsmaller}\n\nProvide the big picture summary of model performance.\n\n**What to include:**\n\n- Report both the Marginal R2 and Conditional R2.\n- Cite Nakagawa \\& Schielzeth (2013) to clarify your framework.\n- If comparing multiple models (e.g., a baseline model vs a full model), report the change in R2 (Delta R2) or use AIC/BIC to discuss relative model fit.\n- Clearly state whether you are reporting raw, StdX, or StdYX slopes.\n\n## IMRD: Results (Model Building Sequence) {.fsmaller}\n\nReviewers want to see the sequence of models you estimated.\n\n**What to include:**\n\n- **Step 1:** The Null Model to establish baseline variance and the ICC.\n- **Step 2:** The Random Coefficients Model containing only Level-1 predictors to see if those slopes vary significantly across clusters.\n- **Step 3:** The Full Contextual Model containing Level-1 and Level-2 predictors, including any cross-level interactions.\n\n## IMRD: Discussion (Language) {.fsmaller}\n\nMultilevel modeling uses the word \"effect\" constantly (e.g., fixed effects, random effects). This can create a semantic trap.\n\n**What to watch out for:**\n\n- Do not let the statistical terminology bleed into causal claims in your discussion section.\n- Unless you have a rigorously controlled experimental design, your \"fixed effects\" are merely associations or predictions.\n- Carefully edit your conclusions to ensure you are not implying a causal mechanism that your design cannot support.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}