---
title: "Week 13: Model Evaluation"
---

<!-- Lecture a -->

## [13a] Troubleshooting

### Topics
1. Understanding Non-Convergence
    + *The Likelihood Surface*
    + *Diagnosing Warnings*
    
2. A Systematic Workflow
    + *Top-Down Troubleshooting*
    + *Bayesian Estimation*

### File Downloads
- [trouble_sim.csv](../../data/trouble_sim.csv){download="trouble_sim.csv"}

### Readings
- [S\&F Chapter 7](https://www.learn-mlms.com/07-module-7.html){target="_blank"} (Troubleshooting)
- [Brauer \& Curtin (2018)](https://canvas.ku.edu/courses/182539/pages/13a-troubleshooting){target="_blank"} (Troubleshooting, pp. 403--406)
- [Barr et al. (2013)](https://canvas.ku.edu/courses/182539/pages/13a-troubleshooting){target="_blank"} (Pruning Dilemma)
- [Matsuchek et al. (2017)](https://canvas.ku.edu/courses/182539/pages/13a-troubleshooting){target="_blank"} (Pruning Dilemma)
- [Muth et al. (2018)](https://canvas.ku.edu/courses/182539/pages/13a-troubleshooting){target="_blank"} (Bayesian, rstanarm)
- [Burkner (2017)](https://canvas.ku.edu/courses/182539/pages/13a-troubleshooting){target="_blank"} (Bayesian, brms)

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[13a] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::


<!-- Lecture b -->

## [13b] Diagnostics

### Topics
1. A Systematic Workflow
    + *Predictive Performance*
    + *Visual Diagnostics*

2. Sensitivity & Easy Fixes
    + *Bootstrapping & LSM*
    + *DHARMa & Outliers*

### File Downloads
- [diag_sim.csv](../../data/diag_sim.csv){download="diag_sim.csv"}

### Readings
- [S\&F Chapter 12](https://www.learn-mlms.com/12-module-12.html){target="_blank"}
- [HMV Chapter 13](https://canvas.ku.edu/courses/182539/pages/13b-diagnostics-+-lab?module_item_id=4317594){target="_blank"}


### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[13b] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../../C/12/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Week 12</a>

  <a href="../14/index.html" class="btn btn-primary" role="button">Week 14&nbsp;&nbsp;&raquo;</a>
</div>
```
