<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-c22d5dff81f50d6ca627b6188dc743b9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/quarto-contrib/lordicon-bundle-1.9.0/bundle.js"></script><meta charset="utf-8">
  <meta name="generator" content="quarto-1.10.18">

  <meta name="author" content="Jeffrey Girard">
  <title>PSYC894 – Multilevel Modeling</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    /* Default styles provided by pandoc.
    ** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
    */
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: 1.5em;}
    div.column{flex: auto;}
    @media screen {
    div.columns{gap: min(4vw, 1.5em);}
    div.column{overflow-x: auto;}
    }
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    html { -webkit-text-size-adjust: 100%; }
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
      }
    pre.numberSource { margin-left: 3em;  padding-left: 4px; }
    div.sourceCode
      { color: #cccccc; background-color: #303030; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span.al { color: #ffcfaf; } /* Alert */
    code span.an { color: #7f9f7f; font-weight: bold; } /* Annotation */
    code span.at { } /* Attribute */
    code span.bn { color: #dca3a3; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #f0dfaf; } /* ControlFlow */
    code span.ch { color: #dca3a3; } /* Char */
    code span.cn { color: #dca3a3; font-weight: bold; } /* Constant */
    code span.co { color: #7f9f7f; } /* Comment */
    code span.cv { color: #7f9f7f; font-weight: bold; } /* CommentVar */
    code span.do { color: #7f9f7f; } /* Documentation */
    code span.dt { color: #dfdfbf; } /* DataType */
    code span.dv { color: #dcdccc; } /* DecVal */
    code span.er { color: #c3bf9f; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #c0bed1; } /* Float */
    code span.fu { color: #efef8f; } /* Function */
    code span.im { } /* Import */
    code span.in { color: #7f9f7f; font-weight: bold; } /* Information */
    code span.kw { color: #f0dfaf; } /* Keyword */
    code span.op { color: #f0efd0; } /* Operator */
    code span.ot { color: #efef8f; } /* Other */
    code span.pp { color: #ffcfaf; font-weight: bold; } /* Preprocessor */
    code span.sc { color: #dca3a3; } /* SpecialChar */
    code span.ss { color: #cc9393; } /* SpecialString */
    code span.st { color: #cc9393; } /* String */
    code span.va { } /* Variable */
    code span.vs { color: #cc9393; } /* VerbatimString */
    code span.wa { color: #7f9f7f; font-weight: bold; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-53e3d2ac1773787e2a3f577cd3a68c1f.css">
  <link rel="stylesheet" href="../../styles.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">


<section class="title-slide slide level1 my-title center">
<h1><span class="blue">Multilevel Modeling</span></h1>
<p>Effect Sizes &amp; Reporting</p>
<div class="my-grey">
<p><span>Spring 2026 | CLAS | PSYC 894</span><br> <span>Jeffrey M. Girard | Lecture 14a</span></p>
</div>
<p><img data-src="../../img/city-girl.svg" class="absolute" style="bottom: 30px; right: 0px; width: 400px; "></p>
</section>

<section class="slide level2">
<h2>Roadmap</h2>
<div class="columns pv4">
<div class="column" style="width:60%;">
<ol type="1">
<li>Effect Sizes
<ul>
<li><em>Marginal vs.&nbsp;Conditional R²</em></li>
<li><em>StdX and StdYX Effects</em></li>
</ul></li>
<li>The Reporting Checklist
<ul>
<li><em>Intro and Methods</em></li>
<li><em>Results and Discussion</em></li>
</ul></li>
</ol>
</div><div class="column tc pv4" style="width:40%;">
<p><lord-icon src="../../icons/map.json" colors="secondary:#2a76dd" trigger="hover" class="rc"></lord-icon></p>
</div></div>
</section>
<section>
<section class="title-slide slide level1 center">
<h1>Effect Sizes in MLMs</h1>

</section>
<section class="slide level2 fs80">
<h2>Beyond <em>p</em>-Values</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Statistical significance tells us if an effect exists. It does not tell us if the effect is meaningful.</li>
<li><strong>Effect sizes</strong> contextualize the magnitude of results from your model.</li>
<li>They answer the question: “What is the practical significance of this result?”</li>
<li>Reviewers and journal editors increasingly demand effect sizes for all key findings.</li>
</ul>
</div><div class="column tc pv4" style="width:40%;">
<p><lord-icon src="../../icons/rulers.json" colors="secondary:#2a76dd" trigger="hover" class="rc"></lord-icon></p>
</div></div>
</section>
<section class="slide level2 fs80">
<h2>Two Types of Effect Sizes</h2>
<p><strong>Unstandardized Effect Sizes</strong></p>
<ul>
<li>Expressed in the raw units of the dependent variable</li>
<li><em>e.g., For every extra year of service, salary increases by $1000</em></li>
<li>Useful when the outcome variable has an intuitive metric</li>
</ul>
<p><strong>Standardized Effect Sizes</strong></p>
<ul>
<li>Measure magnitude without units</li>
<li><em>e.g., The model explains 24 percent of the variance in patient satisfaction</em></li>
<li>Useful when the original metrics are abstract</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>The R-squared Metric</h2>
<ul>
<li>The most common standardized effect size is R²</li>
<li>It represents the proportion of variance in the outcome variable explained by the model and all its included effects</li>
<li>In single-level regression, the math is straightforward: <span class="math display">\[R^2 = \frac{\text{Explained Variance}}{\text{Total Variance}}\]</span></li>
<li>It yields an intuitive measure ranging from:<br> 0 (nothing explained) to 1 (everything explained)</li>
<li>However, applying this to Multilevel Models is notoriously difficult</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>The Multilevel Variance Problem</h2>
<p>Why can’t we just use a single R² for an MLM?</p>
<ul>
<li><strong>Multiple Denominators:</strong><br> Total variance is partitioned. Do we want to explain total outcome variance, within-cluster variance, or between-cluster variance?</li>
<li><strong>Multiple Numerators:</strong><br> We have multiple sources of explained variance. We have fixed effects at Level-1, fixed effects at Level-2, random intercepts, and random slopes.</li>
<li>Summing these up into a single neat number obscures the complexity of the data structure and can be misleading.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>The Rights &amp; Sterba Framework</h2>
<ul>
<li>Rights &amp; Sterba (2019) developed a complex framework for R² in MLMs.</li>
<li>Because there are so many combinations of numerators and denominators, their framework yields <strong>12 different R-squared measures</strong> for a single model.</li>
<li>For example:
<ul>
<li>Proportion of total variance explained by Level-1 fixed effects.</li>
<li>Proportion of within-cluster variance explained by random slopes.</li>
<li>Proportion of between-cluster variance explained by random intercepts.</li>
</ul></li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>Practical Constraints</h2>
<ul>
<li>This framework is academically rigorous and statistically exact.</li>
<li>If your research question relies on isolating exactly how much Level-2 variance is explained by a Level-1 random slope, it is the tool to use.</li>
<li>However, for most applied researchers, reporting 12 effect sizes per model is overwhelming for both the author and the reader.</li>
<li>Most journals expect a simpler, two-part summary of model performance.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>The Nakagawa Framework</h2>
<ul>
<li>The widely accepted standard for applied MLMs is the framework developed by Nakagawa &amp; Schielzeth (2013).</li>
<li>It simplifies the problem by providing two metrics:
<ul>
<li><strong>Marginal R²:</strong> Variance explained by only the fixed effects.</li>
<li><strong>Conditional R²:</strong> Variance explained by the entire model<br>(fixed effects plus random effects).</li>
</ul></li>
<li>This is what we will usually report in practice.</li>
</ul>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Calculating<br> R-squared</h1>

</section>
<section class="slide level2">
<h2>Setup and Data</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(glmmTMB)</span>
<span id="cb1-3"><a aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(easystats)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<div class="cell" data-replace_path="[&quot;../../data/&quot;,&quot;&quot;]">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a aria-hidden="true" tabindex="-1"></a>hospital <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"hospital_sim.csv"</span>)</span>
<span id="cb2-2"><a aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(hospital)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 2,000
Columns: 6
$ satisfaction  &lt;dbl&gt; -0.30518145, 0.18461383, 1.28090155, 0.35863181, 0.…
$ wait_time     &lt;dbl&gt; 0.35091220, -0.53187051, -0.36259725, -1.04860229, …
$ visit_type    &lt;chr&gt; "Emergency", "Emergency", "Routine", "Routine", "Em…
$ hospital      &lt;chr&gt; "H01", "H01", "H01", "H01", "H01", "H01", "H01", "H…
$ nurse_ratio   &lt;dbl&gt; -0.6830383, -0.6830383, -0.6830383, -0.6830383, -0.…
$ hospital_type &lt;chr&gt; "Non-Teaching", "Non-Teaching", "Non-Teaching", "No…</code></pre>
</div>
</div>
</section>
<section class="slide level2">
<h2>Preparing the Data</h2>
<div class="fs80">
<p>To calculate accurate R-squared values, we do not need to standardize or center our Level-2 predictors. However, we <strong>must</strong> decompose our Level-1 predictors to properly isolate the within-cluster and between-cluster variance.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a aria-hidden="true" tabindex="-1"></a>l2_means <span class="ot">&lt;-</span> hospital <span class="sc">|&gt;</span> </span>
<span id="cb4-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">.by =</span> hospital, <span class="at">wait_b =</span> <span class="fu">mean</span>(wait_time))</span>
<span id="cb4-3"><a aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a aria-hidden="true" tabindex="-1"></a>dat_unstd <span class="ot">&lt;-</span> hospital <span class="sc">|&gt;</span> </span>
<span id="cb4-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(l2_means, <span class="at">by =</span> <span class="st">"hospital"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb4-6"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">wait_w =</span> wait_time <span class="sc">-</span> wait_b)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>Fitting the Baseline Model</h2>
<div class="fs80">
<p>Now we fit our model using our unstandardized, centered predictors.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a aria-hidden="true" tabindex="-1"></a>fit_unstd <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(</span>
<span id="cb5-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> satisfaction <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> wait_b <span class="sc">+</span> wait_w <span class="sc">+</span> nurse_ratio <span class="sc">+</span> </span>
<span id="cb5-3"><a aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">+</span> wait_w <span class="sc">|</span> hospital), </span>
<span id="cb5-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat_unstd,</span>
<span id="cb5-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">REML =</span> <span class="cn">TRUE</span></span>
<span id="cb5-6"><a aria-hidden="true" tabindex="-1"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>Extracting R-squared</h2>
<div class="fs80">
<p>We can extract our Nakagawa R² values cleanly using the {performance} package from the {easystats} ecosystem.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a aria-hidden="true" tabindex="-1"></a><span class="fu">r2</span>(fit_unstd)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># R2 for Mixed Models

  Conditional R2: 0.642
     Marginal R2: 0.176</code></pre>
</div>
</div>
</section>
<section class="slide level2 fs80">
<h2>Interpreting R-squared</h2>
<ul>
<li><strong>Marginal R² (0.176):</strong> Fixed effects explain ~17.6% of the variance.
<ul>
<li><em>Prediction Framing:</em> How well we predict a new observation from a <strong>new, unseen cluster</strong>. We must rely solely on the population averages.</li>
</ul></li>
<li><strong>Conditional R² (0.642):</strong> The entire model (fixed + random) explains ~64.2% of the variance.
<ul>
<li><em>Prediction Framing:</em> How well we predict a new observation from an <strong>existing, known cluster</strong>. We can fine-tune the prediction using that cluster’s random effects.</li>
</ul></li>
<li><strong>The Difference:</strong> The random effects alone account for roughly 46.6% of the variance (Conditional minus Marginal).</li>
</ul>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Standardized Effects</h1>

</section>
<section class="slide level2">
<h2>To Standardize Y or Not?</h2>
<div class="fs80">
<p>Before we standardize our slopes, we must ask a theoretical question about our outcome variable (Y).</p>
<ul>
<li><strong>Meaningful Outcomes:</strong> If Y has a well understood and intuitive metric (e.g., dollars, days, blood pressure), we leave it in its raw units. We only standardize the predictors, yielding <span class="b blue">StdX</span> slopes.</li>
<li><strong>Arbitrary Outcomes:</strong> If Y is an abstract scale (e.g., a satisfaction survey, an anxiety inventory), raw points are less intuitive. We standardize the predictors AND the outcome, yielding <span class="b blue">StdYX</span> slopes.</li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>The Predictor Trap</h2>
<div class="fs80">
<p>Regardless of using StdX or StdYX, we must be incredibly careful about how we standardize our multilevel predictors (X).</p>
<ul>
<li><strong>The “Global” Trap:</strong> Standard software defaults to standardizing based on the total sample’s mean and SD. Here is why that fails:
<ul>
<li><strong>Mixing Levels:</strong> A Level-1 predictor can only explain within-cluster variance. Dividing its slope by the total SD (which includes between-cluster differences) unfairly penalizes it, making strong local effects look artificially weak.</li>
<li><strong>Cluster Weighting:</strong> Level-2 predictors are attributes of the cluster. If you standardize across all data rows, a cluster with 500 observations influences the math 10x more than a cluster with 50 observations, distorting the meaning of a “standard unit” for that variable.</li>
</ul></li>
</ul>
</div>
</section>
<section class="slide level2">
<h2>StdX: Data Preparation (L2)</h2>
<div class="fs80">
<p>To avoid mixing levels, we create a distinct Level-2 dataset using summarize. Standardizing within this dataset uses the correct means and SDs.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Create a distinct Level-2 dataset</span></span>
<span id="cb8-2"><a aria-hidden="true" tabindex="-1"></a>l2_std <span class="ot">&lt;-</span> hospital <span class="sc">|&gt;</span> </span>
<span id="cb8-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(</span>
<span id="cb8-4"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">wait_b =</span> <span class="fu">mean</span>(wait_time),</span>
<span id="cb8-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">nurse_ratio =</span> <span class="fu">first</span>(nurse_ratio),</span>
<span id="cb8-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">.by =</span> hospital</span>
<span id="cb8-7"><a aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">|&gt;</span> </span>
<span id="cb8-8"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb8-9"><a aria-hidden="true" tabindex="-1"></a>    <span class="co"># 2. Standardize across the Level-2 clusters</span></span>
<span id="cb8-10"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">wait_b_z =</span> <span class="fu">standardize</span>(wait_b),</span>
<span id="cb8-11"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">nurse_z =</span> <span class="fu">standardize</span>(nurse_ratio)</span>
<span id="cb8-12"><a aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2">
<h2>StdX: Data Preparation (L1)</h2>
<div class="fs80">
<p>Next, we join those standardized L2 variables back to our L1 data and strictly standardize the within-cluster variance.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a aria-hidden="true" tabindex="-1"></a>dat_stdx <span class="ot">&lt;-</span> hospital <span class="sc">|&gt;</span> </span>
<span id="cb9-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="co"># 3. Join the Level-2 data back to the main dataset</span></span>
<span id="cb9-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(l2_std, <span class="at">by =</span> <span class="st">"hospital"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb9-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb9-5"><a aria-hidden="true" tabindex="-1"></a>    <span class="co"># 4. Isolate and standardize the within-cluster variance</span></span>
<span id="cb9-6"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">wait_w =</span> wait_time <span class="sc">-</span> wait_b,</span>
<span id="cb9-7"><a aria-hidden="true" tabindex="-1"></a>    <span class="at">wait_w_z =</span> <span class="fu">standardize</span>(wait_w)</span>
<span id="cb9-8"><a aria-hidden="true" tabindex="-1"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section class="slide level2 fs90">
<h2>StdX: Model &amp; Interpretation</h2>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a aria-hidden="true" tabindex="-1"></a>fit_stdx <span class="ot">&lt;-</span> <span class="fu">glmmTMB</span>(</span>
<span id="cb10-2"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">formula =</span> satisfaction <span class="sc">~</span> <span class="dv">1</span> <span class="sc">+</span> wait_b_z <span class="sc">+</span> wait_w_z <span class="sc">+</span> nurse_z <span class="sc">+</span> </span>
<span id="cb10-3"><a aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">+</span> wait_w_z <span class="sc">|</span> hospital), </span>
<span id="cb10-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> dat_stdx,</span>
<span id="cb10-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="at">REML =</span> <span class="cn">TRUE</span></span>
<span id="cb10-6"><a aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-7"><a aria-hidden="true" tabindex="-1"></a><span class="fu">model_parameters</span>(fit_stdx, <span class="at">effects =</span> <span class="st">"fixed"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># Fixed Effects

Parameter   | Coefficient |   SE |         95% CI |         z |      p
----------------------------------------------------------------------
(Intercept) |   -6.20e-17 | 0.11 | [-0.21,  0.21] | -5.90e-16 | &gt; .999
wait b z    |        0.02 | 0.11 | [-0.19,  0.23] |      0.18 | 0.860 
wait w z    |       -0.37 | 0.03 | [-0.43, -0.31] |    -11.90 | &lt; .001
nurse z     |        0.19 | 0.14 | [-0.08,  0.47] |      1.41 | 0.158 </code></pre>
</div>
</div>
<div class="fs80">
<ul>
<li>A one <em>SD</em> increase in a patient’s wait time (relative to their hospital’s average) significantly decreases their satisfaction by 0.37 <em>raw points</em>.</li>
</ul>
</div>
</section>
<section class="slide level2 fs80">
<h2>The Problem with Global StdYX</h2>
<p>If Y is an arbitrary scale, you might be tempted to standardize Y globally before fitting your model (like you would for OLS). <span class="b dark-red">Do not do this for multilevel data!</span></p>
<ul>
<li><strong>The ICC Penalty:</strong> If you standardize Y globally, the denominator includes both Level-1 and Level-2 variance.</li>
<li><strong>The Trap:</strong> A Level-1 predictor can only explain Level-1 variance. By dividing its effect by the <em>total</em> variance pool, you mathematically penalize it.</li>
<li><strong>The Result:</strong> If your model has high Level-2 variance (high ICC), your Level-1 StdYX effects will look artificially tiny.</li>
<li><strong>The Solution:</strong> We must use <span class="b blue">Level-Specific Standardization</span>.</li>
</ul>
</section>
<section class="slide level2">
<h2>Level-Specific StdYX</h2>
<div class="fs80">
<p>There is no automated R package for this (yet). We manually take the coefficients from our <strong>StdX model</strong> (where X is standardized but Y is raw) and divide them by the level-specific standard deviations of Y.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># 1. Calculate the standard deviation of the hospital means (Level 2 SD)</span></span>
<span id="cb12-2"><a aria-hidden="true" tabindex="-1"></a>sd_y_b <span class="ot">&lt;-</span> hospital <span class="sc">|&gt;</span> </span>
<span id="cb12-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">sat_b =</span> <span class="fu">mean</span>(satisfaction), <span class="at">.by =</span> hospital) <span class="sc">|&gt;</span> </span>
<span id="cb12-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(sat_b) <span class="sc">|&gt;</span> <span class="fu">sd</span>() <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7003727</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Calculate the standard deviation of the within-cluster scores (Level 1 SD)</span></span>
<span id="cb14-2"><a aria-hidden="true" tabindex="-1"></a>sd_y_w <span class="ot">&lt;-</span> hospital <span class="sc">|&gt;</span> </span>
<span id="cb14-3"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sat_b =</span> <span class="fu">mean</span>(satisfaction), <span class="at">.by =</span> hospital) <span class="sc">|&gt;</span> </span>
<span id="cb14-4"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">sat_w =</span> satisfaction <span class="sc">-</span> sat_b) <span class="sc">|&gt;</span> </span>
<span id="cb14-5"><a aria-hidden="true" tabindex="-1"></a>  <span class="fu">pull</span>(sat_w) <span class="sc">|&gt;</span> <span class="fu">sd</span>() <span class="sc">|&gt;</span> <span class="fu">print</span>()</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.7221508</code></pre>
</div>
</div>
</section>
<section class="slide level2">
<h2>Calculating &amp; Interpreting StdYX</h2>
<div class="fs80">
<p>We divide the slopes from our <code>fit_stdx</code> model by the matching SD of Y.</p>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># L2 StdYX Slope = (L2 StdX Slope) / (L2 SD of Y)</span></span>
<span id="cb16-2"><a aria-hidden="true" tabindex="-1"></a><span class="fl">0.19</span> <span class="sc">/</span> <span class="fl">0.700</span> <span class="co"># nurse_z</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.2714286</code></pre>
</div>
</div>
<div class="fs80">
<ul>
<li>A one <em>between-hospital</em> SD increase in nurse ratio was associated with a non-significant increase in satisfaction of 0.27 <em>between-hospital</em> SDs.</li>
</ul>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a aria-hidden="true" tabindex="-1"></a><span class="co"># L1 StdYX Slope = (L1 StdX Slope) / (L1 SD of Y)</span></span>
<span id="cb18-2"><a aria-hidden="true" tabindex="-1"></a><span class="sc">-</span><span class="fl">0.37</span> <span class="sc">/</span> <span class="fl">0.722</span> <span class="co"># wait_w_z</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -0.5124654</code></pre>
</div>
</div>
<div class="fs80">
<ul>
<li>A one <em>within-hospital</em> SD increase in wait time was associated with a significant decrease in satisfaction of 0.51 <em>within-hospital</em> SDs.</li>
</ul>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>The Reporting<br> Checklist</h1>

</section>
<section class="slide level2 fs80">
<h2>The Goal of Reporting</h2>
<ul>
<li>Multilevel modeling involves dozens of minor analytical decisions.</li>
<li>Centering, random effect structures, and estimation algorithms all drastically change your results.</li>
<li>Your goal in a manuscript is not just to report the p-values, but to provide enough transparent detail that another researcher could perfectly replicate your model from your raw data.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Introduction</h2>
<p>The justification for an MLM should begin before the Methods section.</p>
<p><strong>What to include:</strong></p>
<ul>
<li>Acknowledge the nested structure of your data in your hypotheses.</li>
<li>Clearly state the levels of analysis (e.g., L1 is patients, L2 is hospitals).</li>
<li>Distinguish between within-cluster and between-cluster hypotheses. Do not hypothesize a generic “effect of wait time” if you specifically mean “when a patient waits longer than their hospital’s average.”</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Methods (Data)</h2>
<p>The participants section must describe the sample sizes at all levels.</p>
<p><strong>What to include:</strong></p>
<ul>
<li>Total number of Level-1 observations (e.g., N = 2,000 patients).</li>
<li>Total number of Level-2 clusters (e.g., J = 40 hospitals).</li>
<li>The average cluster size, minimum cluster size, and maximum cluster size (e.g., an average of 50 patients per hospital, ranging from 12 to 89).</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Methods (Variables)</h2>
<p>You must explicitly state how every variable was handled.</p>
<p><strong>What to include:</strong></p>
<ul>
<li>Identify which variables were measured at Level-1 and Level-2.</li>
<li>Explicitly state your centering decisions. Did you grand-mean center? Did you group-mean center (cluster-mean center)?</li>
<li>State why you chose that centering method. Did you want to isolate the purely within-cluster effect, or were you aiming for a blended effect?</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Methods (Modeling)</h2>
<p>Clearly identify the mathematical tools you used.</p>
<p><strong>What to include:</strong></p>
<ul>
<li>Software and packages with version numbers (e.g., R version 4.3.1, glmmTMB version 1.1.8).</li>
<li>The estimation method used. Did you use Restricted Maximum Likelihood (REML) or standard Maximum Likelihood (ML)?</li>
<li>Mention the specific optimizer if you had to change it from the default to achieve convergence.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Methods (Structure)</h2>
<p>Explain how you built your equations.</p>
<p><strong>What to include:</strong></p>
<ul>
<li>Describe the random effects structure. Did you include random intercepts? Random slopes?</li>
<li>State whether you allowed the random intercepts and slopes to correlate.</li>
<li>If you had to simplify your random effects structure due to singular fits or convergence issues, document that process here. Explain what was dropped and why.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Methods (Reliability)</h2>
<p>You cannot simply present a correlation matrix for a multilevel dataset.</p>
<p><strong>What to include:</strong></p>
<ul>
<li>A table of means, standard deviations, and correlations for all Level-1 variables.</li>
<li>A completely separate table of descriptives and correlations for all Level-2 variables, calculated at the cluster level.</li>
<li>Evidence of reliability for your continuous predictors. Predictors measured with high error will bias your regression coefficients.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Methods (Missing Data)</h2>
<p>Missing data is especially dangerous in MLMs. Deleting one Level-2 cluster due to a missing covariate takes all of its Level-1 observations down with it.</p>
<p><strong>What to include:</strong></p>
<ul>
<li>The exact percentage of missing data reported separately for Level-1 variables and Level-2 variables.</li>
<li>The method used to handle missingness (e.g., Full Information Maximum Likelihood or Multiple Imputation).</li>
<li>If using listwise deletion, explicitly state the final analytical sample size and justify why deletion was acceptable.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Results (The Null Model)</h2>
<p>Always report the baseline before adding predictors.</p>
<p><strong>What to include:</strong></p>
<ul>
<li>Report the unconditional ICC from the null model.</li>
<li>Provide a plain language interpretation: “The ICC was 0.22, indicating that 22 percent of the variance in patient satisfaction is attributable to differences between hospitals.”</li>
<li>This justifies the need for multilevel modeling in the first place.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Results (Fixed Effects)</h2>
<p>Report the focal tests of your hypotheses.</p>
<p><strong>What to include:</strong></p>
<ul>
<li>The unstandardized coefficient estimate.</li>
<li>The 95% Confidence Interval for the estimate.</li>
<li>The standard error.</li>
<li>The exact p-value.</li>
<li>A plain language interpretation of the direction and magnitude of the effect.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Results (Random Effects)</h2>
<p>Do not ignore the random portion of the model.</p>
<p><strong>What to include:</strong></p>
<ul>
<li>The variance (or standard deviation) of the random intercepts.</li>
<li>The variance (or standard deviation) of any random slopes.</li>
<li>The correlation between random intercepts and random slopes.</li>
<li>The residual (Level-1) variance.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Results (Effect Sizes)</h2>
<p>Provide the big picture summary of model performance.</p>
<p><strong>What to include:</strong></p>
<ul>
<li>Report both the Marginal R2 and Conditional R2.</li>
<li>Cite Nakagawa &amp; Schielzeth (2013) to clarify your framework.</li>
<li>If comparing multiple models (e.g., a baseline model vs a full model), report the change in R2 (Delta R2) or use AIC/BIC to discuss relative model fit.</li>
<li>Clearly state whether you are reporting raw, StdX, or StdYX slopes.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Results (Model Building)</h2>
<p>Reviewers want to see the sequence of models you estimated.</p>
<p><strong>What to include:</strong></p>
<ul>
<li><strong>Step 1:</strong> The Null Model to establish baseline variance and the ICC.</li>
<li><strong>Step 2:</strong> The Random Coefficients Model containing only Level-1 predictors to see if those slopes vary significantly across clusters.</li>
<li><strong>Step 3:</strong> The Full Contextual Model containing Level-1 and Level-2 predictors, including any cross-level interactions.</li>
</ul>
</section>
<section class="slide level2 fs80">
<h2>IMRD: Discussion (Language)</h2>
<p>Multilevel modeling uses the word “effect” constantly (e.g., fixed effects, random effects). This can create a semantic trap.</p>
<p><strong>What to watch out for:</strong></p>
<ul>
<li>Do not let the statistical terminology bleed into causal claims in your discussion section.</li>
<li>Unless you have a rigorously controlled experimental design, your “fixed effects” are merely associations or predictions.</li>
<li>Carefully edit your conclusions to ensure you are not implying a causal mechanism that your design cannot support.</li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <script>

    document.addEventListener("DOMContentLoaded", function() {

      // 1. Re-classify stderr to warnings and messages and strip empty lines

      document.querySelectorAll('.cell-output-stderr').forEach(function(output) {

        // Strip invisible zero-width spaces Quarto sometimes inserts

        const text = output.textContent.replace(/[\u200B-\u200D\uFEFF]/g, '').trim();

    

        // Remove completely empty blocks to fix the gaps

        if (text === '') {

          output.remove();

          return;

        }

    

        if (output.textContent.includes('Warning:')) {

          output.classList.replace('cell-output-stderr', 'cell-output-warning');

        } else {

          output.classList.replace('cell-output-stderr', 'cell-output-message');

        }

      });

    

      // 2. Physically merge adjacent blocks into one seamless block

      ['.cell-output-message', '.cell-output-warning'].forEach(function(selector) {

        const elements = document.querySelectorAll(selector);

        elements.forEach(function(current) {

          if (!current.parentNode) return; // Skip if it was already merged and removed

    

          let next = current.nextElementSibling;

          while (next && next.classList.contains(selector.substring(1))) {

            let currentCode = current.querySelector('pre code');

            let nextCode = next.querySelector('pre code');

    

            if (currentCode && nextCode) {

               // Clean up formatting and append to the primary block

               let appendText = nextCode.innerHTML.replace(/^\n+|\n+$/g, '');

               if (appendText !== '') {

                 currentCode.innerHTML += '\n' + appendText;

               }

            }

    

            let toRemove = next;

            next = next.nextElementSibling;

            toRemove.remove();

          }

        });

      });

    });

    </script>

    

    <script>

      // htmlwidgets need to know to resize themselves when slides are shown/hidden.

      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current

      // slide changes (different for each slide format).

      (function () {

        // dispatch for htmlwidgets

        function fireSlideEnter() {

          const event = window.document.createEvent("Event");

          event.initEvent("slideenter", true, true);

          window.document.dispatchEvent(event);

        }

    

        function fireSlideChanged(previousSlide, currentSlide) {

          fireSlideEnter();

    

          // dispatch for shiny

          if (window.jQuery) {

            if (previousSlide) {

              window.jQuery(previousSlide).trigger("hidden");

            }

            if (currentSlide) {

              window.jQuery(currentSlide).trigger("shown");

            }

          }

        }

    

        // hookup for slidy

        if (window.w3c_slidy) {

          window.w3c_slidy.add_observer(function (slide_num) {

            // slide_num starts at position 1

            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);

          });

        }

    

      })();

    </script>

    

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp('/' + window.location.host + '/');
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>