---
title: "Week 14: Practical Matters"
---

<!-- Lecture a -->

## [14a] Effect Sizes and Reporting

### Topics
1. Effect Sizes
    + *Marginal vs. Conditional R²*
    + *StdX and StdYX Effects*
    
2. The Reporting Checklist
    + *Intro and Methods*
    + *Results and Discussion*

### File Downloads
- [hospital_sim.csv](../../data/hospital_sim.csv){download="hospital_sim.csv"}

### Readings
- [View on Canvas](https://canvas.ku.edu/courses/182539/pages/14a-effect-sizes-and-reporting){target="_blank"}

### Slides

```{=html}
<iframe class="slide-deck" src="a_Slides.html" title="[14a] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::


<!-- Lecture b -->

## [14b] Power Analysis

### Topics
1. The Power Problem in MLMs
    + *Why G\*Power isn't enough*
    + *The simulation solution*
    
2. The `simr` Workflow
    + *Building dummy models*
    + *Simulating and extending power*

### Readings
- [View on Canvas](https://canvas.ku.edu/courses/182539/pages/14b-power-analysis-+-lab?module_item_id=4317598){target="_blank"}

### Slides

```{=html}
<iframe class="slide-deck" src="b_Slides.html" title="[14b] Slideshow">
</iframe>
```

::: {.fsmaller}
\*Note that you can click the three-line (hamburger) icon on the bottom-left of the slides to access a navigation menu. You can click inside the slides region and press the left and right arrow keys on your keyboard to advance and reverse the slides and animations.
:::

<!-- Bottom Nav -->

```{=html}
<div style="display: flex; justify-content: space-between; margin-top: 3rem;">
  <a href="../13/index.html" class="btn btn-outline-primary" role="button">&laquo;&nbsp;&nbsp;Week 13</a>

  <a href="../15/index.html" class="btn btn-primary" role="button">Week 15&nbsp;&nbsp;&raquo;</a>
</div>
```
