{
  "hash": "2721fc9429122999d40906136ff49c1a",
  "result": {
    "engine": "knitr",
    "markdown": "---\nformat: \n  revealjs:\n    css: ../../styles.css\n    slide-number: true\n    show-slide-number: all\n    preview-links: false\n    progress: true\n    history: true\n    hash-type: number\n    theme: default\n    code-block-background: true\n    highlight-style: zenburn\n    code-link: false\n    code-copy: true\n    code-line-numbers: false\n    controls: true\n    pagetitle: \"Multilevel Modeling\"\n    author-meta: \"Jeffrey Girard\"\n    semester: \"Spring 2026\"\n    course: \"PSYC 894\"\n    lecture: \"02a\"\nexecute:\n  echo: true\n  eval: true\n  collapse: false\n  cache: false\n---\n\n::: {.my-title}\n# [Multilevel Modeling]{.blue}\nLinear Modeling Review (1/2)\n\n::: {.my-grey}\n[{{< meta semester >}} | CLAS | {{< meta course >}}]{}<br />\n[Jeffrey M. Girard | Lecture {{< meta lecture >}}]{}\n:::\n\n![](../../img/city-girl.svg){.absolute bottom=30 right=0 width=\"400\"}\n:::\n\n## Roadmap\n\n::: {.columns .pv4}\n\n::: {.column width=\"60%\"}\n1. Simple Regression\n  \n2. Multiple Regression\n\n3. Categorical Predictors\n:::\n\n::: {.column .tc .pv4 width=\"40%\"}\n{{< lif \"../../icons/map.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n\n:::\n\n# R Setup\n\n## Load Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# install.packages(c(\"easystats\", \"ggplot2\", \"marginaleffects\"))\nlibrary(easystats)\nlibrary(ggplot2)\nlibrary(marginaleffects)\n```\n:::\n\n\n:::{.fsmaller}\n#### Needs to be loaded\n- [easystats]{.b .blue} will provide most of our statistical functions\n- [ggplot2]{.b .blue} will provide the ability to customize our plots\n\n#### Needs to be installed\n- [marginaleffects]{.b .green} is called by easystats for estimation\n\n:::\n\n## Example Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata_codebook(penguins)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\npenguins (344 rows and 8 variables, 8 shown)\n\nID | Name        | Type        |  Missings |       Values |           N\n---+-------------+-------------+-----------+--------------+------------\n1  | species     | categorical |  0 (0.0%) |       Adelie | 152 (44.2%)\n   |             |             |           |    Chinstrap |  68 (19.8%)\n   |             |             |           |       Gentoo | 124 (36.0%)\n---+-------------+-------------+-----------+--------------+------------\n2  | island      | categorical |  0 (0.0%) |       Biscoe | 168 (48.8%)\n   |             |             |           |        Dream | 124 (36.0%)\n   |             |             |           |    Torgersen |  52 (15.1%)\n---+-------------+-------------+-----------+--------------+------------\n3  | bill_len    | numeric     |  2 (0.6%) | [32.1, 59.6] |         342\n---+-------------+-------------+-----------+--------------+------------\n4  | bill_dep    | numeric     |  2 (0.6%) | [13.1, 21.5] |         342\n---+-------------+-------------+-----------+--------------+------------\n5  | flipper_len | integer     |  2 (0.6%) |   [172, 231] |         342\n---+-------------+-------------+-----------+--------------+------------\n6  | body_mass   | integer     |  2 (0.6%) | [2700, 6300] |         342\n---+-------------+-------------+-----------+--------------+------------\n7  | sex         | categorical | 11 (3.2%) |       female | 165 (49.5%)\n   |             |             |           |         male | 168 (50.5%)\n---+-------------+-------------+-----------+--------------+------------\n8  | year        | integer     |  0 (0.0%) |         2007 | 110 (32.0%)\n   |             |             |           |         2008 | 114 (33.1%)\n   |             |             |           |         2009 | 120 (34.9%)\n-----------------------------------------------------------------------\n```\n\n\n:::\n:::\n\n\n::: {.fsmaller}\n*Note that this dataset is already included with recent versions of R.*\n:::\n\n# CSR\nContinuous Simple Regression\n\n## CSR Overview {.smaller}\n\n::: {.columns .pv4}\n::: {.column width=\"60%\"}\n-   [Simple regression]{.b .blue} predicts one variable $y$ from another variable $x$ using a straight line\n\n::: {.fragment .mt1}\n-   This line is defined by two parameters\n    -   The [intercept]{.b .green} is the value of $y$ when $x=0$\n    -   The [slope]{.b .green} is the change in $y$ expected for a change of 1 in $x$ (from $x=0$ to $x=1$)\n:::\n\n::: {.fragment .mt1}\n-   We will use `lm()` to fit regression models\n    -   This will solve using ordinary least squares\n    -   We need to give it the [data]{.b .green} and a [formula]{.b .green}\n:::\n:::\n\n::: {.column .tc .pv5 width=\"40%\"}\n{{< lif \"../../icons/scatter.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n:::\n\n## CSR Equation\n\n#### Generic\n\n$$y_i = \\beta_0 + \\beta_1 x_{i} + \\varepsilon_{i}$$\n\n#### Example\n\n$$\\text{MASS}_i = \\beta_0 + \\beta_1 \\text{FLEN}_{i} + \\varepsilon_i$$\n\n## CSR Formula\n\n#### Generic\n:::{.tc}\n`y ~ 1 + x`\n:::\n\n#### Example\n:::{.tc}\n`body_mass ~ 1 + flipper_len`\n:::\n\n## CSR Diagram {.nostretch}\n\n![](../../diagrams/simple_regression_full.png){width=\"75%\"}\n\n## CSR Estimation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncsr_f <- lm(\n  formula = body_mass ~ 1 + flipper_len,\n  data = penguins\n)\n```\n:::\n\n\n:::{.pv4}\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(csr_f)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter   | Coefficient |     SE |               95% CI | t(340) |      p\n---------------------------------------------------------------------------\n(Intercept) |    -5780.83 | 305.81 | [-6382.36, -5179.30] | -18.90 | < .001\nflipper len |       49.69 |   1.52 | [   46.70,    52.67] |  32.72 | < .001\n```\n\n\n:::\n:::\n\n\n:::\n\n## CSR Interpretation {.smaller}\n\n- **Intercept** $(\\beta_0 = -5780.8$, $p<.001)$<br />\nThe body mass (g) expected for a penguin with a flipper length of 0mm.<br />\n*This is biologically impossible, suggesting we should center our predictor.*\n\n- **Flipper Length Slope** $(\\beta_1 = 49.7$, $p<.001)$<br />\nThe expected change in body mass (g) for every 1mm increase in flipper length.\n\n- **Conclusion**<br />\nFlipper length is significantly and positively related to body mass.\n\n## CSR Centering\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_c <- center(penguins, select = \"flipper_len\")\ncsr_f_c <- lm(formula = body_mass ~ 1 + flipper_len, data = penguins_c)\n```\n:::\n\n\n:::{.pv4}\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_parameters(csr_f, csr_f_c, select = \"{estimate}{stars}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter    |       csr_f |    csr_f_c\n---------------------------------------\n(Intercept)  | -5780.83*** | 4201.75***\nflipper len  |    49.69*** |   49.69***\n---------------------------------------\nObservations |         342 |        342\n```\n\n\n:::\n:::\n\n:::{.fsmaller}\n**Note:** The slope $(\\beta_1)$ does not change. However, the intercept $(\\beta_0)$ is now the expected body mass for a penguin with ***average*** flipper length.\n:::\n:::\n\n## CSR Standardizing\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins_z <- standardize(penguins, select = c(\"body_mass\", \"flipper_len\"))\ncsr_f_z <- lm(formula = body_mass ~ 1 + flipper_len, data = penguins_z)\n```\n:::\n\n\n:::{.pv4}\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_parameters(csr_f, csr_f_z, select = \"{estimate}{stars}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter    |       csr_f |     csr_f_z\n----------------------------------------\n(Intercept)  | -5780.83*** |    1.02e-15\nflipper len  |    49.69*** |     0.87***\n----------------------------------------\nObservations |         342 |         342\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\n**Note:** The intercept is now zero. The slope is now the change in body mass in **Standard Deviations (SDs)** for a 1 SD increase in flipper length.\n:::\n:::\n\n## CSR Visualization\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\npred_csrf <- estimate_relation(\n  model = csr_f, \n  by = \"flipper_len\"\n)\nplot(pred_csrf)\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-9-1.png){width=576}\n:::\n:::\n\n\n## Plot Customization\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\n# Use the black-and-white theme and\n# use 30pt font for all future plots\ntheme_set(theme_bw(base_size = 30))\n\nplot(\n  pred_csrf, \n  show_data = TRUE,\n  point = list(color = \"salmon\"),\n  line = list(linewidth = 1.5)\n) +\nscale_y_continuous(\n  limits = c(2500, 6500)\n) +\nlabs(\n  x = \"Flipper length (mm)\", \n  y = \"Body mass (g)\"\n)\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-10-1.png){width=624}\n:::\n:::\n\n\n# CMR\nContinuous Multiple Regression\n\n## CMR Overview {.smaller}\n\n::: {.columns .pv4}\n::: {.column width=\"60%\"}\n-   We can include [multiple predictors]{.b .blue} to assess the [unique effect]{.b .green} of each predictor\n    -   This controls for the variance shared between predictors (collinearity)\n\n::: {.fragment .mt1}\n-   This changes the interpretation of slopes\n    -   **Simple Regression:** \"zero-order\" or Total Effect\n    -   **Multiple Regression:** \"partial\" or Unique Effect\n    \n:::\n::: {.fragment .mt1}\n-   Interpretation:\n    -   The partial effect of a predictor is the change in $y$ expected for a change of 1 in that predictor, **while holding all other predictors constant**\n:::\n:::\n\n::: {.column .tc .pv5 width=\"40%\"}\n{{< lif \"../../icons/venn.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n:::\n\n## CMR Equation\n\n#### Generic\n$$y_i = \\beta_0 + \\beta_1 x_{1i} + \\beta_2 x_{2i} + \\dots + \\varepsilon_{i}$$\n\n#### Example (with 2 predictors)\n$$\\text{MASS}_i = \\beta_0 + \\beta_1 \\text{FLEN}_{i} + \\beta_2 \\text{BDEP}_{i} + \\varepsilon_i$$\n\n## CMR Formula\n\n#### Generic\n:::{.tc}\n`y ~ 1 + x1 + x2 + ...`\n:::\n\n#### Example (with 2 predictors)\n:::{.tc}\n`body_mass ~ 1 + flipper_len + bill_dep`\n:::\n\n## CMR Diagram {.nostretch}\n![](../../diagrams/multiple_regression_full.png){width=\"70%\"}\n\n## CMR Estimation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncmr_fb <- lm(\n  formula = body_mass ~ 1 + flipper_len + bill_dep,\n  data = penguins\n)\n```\n:::\n\n\n:::{.pv4}\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(cmr_fb)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter   | Coefficient |     SE |               95% CI | t(339) |      p\n---------------------------------------------------------------------------\n(Intercept) |    -6541.91 | 540.75 | [-7605.56, -5478.26] | -12.10 | < .001\nflipper len |       51.54 |   1.87 | [   47.87,    55.21] |  27.64 | < .001\nbill dep    |       22.63 |  13.28 | [   -3.49,    48.76] |   1.70 | 0.089 \n```\n\n\n:::\n:::\n\n\n:::\n\n## CMR Interpretation {.smaller}\n\n- **Intercept** $(\\beta_0 = -6541.9$, $p<.001)$<br />\nThe body mass (g) expected when both Flipper Length and Bill Depth are 0mm.\n\n- **Flipper Length Partial Effect** $(\\beta_1 = 51.5$, $p<.001)$<br />\nThe expected change in body mass (g) for every 1mm increase in Flipper Length,<br />\n*holding Bill Depth constant*.\n\n- **Bill Depth Partial Effect** $(\\beta_2 = 22.6$, $p=.089)$<br />\nThe expected change in body mass (g) for every 1mm increase in Bill Depth,<br />\n*holding Flipper Length constant*.\n\n- **Conclusion**<br />\nFlipper length is uniquely predictive of Body Mass, whereas Bill Depth is not.\n\n## Comparing Estimates\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncsr_b <- lm(formula = body_mass ~ 1 + bill_dep, data = penguins)\n```\n:::\n\n\n:::{.pv4}\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_parameters(csr_f, csr_b, cmr_fb, select = \"{estimate}{stars}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter    |       csr_f |      csr_b |      cmr_fb\n-----------------------------------------------------\n(Intercept)  | -5780.83*** | 7488.65*** | -6541.91***\nflipper len  |    49.69*** |            |    51.54***\nbill dep     |             | -191.64*** |       22.63\n-----------------------------------------------------\nObservations |         342 |        342 |         342\n```\n\n\n:::\n:::\n\n\n:::\n\n:::{.fsmaller}\nNotice that Bill Depth was significant on its own (`csr_b`), but loses significance when Flipper Length is added (`cmr_fb`). This is because Flipper Length \"explains away\" the variance.\n:::\n\n## Comparing Plots 1\n\n:::{.columns}\n\n:::{.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npred_csrf <- estimate_relation(\n  model = csr_f, by = \"flipper_len\"\n)\nplot(pred_csrf)\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-15-1.png){width=960}\n:::\n:::\n\n:::\n\n:::{.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npred_cmrf <- estimate_relation(\n  model = cmr_fb, by = \"flipper_len\"\n)\nplot(pred_cmrf)\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n:::\n:::\n\n## Comparing Plots 2\n\n:::{.columns}\n\n:::{.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npred_csrb <- estimate_relation(\n  model = csr_b, by = \"bill_dep\"\n)\nplot(pred_csrb)\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n\n:::\n\n:::{.column width=\"50%\"}\n\n::: {.cell}\n\n```{.r .cell-code}\npred_cmrb <- estimate_relation(\n  model = cmr_fb, by = \"bill_dep\"\n)\nplot(pred_cmrb)\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-18-1.png){width=960}\n:::\n:::\n\n\n:::\n:::\n\n# DSR\nDiscrete Simple Regression\n\n## DSR Overview {.smaller}\n\n::: {.columns .pv4}\n::: {.column width=\"60%\"}\n-   To include a discrete predictor, the model will automatically use [dummy coding]{.b .blue}\n    -   This creates binary $(0/1)$ \"switches\"\n\n::: {.fragment .mt1}\n-   One group is chosen as the [Reference Group]{.b .green}\n    -   This group is represented by the *Intercept*\n    -   The slopes for other groups represent differences from the reference\n:::\n\n::: {.fragment .mt1}\n-   In R, simply include a [factor]{.b .green} in the formula\n    -   R treats the first level as the Reference group\n    -   You can create a factor if needed using `factor()`\n:::\n:::\n\n::: {.column .tc .pv5 width=\"40%\"}\n{{< lif \"../../icons/theater.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n:::\n\n## DSR Equation {.smaller}\n\n#### Generic\n$$y_i = \\beta_0 + \\beta_1 D_{1i} + \\dots + \\varepsilon_{i}$$\n\n#### Example (with 3 Groups)\n$$\\text{MASS}_i = \\beta_0 + \\beta_1 \\text{CHIN}_i + \\beta_2 \\text{GENT}_i + \\varepsilon_i$$\n\n## DSR Formula\n\n#### Generic\n:::{.tc}\n`y ~ 1 + f`\n:::\n\n#### Example (with 3 Groups)\n:::{.tc}\n`body_mass ~ 1 + species`\n:::\n\n\n## DSR Diagram {.nostretch}\n\n![](../../diagrams/categorical_regression_full3.png){width=\"70%\"}\n\n## DSR Data Prep\n\nThe `species` variable is already a factor!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(penguins$species)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   Adelie Chinstrap    Gentoo \n      152        68       124 \n```\n\n\n:::\n:::\n\n\n\nBut if it wasn't, we would need to convert it:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npenguins$species <- factor(penguins$species)\n```\n:::\n\n\n## DSR Estimation\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndsr_s <- lm(\n  formula = body_mass ~ 1 + species,\n  data = penguins\n)\n```\n:::\n\n\n:::{.pv4}\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(dsr_s)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter           | Coefficient |    SE |             95% CI | t(339) |      p\n--------------------------------------------------------------------------------\n(Intercept)         |     3700.66 | 37.62 | [3626.67, 3774.66] |  98.37 | < .001\nspecies [Chinstrap] |       32.43 | 67.51 | [-100.37,  165.22] |   0.48 | 0.631 \nspecies [Gentoo]    |     1375.35 | 56.15 | [1264.91, 1485.80] |  24.50 | < .001\n```\n\n\n:::\n:::\n\n\n:::\n\n## DSR Interpretation {.smaller}\n\n- **Intercept** $(\\beta_0 = 3700.7$, $p<.001)$<br />\nThe predicted body mass (g) for the Reference Group (Adelie).\n\n- **Species [Chinstrap] Total Effect** $(\\beta_1 = 32.4$, $p=.631)$<br />\nThe body mass difference between Chinstrap and Adelie.<br />\n*Result:* Not significant. Chinstraps are roughly the same size as Adelies.\n\n- **Species [Gentoo] Total Effect** $(\\beta_2 = 1375.4$, $p<.001)$<br />\nThe body mass difference between Gentoo and Adelie.<br />\n*Result:* Significant. Gentoos are much larger than Adelies.\n\n- **What's Missing?**<br />\nWe know how all groups compare to Adelie, but do Chinstraps differ from Gentoos?<br />\nStandard regression output doesn't tell us. We need contrasts...\n\n## DSR Pairwise Contrasts\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_contrasts(\n  model = dsr_s, \n  contrast = \"species\", \n  comparison = \"pairwise\", # compare pairs of groups\n  estimate = \"average\",\n  p_adjust = \"holm\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAveraged Contrasts Analysis\n\nLevel1    | Level2    | Difference |    SE |             95% CI | t(339) |      p\n---------------------------------------------------------------------------------\nChinstrap | Adelie    |      32.43 | 67.51 | [-100.37,  165.22] |   0.48 |  0.631\nGentoo    | Adelie    |    1375.35 | 56.15 | [1264.91, 1485.80] |  24.50 | < .001\nGentoo    | Chinstrap |    1342.93 | 69.86 | [1205.52, 1480.34] |  19.22 | < .001\n\nVariable predicted: body_mass\nPredictors contrasted: species\np-value adjustment method: Holm (1979)\n```\n\n\n:::\n:::\n\n\n## CSR Deviation Contrasts\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_contrasts(\n  model = dsr_s, \n  contrast = \"species\",\n  comparison = \"meandev\", # compare groups to mean of all\n  estimate = \"average\",\n  p_adjust = \"holm\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAveraged Contrasts Analysis\n\nLevel1    | Level2 | Difference |    SE |             95% CI | t(339) |      p\n------------------------------------------------------------------------------\nAdelie    | Mean   |    -469.26 | 34.22 | [-536.58, -401.94] | -13.71 | < .001\nChinstrap | Mean   |    -436.83 | 41.80 | [-519.05, -354.62] | -10.45 | < .001\nGentoo    | Mean   |     906.09 | 35.76 | [ 835.76,  976.43] |  25.34 | < .001\n\nVariable predicted: body_mass\nPredictors contrasted: species\np-value adjustment method: Holm (1979)\n```\n\n\n:::\n:::\n\n\n## DSR Means\n\n::: {.cell}\n\n```{.r .cell-code}\npred_dsrs <- estimate_means(dsr_s, by = \"species\")\npred_dsrs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated Marginal Means\n\nspecies   |    Mean |    SE |             95% CI | t(339)\n---------------------------------------------------------\nAdelie    | 3700.66 | 37.62 | [3626.67, 3774.66] |  98.37\nChinstrap | 3733.09 | 56.06 | [3622.82, 3843.36] |  66.59\nGentoo    | 5076.02 | 41.68 | [4994.03, 5158.00] | 121.78\n\nVariable predicted: body_mass\nPredictors modulated: species\n```\n\n\n:::\n:::\n\n\n\n## DSR Visualization\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nplot(pred_dsrs) +\n  labs(\n    x = \"Species\",\n    y = \"Body Mass (g)\"\n  )\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-26-1.png){width=624}\n:::\n:::\n\n\n# MMR\nMixed Multiple Regression\n\n## MMR Equation {.smaller}\n\n#### Generic\n$$y_i = \\beta_0 + \\beta_1 x_{1i} + \\dots +\\beta_2 D_{1i} + \\dots + \\varepsilon_{i}$$\n\n#### Example (with 1 continuous predictor and 3 groups)\n$$\\text{MASS}_i = \\beta_0 + \\beta_1 \\text{FLEN}_i + \\beta_2 \\text{CHIN}_i + \\beta_3 \\text{GENT}_i + \\varepsilon_i$$\n\n## MMR Formula\n\n#### Generic\n:::{.tc}\n`y ~ 1 + x1 + ... + f1 + ...`\n:::\n\n#### Example (with 1 continuous and 3 groups)\n:::{.tc}\n`body_mass ~ 1 + flipper_len + species`\n:::\n\n\n## MMR Diagram\n\n![](../../diagrams/complex_regression_full.png)\n\n## MMR Estimation\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmmr_fs <- lm(\n  formula = body_mass ~ 1 + flipper_len + species,\n  data = penguins\n)\n```\n:::\n\n\n:::{.pv4}\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(mmr_fs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter           | Coefficient |     SE |               95% CI | t(338) |      p\n-----------------------------------------------------------------------------------\n(Intercept)         |    -4031.48 | 584.15 | [-5180.51, -2882.45] |  -6.90 | < .001\nflipper len         |       40.71 |   3.07 | [   34.66,    46.75] |  13.25 | < .001\nspecies [Chinstrap] |     -206.51 |  57.73 | [ -320.07,   -92.95] |  -3.58 | < .001\nspecies [Gentoo]    |      266.81 |  95.26 | [   79.43,   454.19] |   2.80 | 0.005 \n```\n\n\n:::\n:::\n\n\n:::\n\n## MMR Slope Visualization\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\npred_mmrf <- estimate_relation(\n  model = mmr_fs, \n  by = \"flipper_len\", \n  estimate = \"average\"\n)\nplot(pred_mmrf) +\n  labs(\n    x = \"Flipper Length (mm)\", \n    y = \"Body Mass (g)\", \n    subtitle = \"Controlling for Species\"\n  )\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-29-1.png){width=960}\n:::\n:::\n\n\n## MMR Means\n\n\n::: {.cell}\n\n```{.r .cell-code}\npred_mmrs <- estimate_means(mmr_fs, by = \"species\", estimate = \"average\")\npred_mmrs\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAverage Predictions\n\nspecies   |    Mean |    SE |             95% CI | t(338)\n---------------------------------------------------------\nAdelie    | 3700.66 | 30.56 | [3640.55, 3760.78] | 121.09\nChinstrap | 3733.09 | 45.54 | [3643.51, 3822.67] |  81.97\nGentoo    | 5076.02 | 33.86 | [5009.41, 5142.62] | 149.91\n\nVariable predicted: body_mass\nPredictors modulated: species\n```\n\n\n:::\n:::\n\n\n## MMR Means Visualization\n\n\n::: {.cell output-location='column'}\n\n```{.r .cell-code}\nplot(pred_mmrs) +\n  labs(\n    x = \"Species\", \n    y = \"Body Mass (g)\", \n    subtitle = \"Controlling for Flipper Length\"\n  )\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-31-1.png){width=624}\n:::\n:::\n\n\n## MMR Pairwise Contrasts\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_contrasts(\n  model = mmr_fs,\n  contrast = \"species\",\n  comparison = \"pairwise\", # compare each group to each other group\n  estimate = \"average\",\n  p_adjust = \"holm\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAveraged Contrasts Analysis\n\nLevel1    | Level2    | Difference |    SE |             95% CI | t(338) |      p\n---------------------------------------------------------------------------------\nChinstrap | Adelie    |      32.43 | 54.84 | [ -75.45,  140.30] |   0.59 |  0.555\nGentoo    | Adelie    |    1375.35 | 45.61 | [1285.63, 1465.07] |  30.15 | < .001\nGentoo    | Chinstrap |    1342.93 | 56.75 | [1231.30, 1454.55] |  23.66 | < .001\n\nVariable predicted: body_mass\nPredictors contrasted: species\np-value adjustment method: Holm (1979)\n```\n\n\n:::\n:::\n\n\n## MMR Deviation Contrasts\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_contrasts(\n  model = mmr_fs,\n  contrast = \"species\",\n  comparison = \"meandev\", # compare each group to the mean of all groups\n  estimate = \"average\",\n  p_adjust = \"holm\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nAveraged Contrasts Analysis\n\nLevel1    | Level2 | Difference |    SE |             95% CI | t(338) |      p\n------------------------------------------------------------------------------\nAdelie    | Mean   |    -469.26 | 27.80 | [-523.95, -414.57] | -16.88 | < .001\nChinstrap | Mean   |    -436.83 | 33.95 | [-503.62, -370.05] | -12.87 | < .001\nGentoo    | Mean   |     906.09 | 29.05 | [ 848.96,  963.23] |  31.19 | < .001\n\nVariable predicted: body_mass\nPredictors contrasted: species\np-value adjustment method: Holm (1979)\n```\n\n\n:::\n:::\n\n\n",
    "supporting": [
      "a_Slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}