{
  "hash": "830417c43cf1814862d348f26fac5b45",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlecture: \"12a\"\nmetadata-files:\n  - ../../_slide-settings.yml\nformat:\n  revealjs:\n    theme: default\n---\n\n::: {.my-title}\n# [Multilevel Modeling]{.blue}\nCharacterizing Change\n\n::: {.my-grey}\n[{{< meta semester >}} | CLAS | {{< meta course >}}]{}<br />\n[Jeffrey M. Girard | Lecture {{< meta lecture >}}]{}\n:::\n\n![](../../img/city-girl.svg){.absolute bottom=30 right=0 width=\"400\"}\n:::\n\n\n::: {.cell}\n\n:::\n\n\n## Roadmap\n\n::: {.columns .pv4}\n\n::: {.column width=\"60%\"}\n1. Linear Trajectories\n    + *Structuring Time*\n    + *Growth Modeling*\n    \n2. Nonlinear Trajectories\n    + *Transforming Time*\n    + *Instantaneous Change*\n    \n:::\n\n::: {.column .tc .pv4 width=\"40%\"}\n{{< lif \"../../icons/map.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n\n:::\n\n# Linear Trajectories\n\n## Fluctuation vs. Growth\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-1-1.png){width=1056}\n:::\n:::\n\n\n## Modeling the Trajectory\n\n:::{.fsmaller}\n- In Week 11, we treated the baseline as stable. We were most interested in the observation-specific fluctuations around that baseline.\n- Moving forward with longitudinal change models, we are now most interested in the **shape of change** over the entire assessment period.\n- We want to know the *starting point*, the overall *trajectory*, and the overall *shape* (e.g., linear, quadratic, or logarithmic). \n- To capture this shape, we simply **add a time variable (or variables) to the model as a Level 1 predictor**. \n- Random intercepts will allow each participant to have their own starting point and random time slopes will allow each to have their own trajectory.\n:::\n\n## Centering Time\n\n:::{.fsmaller}\n- The **intercept** represents the expected outcome when all predictors equal zero. Therefore, we need to be mindful about what zero represents for *time*.\n- *If we study grades 9 through 12, then using the numbers `9` to `12` will result in an intercept corresponding to grade 0, which isn't very meaningful here.*\n\n:::{.fragment .mt1}\n- We usually [center]{.b .blue} time so that `0` and the intercept represent a meaningful starting point such as the first or baseline assessment in the study.\n- *We can re-code time (by subtracting 9) so that `0` and the intercept represent grade 9, and `1`, `2`, and `3` represent grades 10, 11, and 12, respectively.*\n:::\n:::\n\n## Scaling Time\n\n:::{.fsmaller}\n- The **slope** of a predictor represents the expected change in the outcome for a 1-unit increase in that predictor. Therefore, we need to be mindful about what a 1-unit increase actually represents for *time*.\n- *If a 10-year study records time in days (from `0` to `3650`), the slope will represent daily growth. This coefficient might be uninterpretable or confusingly small (e.g., a gain of 0.002).*\n\n:::{.fragment .mt1}\n- We usually [scale]{.b .blue} time so that `1` represents a meaningful, intuitive interval like \"one year\" or \"one academic semester\".\n- *We can re-code time (by dividing days by 365) so that `1` represents a full year. The slope now reflects a much more intuitive gain of 0.73 per year.*\n:::\n:::\n\n## Example Data\n\n\n::: {.cell replace_path='[\"../../data/\",\"\"]'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nvocab_raw <- read_csv(\"vocab_sim.csv\")\nglimpse(vocab_raw)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 900\nColumns: 5\n$ subject    <dbl> 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, …\n$ program    <chr> \"B\", \"B\", \"B\", \"B\", \"B\", \"B\", \"A\", \"A\", \"A\", \"A\", \"A\",…\n$ age_months <dbl> 120, 132, 144, 156, 168, 180, 120, 132, 144, 156, 168,…\n$ vocab      <dbl> 45.38913, 59.32121, 72.81737, 82.83264, 88.51938, 93.2…\n$ hours_read <dbl> 3.399861, 2.572877, 1.571513, 2.955250, 3.413900, 3.60…\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\nEach of 150 subjects was assessed for vocabulary size annually. Notice that our time variable is `age_months`, starting at 120 months (10 years old). \n:::\n\n## Preparing the Time Variable\n\n:::{.fsmaller}\nIf we use `age_months` as our predictor, our intercept will represent vocabulary at an age of 0 months, and our slope will represent month-to-month growth. We need to fix this!\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvocab <- vocab_raw |> \n  mutate(\n    # Center at 120 months (Baseline), then scale by 12 (Years)\n    time = (age_months - 120) / 12\n  ) |> \n  print(n = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 900 × 6\n  subject program age_months vocab hours_read  time\n    <dbl> <chr>        <dbl> <dbl>      <dbl> <dbl>\n1       1 B              120  45.4       3.40     0\n2       1 B              132  59.3       2.57     1\n3       1 B              144  72.8       1.57     2\n# ℹ 897 more rows\n```\n\n\n:::\n:::\n\n\n## Multilevel Equation (Linear)\n\n:::{.tc .b}\nLevel One (Observation)\n:::\n\n$$y_{ti} = \\beta_{0i} + \\beta_{1i} T_{ti} + \\color{#4daf4a}{e_{ti}}$$\n\n:::{.tc .b}\nLevel Two (Cluster)\n:::\n\n$$\\begin{align}\n\\beta_{0i} &= \\color{#377eb8}{\\gamma_{00}} + \\color{#e41a1c}{u_{0i}} \\\\\n\\beta_{1i} &= \\color{#377eb8}{\\gamma_{10}} + \\color{#e41a1c}{u_{1i}}\n\\end{align}$$\n\n:::{.fsmaller .mt4}\nNotice that time is the only predictor in the model. We are just defining the average starting point ($\\color{#377eb8}{\\gamma_{00}}$) and the average rate of linear change ($\\color{#377eb8}{\\gamma_{10}}$), along with how much different people vary around those averages.\n:::\n\n## Multilevel Equation Part 2 {.fsmaller}\n\n:::{.tc .b}\nLevel One (Observation)\n:::\n\n$$\n\\color{#4daf4a}{e_{ti}} \\sim \\text{Normal}(0, \\color{#4daf4a}{\\sigma})\n$$\n\n:::{.tc .b}\nLevel Two (Cluster)\n:::\n\n$$\n\\begin{bmatrix}\\color{#e41a1c}{u_{0i}}\\\\ \\color{#e41a1c}{u_{1i}}\\end{bmatrix} \\sim \\text{MVN}\\left(\\begin{bmatrix}0\\\\0\\end{bmatrix}, \\begin{bmatrix}\\color{#e41a1c}{\\tau_{00}} & \\\\ \\color{#e41a1c}{\\tau_{10}} & \\color{#e41a1c}{\\tau_{11}}\\end{bmatrix}\\right)\n$$\n\n:::{.mt4}\n- $\\color{#4daf4a}{\\sigma}$: The within-person spread around their own trajectory.\n- $\\color{#e41a1c}{\\tau_{00}}$: The between-person spread in starting points at baseline.\n- $\\color{#e41a1c}{\\tau_{11}}$: The between-person spread in the rate of growth over time.\n- $\\color{#e41a1c}{\\tau_{10}}$: The correlation between a person's starting point and rate of growth.\n:::\n\n## Path Diagram\n\n![](../../diagrams/longitudinal_change.png)\n\n## Formula\n\n:::{.fsmaller}\n$$y_{ti} = \\underbrace{\\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{10}} T_{ti}}_{\\text{Fixed}} + \\underbrace{\\color{#e41a1c}{u_{0i}} + \\color{#e41a1c}{u_{1i}} T_{ti}}_{\\text{(Random)}} + \\color{#4daf4a}{e_{ti}}$$\n\n**Generic**\n\n:::{.tc}\n`y ~ 1 + T + (1 + T | person)`\n\nwhere the [1 + T]{.blue} part is fixed<br>\nand the [(1 + T | person)]{.red} part is random\n:::\n\n:::{.fragment}\n**Example**\n\n:::{.tc}\n`vocab ~ 1 + time + (1 + time | subject)`\n:::\n:::\n:::\n\n## Fitting the Linear Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_linear <- glmmTMB(\n  formula = vocab ~ 1 + time + (1 + time | subject),\n  data = vocab\n)\n```\n:::\n\n\n:::{.fragment}\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(fit_linear, effects = \"fixed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Fixed Effects\n\nParameter   | Coefficient |   SE |         95% CI |     z |      p\n------------------------------------------------------------------\n(Intercept) |       53.33 | 0.56 | [52.23, 54.42] | 95.54 | < .001\ntime        |        8.06 | 0.24 | [ 7.59,  8.54] | 33.27 | < .001\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\n- `(Intercept)` ($\\gamma_{00}$): The average expected vocabulary score at Baseline.\n- `time` ($\\gamma_{10}$): The average expected annual change in vocabulary score.\n:::\n:::\n\n## Interpreting the Linear Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(fit_linear, effects = \"random\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Random Effects\n\nParameter                     | Coefficient | 95% CI\n----------------------------------------------------\nSD (Intercept: subject)       |        5.24 |       \nSD (time: subject)            |        2.59 |       \nCor (Intercept~time: subject) |        0.68 |       \nSD (Residual)                 |        6.06 |       \n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\n- `SD (Intercept)` ($\\tau_{00}$): The variation in starting scores among subjects.\n- `SD (time)` ($\\tau_{11}$): The variation in the rate of linear growth among subjects.\n- `Cor (Intercept~time)` ($\\tau_{10}$): A negative correlation suggests that those who start lower tend to grow faster.\n:::\n\n## Visualizing Fixed Effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the growth curve for the average subject\nestimate_relation(fit_linear, by = \"time\") |> plot()\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-7-1.png){width=960}\n:::\n:::\n\n\n## Visualizing Trajectories\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the growth curves for six randomly selected subjects\nestimate_relation(fit_linear, by = c(\"time\", \"subject=[sample 6]\")) |> plot()\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n## Linear Slopes\n\n:::{.fsmaller}\nIn a linear model, the growth rate stays constant over time. Here, vocab growth is always 8.06 per year with no acceleration or deceleration possible.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_slopes(fit_linear, trend = \"time\", by = \"time\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated Marginal Effects\n\ntime | Slope |   SE |       95% CI |     z |      p\n---------------------------------------------------\n0    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | < .001\n1    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | < .001\n2    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | < .001\n3    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | < .001\n4    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | < .001\n5    |  8.06 | 0.24 | [7.59, 8.54] | 33.27 | < .001\n\nMarginal effects estimated for time\nType of slope was dY/dX\n```\n\n\n:::\n:::\n\n\n\n# Nonlinear Trajectories\n\n## Beyond Linear Growth\n\n:::{.fsmaller}\n- Linear models assume a constant rate of change. They force a straight line through the data.\n- However, human behavior, learning, and biological processes rarely grow at exactly the same speed forever.\n- To allow our trajectories to bend and take on nonlinear shapes, we simply apply **mathematical transformations** to our time variable.\n- Instead of just predicting the outcome from raw Time, we can predict it from the Square of Time, the Logarithm of Time, the Exponentiation of Time, etc.\n:::\n\n## Visualizing the Shapes\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-10-1.png){width=1152}\n:::\n:::\n\n\n:::{.fsmaller}\n- **Quadratic:** acceleration, deceleration, or reversal (e.g., marital satisfaction)\n- **Logarithmic:** rapid early growth that plateaus (e.g., therapy response)\n- **Exponential:** slow early growth that compounds (e.g., viral outbreak)\n:::\n\n## Returning to Our Data\n\n:::{.fsmaller}\n- Let's apply this theory to our `vocab` dataset. We are modeling vocabulary growth in children from Baseline (Age 10) to Year 5 (Age 15).\n- Before we just test every math function in R, we should ask:<br>\n[*Which shapes make theoretical sense for this process?*]{.b .blue}\n\n:::{.fragment .mt4}\n- [Exponential:]{.b .dark-red} Unlikely. Human vocabulary does not compound toward infinity; there are natural cognitive and linguistic ceilings.\n- [Quadratic:]{.b .orange} Possible. Growth might be fast early on and then slow down significantly as they get older and possibly even reverse in old age.\n- [Logarithmic:]{.b .dark-green} Highly likely. Language acquisition often follows a rapid early learning phase that gradually plateaus as ceilings are approached.\n:::\n:::\n\n## Our Testing Plan\n\n:::{.fsmaller}\n- Based on our developmental theory, we will drop the Exponential model.\n- We will formally test a **Quadratic** model and a **Logarithmic** model against our standard **Linear** baseline to see which shape best fits the actual data.\n- Let's start by building the Quadratic model. We need to add a new predictor to our equation: **Time-Squared**.\n:::\n\n## Quadratic Equations\n\n:::{.tc .b}\nLevel One (Observation)\n:::\n\n$$y_{ti} = \\beta_{0i} + \\beta_{1i} T_{ti} + \\beta_{2i} T_{ti}^2 + \\color{#4daf4a}{e_{ti}}$$\n\n:::{.tc .b}\nLevel Two (Cluster)\n:::\n\n$$\\begin{align}\n\\beta_{0i} &= \\color{#377eb8}{\\gamma_{00}} + \\color{#e41a1c}{u_{0i}} \\\\\n\\beta_{1i} &= \\color{#377eb8}{\\gamma_{10}} + \\color{#e41a1c}{u_{1i}} \\\\\n\\beta_{2i} &= \\color{#377eb8}{\\gamma_{20}} + \\color{#e41a1c}{u_{2i}}\n\\end{align}$$\n\n## Orthogonal Polynomials\n\n- Using raw polynomials can introduce multicollinearity problems when $T$ and $T^2$ are highly correlated.\n\n:::{.fragment}\n- **The Solution:** We use [Orthogonal Polynomials]{.b .blue} via the `poly()` function to transform our time variable into fully uncorrelated linear and quadratic components.\n:::\n\n:::{.fragment}\n- **The Catch:** The components are centered and re-scaled,<br>so the coefficient values cannot be interpreted normally.\n:::\n\n## Quadratic Modeling\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_quad <- glmmTMB(\n  formula = vocab ~ 1 + poly(time, 2) + (1 + poly(time, 2) | subject),\n  data = vocab\n)\nmodel_parameters(fit_quad, effects = \"fixed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Fixed Effects\n\nParameter         | Coefficient |    SE |            95% CI |      z |      p\n-----------------------------------------------------------------------------\n(Intercept)       |       73.48 |  0.90 | [  71.71,  75.25] |  81.49 | < .001\ntime [1st degree] |      413.03 | 12.42 | [ 388.70, 437.37] |  33.27 | < .001\ntime [2nd degree] |     -107.38 |  4.65 | [-116.50, -98.26] | -23.08 | < .001\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller .fragment}\nThe intercept is the overall average vocabulary score across all time points (due to centering). The significant and positive 1st degree term indicates the overall average growth trend is increasing. The significant and negative 2nd degree term indicates the trajectory is curved downwards (growth is slowing).\n:::\n\n## Quadratic Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the growth curve for the average subject\nestimate_relation(fit_quad, by = \"time\") |> plot()\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-12-1.png){width=960}\n:::\n:::\n\n\n## Quadratic Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the growth curve for six randomly selected subjects\nestimate_relation(fit_quad, by = c(\"time\", \"subject=[sample 6]\")) |> plot()\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-13-1.png){width=960}\n:::\n:::\n\n\n## Quadratic Slopes\n\n:::{.fsmaller}\nIn a quadratic model, the growth rate is accelerating or decelerating by a fixed, constant amount per one-unit increase in time. Here, vocab growth is always decelerating by 2.87 per year (see the diff column).\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_slopes(fit_quad, trend = \"time\", by = \"time\") |>\n  mutate(diff = diff(c(NA, Slope)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntime | Slope |   SE |             CI |     z |      p |  diff\n-------------------------------------------------------------\n0    | 15.24 | 0.46 | [14.34, 16.13] | 33.42 | < .001 |      \n1    | 12.37 | 0.35 | [11.67, 13.06] | 34.97 | < .001 | -2.87\n2    |  9.50 | 0.27 | [ 8.97, 10.03] | 35.13 | < .001 | -2.87\n3    |  6.63 | 0.23 | [ 6.18,  7.07] | 29.04 | < .001 | -2.87\n4    |  3.76 | 0.25 | [ 3.27,  4.24] | 15.09 | < .001 | -2.87\n5    |  0.89 | 0.32 | [ 0.26,  1.52] |  2.77 |  0.006 | -2.87\n```\n\n\n:::\n:::\n\n\n## Logarithmic Equations\n\n:::{.tc .b}\nLevel One (Observation)\n:::\n\n$$y_{ti} = \\beta_{0i} + \\beta_{1i} \\log(T_{ti}+1) + \\color{#4daf4a}{e_{ti}}$$\n\n:::{.tc .b}\nLevel Two (Cluster)\n:::\n\n$$\\begin{align}\n\\beta_{0i} &= \\color{#377eb8}{\\gamma_{00}} + \\color{#e41a1c}{u_{0i}} \\\\\n\\beta_{1i} &= \\color{#377eb8}{\\gamma_{10}} + \\color{#e41a1c}{u_{1i}}\n\\end{align}$$\n\n::: {.aside}\n***Note:*** In R, `log()` defaults to the natural logarithm (base $e$). We add $+1$ to our time variable for two reasons. First, $\\log(0)$ is undefined. Second, $\\log(1)=0$, which ensures that our intercept still represents the expected outcome at $T=0$.\n:::\n\n## Logarithmic Modeling\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_log <- glmmTMB(\n  formula = vocab ~ 1 + log(time + 1) + (1 + log(time + 1) | subject),\n  data = vocab\n)\nmodel_parameters(fit_log, effects = \"fixed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Fixed Effects\n\nParameter      | Coefficient |   SE |         95% CI |     z |      p\n---------------------------------------------------------------------\n(Intercept)    |       47.62 | 0.54 | [46.55, 48.68] | 87.59 | < .001\ntime + 1 [log] |       23.59 | 0.69 | [22.24, 24.94] | 34.27 | < .001\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller .fragment}\nThe intercept represents the expected vocabulary score exactly at Baseline (Age 10). The significant and positive logarithmic term indicates that vocabulary size increases over time. This growth is modeled as fastest at the beginning and gradually slowing down over time.\n:::\n\n## Logarithmic Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the growth curve for the average subject\nestimate_relation(fit_log, by = \"time\") |> plot()\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-16-1.png){width=960}\n:::\n:::\n\n\n## Logarithmic Visualization\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot the growth curve for six randomly selected subjects\nestimate_relation(fit_log, by = c(\"time\", \"subject=[sample 6]\")) |> plot()\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-17-1.png){width=960}\n:::\n:::\n\n\n## Logarithmic Slopes\n\n:::{.fsmaller}\nIn a logarithmic model, the growth rate changes non-uniformly over time, following a pattern of diminishing returns. Here, vocab growth decelerates rapidly at first and then more gradually over time (see the diff column).\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_slopes(fit_log, trend = \"time\", by = \"time\") |>\n  mutate(diff = diff(c(NA, Slope)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ntime | Slope |   SE |             CI |     z |      p |   diff\n--------------------------------------------------------------\n0    | 23.59 | 0.69 | [22.24, 24.94] | 34.27 | < .001 |       \n1    | 11.79 | 0.34 | [11.12, 12.47] | 34.27 | < .001 | -11.79\n2    |  7.86 | 0.23 | [ 7.41,  8.31] | 34.27 | < .001 |  -3.93\n3    |  5.90 | 0.17 | [ 5.56,  6.23] | 34.27 | < .001 |  -1.97\n4    |  4.72 | 0.14 | [ 4.45,  4.99] | 34.25 | < .001 |  -1.18\n5    |  3.93 | 0.11 | [ 3.71,  4.16] | 34.27 | < .001 |  -0.79\n```\n\n\n:::\n:::\n\n\n\n## Model Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_performance(fit_linear, fit_quad, fit_log, metrics = c(\"AIC\", \"BIC\"))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Comparison of Model Performance Indices\n\nName       |   Model |  AIC (weights) |  BIC (weights)\n------------------------------------------------------\nfit_linear | glmmTMB | 6323.5 (<.001) | 6352.3 (<.001)\nfit_quad   | glmmTMB | 5860.0 (<.001) | 5908.0 (<.001)\nfit_log    | glmmTMB | 5793.0 (>.999) | 5821.8 (>.999)\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller .pv4}\nIn our simulated data, the Logarithmic change model has the lowest AIC and BIC, suggesting it provides the best fit for this specific process. Note as well that the weights for both metrics are overwhelmingly in favor of this model.\n:::\n\n## What about Autocorrelation?\n\n- In Fluctuation models, it was important to use the AR1 or EXP covariance structure because we had no other way to explain why \"today\" looked like \"yesterday\"\n\n- In Growth models, we have a systematic trend. We expect Year 2 to be related to Year 1 because they both sit on the same developmental path\n\n- Usually, once the shape of the growth is correctly specified, the remaining residuals are independent enough that we don't need the extra complexity of AR1 or EXP\n",
    "supporting": [
      "a_Slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}