{
  "hash": "149af82534437a8df2e75998a08c4abb",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlecture: \"10a\"\nmetadata-files:\n  - ../../_slide-settings.yml\nformat:\n  revealjs:\n    theme: default\n---\n\n::: {.my-title}\n# [Multilevel Modeling]{.blue}\nModel Comparison\n\n::: {.my-grey}\n[{{< meta semester >}} | CLAS | {{< meta course >}}]{}<br />\n[Jeffrey M. Girard | Lecture {{< meta lecture >}}]{}\n:::\n\n![](../../img/city-girl.svg){.absolute bottom=30 right=0 width=\"400\"}\n:::\n\n\n::: {.cell}\n\n:::\n\n\n## Roadmap\n\n::: {.columns .pv4}\n\n::: {.column width=\"60%\"}\n1. Model Comparison\n    + *Deviance and Nesting*\n    + *LRT and Information Criteria*\n  \n2. Modeling Approach\n    + *Simple to Complex*\n    + *Sequential Comparisons*\n    \n:::\n\n::: {.column .tc .pv4 width=\"40%\"}\n{{< lif \"../../icons/map.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n\n:::\n\n# Model Comparison\n\n## Deviance\n\nTo compare models, we need to quantify their fit to the data\n\nThe [deviance]{.b .blue} $(D)$ metric has some nice properties for this\n\n:::{.fragment}\nIt is a simple transformation of the model's likelihood $(\\mathcal{L})$\n\n$$D = -2\\ell=-2 \\log(\\mathcal{L})$$\n\n:::{.tc}\n[Lower deviance = Better fit]{.b .green}<br />\n(e.g., $1000$ is better than $1552$)<br />\n(e.g., $-52$ is better than $-30$)\n:::\n:::\n\n## Nesting\n\n::: {.fsmaller}\n- We can statistically compare *nested* models using their deviances\n\n:::{.fragment}\n- If two models are nested, that means a more specific model can be derived from a more general model by removing fixed effects\n    + ✅ Adding fixed slopes (nested)\n    + ✅ Adding random slopes (nested)\n    + ✅ Adding random intercepts (nested)\n    + ❌ Swapping predictors (not nested)\n    + ❌ Swapping clustering variables  (not nested)\n    + ❌❌ Swapping outcome variables (not comparable)\n\n:::\n:::\n\n## The Nesting Logic\n\n- **Definition**: Model A is nested in Model B if A is just B with some parts \"turned off\" (fixed at zero).\n- **Visualizing Nesting**: Think of Russian Dolls. A smaller model must fit entirely inside the larger one.\n- **The Rule**: You can add or remove terms, but you cannot swap them.\n    - ✅  <code>y ~ 1 + x</code> is nested in <code>y ~ 1 + x <span class=\"light-green b\">+ z</span></code>\n    - ❌  <code>y ~ 1 + x</code> is **not** nested in <code>y ~ 1 + <span class=\"light-red b\">z</span></code>\n\n## Nesting Examples {.f36}\n\n1. ✅ Adding a fixed slope\n    + <code>y ~ 1 + (1 | c)</code> to <code>y ~ 1 <span class=\"light-green b\">+ x</span> + (1 | c)</code>\n\n:::{.fragment}\n2. ✅ Adding a random slope\n    + <code>y ~ 1 + x + (1 | c)</code> to <code>y ~ 1 + x + (1 <span class=\"light-green b\">+ x</span> | c)</code>\n\n:::\n:::{.fragment}\n3. ✅ Adding random intercepts\n    + <code>y ~ 1 + x</code> to <code>y ~ 1 + x <span class=\"light-green b\">+ (1 | c)</span></code>\n\n:::\n\n## Non-Nesting Examples {.f36}\n\n4. ❌ Swapping predictors\n    + <code>y ~ 1 + x + (1 | c)</code> to <code>y ~ 1 + <span class=\"light-red b\">z</span> + (1 | c)</code>\n\n:::{.fragment}\n5. ❌ Swapping clustering variables\n    + <code>y ~ 1 + (1 | c)</code> to <code>y ~ 1 + (1 | <span class=\"light-red b\">g</span>)</code>\n\n:::\n:::{.fragment}\n6. ❌❌ Swapping outcome variables\n    + <code>y ~ 1 + (1 | c)</code> to <code><span class=\"light-red b\">q</span> ~ 1 + (1 | c)</code>\n\n:::\n\n## Likelihood Ratio Test\n\n- The LRT compares two nested models' deviances\n\n$$\\Delta D = D_{\\text{general}}-D_{\\text{specific}}$$ \n\n- It is a chi-squared test with degrees of freedom equal to the difference in the two models' number of parameters $(q)$\n\n$$\\Delta D \\sim \\chi^2(\\text{df}=q_{\\text{general}}-q_{\\text{specific}})$$\n\n\n## Likelihood Ratio Test {.f36}\n\n- Several important notes about the LRT\n    + It can only compare ***nested*** models\n    + The compared models should be fit with ML\n    + We can use `test_lrt(model1, model2, ...)`\n    \n:::{.fragment}\n- Interpreting the results\n    + A significant result means $\\Delta D \\neq 0$\n    + The model with *lower* deviance is better\n    + We can examine them with `get_deviance(model1)`\n    \n:::\n\n\n## Data Preparation\n\n\n::: {.cell replace_path='[\"../../data/\",\"\"]'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(glmmTMB)\nlibrary(easystats)\n\nheck2011 <- read_csv(\"heck2011.csv\", show_col_types = FALSE)\nglimpse(heck2011)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 6,871\nColumns: 7\n$ school  <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2,…\n$ student <dbl> 6701, 6702, 6703, 6704, 6705, 6706, 6707, 6708, 6709, 6710, 67…\n$ female  <dbl> 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ ses     <dbl> 0.586, 0.304, -0.544, -0.848, 0.001, -0.106, -0.330, -0.891, 0…\n$ math    <dbl> 47.1400, 63.6100, 57.7100, 53.9000, 58.0100, 59.8700, 62.5556,…\n$ puniv   <dbl> 0.08333333, 0.08333333, 0.08333333, 0.08333333, 0.08333333, 0.…\n$ public  <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n```\n\n\n:::\n:::\n\n\n## Why glmmTMB?\n\n- **Familiar Syntax**: It uses the same `formula`, `data`, and `REML` arguments as `lmer()` (defaults to REML = FALSE)\n- **Flexibility**: Unlike `lmer()`, it can fit models with no random effects, which will let us compare models with and without\n- **Better Convergence**: It is often more robust when models become complex (will be used a lot for troubleshooting)\n\n::: {.fragment .fsmaller .mt1}\n**Note**: GLMM stands for Generalized Linear Mixed Modeling, which is multilevel modeling for non-normal outcomes, and TMB stands for Template Model Builder, which is the underlying software that powers the package\n:::\n\n## Do we need a random intercept?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm0 <- glmmTMB(math ~ 1, heck2011)\nm1 <- glmmTMB(math ~ 1 + (1 | school), heck2011)\nc(m0 = get_deviance(m0), m1 = get_deviance(m1))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      m0       m1 \n49358.47 48875.75 \n```\n\n\n:::\n:::\n\n\n:::{.fragment}\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_lrt(m0, m1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName |   Model | df | df_diff |   Chi2 |      p\n-----------------------------------------------\nm0   | glmmTMB |  2 |         |        |       \nm1   | glmmTMB |  3 |       1 | 482.72 | < .001\n```\n\n\n:::\n:::\n\n\n::: {.fsmaller}\n- m1 has significantly better fit than m0, so we need the random intercept\n:::\n:::\n\n## Do we need a fixed slope?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm1 <- glmmTMB(math ~ 1 + (1 | school), heck2011)\nm2 <- glmmTMB(math ~ 1 + female + (1 | school), heck2011)\nc(m1 = get_deviance(m1), m2 = get_deviance(m2))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      m1       m2 \n48875.75 48840.55 \n```\n\n\n:::\n:::\n\n\n:::{.fragment}\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_lrt(m1, m2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName |   Model | df | df_diff |  Chi2 |      p\n----------------------------------------------\nm1   | glmmTMB |  3 |         |       |       \nm2   | glmmTMB |  4 |       1 | 35.20 | < .001\n```\n\n\n:::\n:::\n\n\n::: {.fsmaller}\n- m2 has significantly better fit than m1, so we need the fixed slope\n:::\n:::\n\n## Do we need a random slope?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm2 <- glmmTMB(math ~ 1 + female + (1 | school), heck2011)\nm3 <- glmmTMB(math ~ 1 + female + (1 + female | school), heck2011)\nc(m2 = get_deviance(m2), m3 = get_deviance(m3))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      m2       m3 \n48840.55 48835.32 \n```\n\n\n:::\n:::\n\n\n:::{.fragment}\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_lrt(m2, m3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName |   Model | df | df_diff | Chi2 |     p\n--------------------------------------------\nm2   | glmmTMB |  4 |         |      |      \nm3   | glmmTMB |  6 |       2 | 5.23 | 0.073\n```\n\n\n:::\n:::\n\n\n::: {.fsmaller}\n- m3 was not sig. better than m2, so we don't need the random slope\n:::\n:::\n\n\n## Trying Non-nested Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\nm4 <- glmmTMB(math ~ 1 + public + (1 | school), heck2011)\nm5 <- glmmTMB(math ~ 1 + puniv + (1 | school), heck2011)\n```\n:::\n\n\n:::{.fragment}\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_lrt(m4, m5)\n```\n\n::: {.cell-output .cell-output-error}\n\n```\nError:\n! The models are not nested, which is a prerequisite for\n  `test_likelihoodratio()`.\n  See the 'Details' section.\n  You may try `test_vuong()` instead.\n```\n\n\n:::\n:::\n\n\n:::\n\n\n## Information Criteria {.smaller}\n\n- We use \"information criteria\" to compare non-nested models\n    + They are only meaningful when the outcome is the same\n    + Lower is better but the comparisons are only relative\n    + $\\Delta\\text{IC}$: 0--2 = small, 2--10 = medium, 10+ = large difference\n\n$$\n\\text{AIC} = D + 2q \\quad\\quad\\quad\n\\text{BIC} = D + q \\log(n)\n$$\n\n- Two popular ICs are the Akaike (AIC) and Bayesian (BIC)\n    + Both metrics penalize the model for adding parameters $(q)$\n    + BIC is more \"conservative\" than AIC (i.e., adds a larger penalty)\n\n\n## IC for Non-nested Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_performance(\n  m4, # math ~ 1 + public + (1 | school)\n  m5, # math ~ 1 + puniv + (1 | school)\n  metrics = c(\"AIC\", \"BIC\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Comparison of Model Performance Indices\n\nName |   Model |   AIC (weights) |   BIC (weights)\n--------------------------------------------------\nm4   | glmmTMB | 48883.3 (<.001) | 48910.7 (<.001)\nm5   | glmmTMB | 48840.1 (>.999) | 48867.5 (>.999)\n```\n\n\n:::\n:::\n\n\n- Thus, *puniv* is a better predictor of *math* than *public* is\n\n- The probability that fit5 is better than fit4 is 99.9\\%\n\n## IC for Nested Models\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_performance(\n  m0, # math ~ 1\n  m1, # math ~ 1 + (1 | school)\n  m2, # math ~ 1 + female + (1 | school)\n  m3, # math ~ 1 + female + (1 + female | school)\n  metrics = c(\"AIC\", \"BIC\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Comparison of Model Performance Indices\n\nName |   Model |   AIC (weights) |   BIC (weights)\n--------------------------------------------------\nm0   | glmmTMB | 49362.5 (<.001) | 49376.1 (<.001)\nm1   | glmmTMB | 48881.8 (<.001) | 48902.3 (<.001)\nm2   | glmmTMB | 48848.6 (0.351) | 48875.9 (0.998)\nm3   | glmmTMB | 48847.3 (0.649) | 48888.3 (0.002)\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\n- AIC prefers the complex m3 (66.7\\%), BIC prefers the simpler m2 (99.8\\%)\n:::\n\n# Modeling Approach\n\n## Bottom-up Strategy\n\n::: {.fsmaller}\n- Start with the simplest model and build up, one step at a time\n\n- Test whether each step is a significant improvement\n\n1. Fit a null model (intercepts only)\n\n2. Add all L1 predictors (fixed slopes only)\n\n3. Add all L2 predictors (fixed slopes)\n\n4. Add L1 random slopes one at a time 🔄\n\n5. Add cross-level interactions one at a time 🔄\n:::\n\n## Example\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndat <-\n  heck2011 |> \n  degroup(select = \"ses\", by = \"school\") |>\n  mutate(female = factor(female), public = factor(public)) |> \n  standardize()\nglimpse(dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 6,871\nColumns: 9\n$ school      <dbl> -1.716289, -1.716289, -1.716289, -1.716289, -1.716289, -1.…\n$ student     <dbl> 1.6459713, 1.6464754, 1.6469796, 1.6474837, 1.6479878, 1.6…\n$ female      <fct> 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0…\n$ ses         <dbl> 0.70967156, 0.34849365, -0.73760160, -1.12695651, -0.03958…\n$ math        <dbl> -1.206047390, 0.668954645, -0.002721858, -0.436465498, 0.0…\n$ puniv       <dbl> -2.8981142, -2.8981142, -2.8981142, -2.8981142, -2.8981142…\n$ public      <fct> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0…\n$ ses_between <dbl> -0.605202, -0.605202, -0.605202, -0.605202, -0.605202, -0.…\n$ ses_within  <dbl> 1.409368976, 0.943297969, -0.458220520, -0.960651677, 0.44…\n```\n\n\n:::\n:::\n\n\n\n## Step 1\n\nFit null model and calculate unconditional ICC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep1 <- glmmTMB(\n  math ~ 1 + (1 | school),\n  data = dat,\n  REML = FALSE\n)\nicc(step1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Intraclass Correlation Coefficient\n\n    Adjusted ICC: 0.137\n  Unadjusted ICC: 0.137\n```\n\n\n:::\n:::\n\n\n:::{.fragment}\n- 14\\% of math score variance is between schools\n:::\n\n## Step 2\n\nAdd fixed slopes for all L1 predictors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep2 <- glmmTMB(\n  math ~ 1 + female + ses_within + (1 | school),\n  data = dat,\n  REML = FALSE\n)\ntest_lrt(step1, step2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName  |   Model | df | df_diff |   Chi2 |      p\n------------------------------------------------\nstep1 | glmmTMB |  3 |         |        |       \nstep2 | glmmTMB |  5 |       2 | 426.98 | < .001\n```\n\n\n:::\n:::\n\n\n:::{.fragment}\n- Including the L1 predictors is helpful\n:::\n\n## Step 3\n\nAdd fixed slopes for all L2 predictors\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep3 <- glmmTMB(\n  math ~ 1 + female + ses_within + \n    ses_between + public + puniv + (1 | school),\n  data = dat,\n  REML = FALSE\n)\ntest_lrt(step2, step3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName  |   Model | df | df_diff |   Chi2 |      p\n------------------------------------------------\nstep2 | glmmTMB |  5 |         |        |       \nstep3 | glmmTMB |  8 |       3 | 354.67 | < .001\n```\n\n\n:::\n:::\n\n\n:::{.fragment}\n- Including the L2 predictors is helpful\n:::\n\n## Step 4a\n\nAdd first random slope (for female)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep4a <- glmmTMB(\n  math ~ 1 + female + ses_within + \n    ses_between + public + puniv + (1 + female | school),\n  data = dat,\n  REML = FALSE\n)\ntest_lrt(step3, step4a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName   |   Model | df | df_diff | Chi2 |     p\n----------------------------------------------\nstep3  | glmmTMB |  8 |         |      |      \nstep4a | glmmTMB | 10 |       2 | 4.48 | 0.106\n```\n\n\n:::\n:::\n\n\n:::{.fragment}\n- Making the female slope random is not helpful\n:::\n\n## Step 4b\n\nAdd second random slope (for ses_within)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep4b <- glmmTMB(\n  math ~ 1 + female + ses_within + \n    ses_between + public + puniv + (1 + ses_within | school),\n  data = dat,\n  REML = FALSE\n)\ntest_lrt(step3, step4b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName   |   Model | df | df_diff |  Chi2 |     p\n-----------------------------------------------\nstep3  | glmmTMB |  8 |         |       |      \nstep4b | glmmTMB | 10 |       2 | 10.79 | 0.005\n```\n\n\n:::\n:::\n\n\n:::{.fragment}\n- Making the ses_within slope random is helpful\n:::\n\n## Step 5a\n\nAdd the cross-level interaction of ses_within and public\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep5a <- glmmTMB(\n  math ~ 1 + female + ses_within * public +\n    ses_between + public + puniv + \n    (1 + ses_within | school),\n  data = dat,\n  REML = FALSE\n)\ntest_lrt(step4b, step5a)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName   |   Model | df | df_diff | Chi2 |     p\n----------------------------------------------\nstep4b | glmmTMB | 10 |         |      |      \nstep5a | glmmTMB | 11 |       1 | 2.78 | 0.095\n```\n\n\n:::\n:::\n\n\n:::{.fragment}\n- Including this interaction may not be necessary\n:::\n\n## Step 5b\n\nAdd the cross-level interaction of ses_within and puniv\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstep5b <- glmmTMB(\n  math ~ 1 + female + ses_within * puniv +\n    ses_between + public + puniv + \n    (1 + ses_within | school),\n  data = dat,\n  REML = FALSE\n)\ntest_lrt(step4b, step5b)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName   |   Model | df | df_diff | Chi2 |     p\n----------------------------------------------\nstep4b | glmmTMB | 10 |         |      |      \nstep5b | glmmTMB | 11 |       1 | 0.56 | 0.456\n```\n\n\n:::\n:::\n\n\n:::{.fragment}\n- Including this interaction is not helpful\n:::\n\n## Summary of LRT Results\n\n![](../../img/model_flow.svg)\n\n::: {.fsmaller}\n- LRT favors the model from Step 4b, so I would usually choose that\n- Or, if testing an SES interaction was my goal, I would use 5a or 5b\n:::\n\n## Final Model (According to LRT)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmodel_parameters(step4b, effects = \"fixed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Fixed Effects\n\nParameter   | Coefficient |   SE |         95% CI |     z |      p\n------------------------------------------------------------------\n(Intercept) |        0.08 | 0.03 | [ 0.02,  0.14] |  2.81 | 0.005 \nfemale [1]  |       -0.12 | 0.02 | [-0.16, -0.08] | -5.39 | < .001\nses within  |        0.22 | 0.01 | [ 0.20,  0.24] | 18.89 | < .001\nses between |        0.31 | 0.01 | [ 0.29,  0.34] | 21.54 | < .001\npublic [1]  |       -0.03 | 0.03 | [-0.09,  0.03] | -0.92 | 0.357 \npuniv       |        0.05 | 0.01 | [ 0.02,  0.07] |  3.19 | 0.001 \n```\n\n\n:::\n:::\n\n\n## IC Model Comparison\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_performance(\n  step1, step2, step3, step4a, \n  step4b, step5a, step5b,\n  metrics = c(\"AIC\", \"BIC\")\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Comparison of Model Performance Indices\n\nName   |   Model |   AIC (weights) |   BIC (weights)\n----------------------------------------------------\nstep1  | glmmTMB | 19021.3 (<.001) | 19041.8 (<.001)\nstep2  | glmmTMB | 18598.4 (<.001) | 18632.5 (<.001)\nstep3  | glmmTMB | 18249.7 (0.011) | 18304.4 (0.966)\nstep4a | glmmTMB | 18249.2 (0.014) | 18317.6 (0.001)\nstep4b | glmmTMB | 18242.9 (0.329) | 18311.3 (0.031)\nstep5a | glmmTMB | 18242.1 (0.486) | 18317.3 (0.001)\nstep5b | glmmTMB | 18244.3 (0.160) | 18319.5 (<.001)\n```\n\n\n:::\n:::\n\n\n::: {.fsmaller}\n- So AIC prefers the complex Model 5a and BIC prefers the simpler Model 3\n:::\n\n## Which Metric Should I Trust? {.smaller}\n\nWhen AIC, BIC, and LRT disagree, consider your research goal:\n\n1. **LRT**: Best for testing a specific \"yes/no\" hypothesis about a parameter\n2. **AIC**: Best if you want the most accurate prediction (favors complexity)\n3. **BIC**: Best for building simple, clean theory (favors parsimony)\n\n::: {.callout-tip}\nIf BIC prefers the simpler model and AIC prefers the complex one, the \"extra\" effects are likely very small\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}