{
  "hash": "c1a6f5c5676b4368c8e053c85f82bb8d",
  "result": {
    "engine": "knitr",
    "markdown": "---\nlecture: \"11a\"\nmetadata-files:\n  - ../../_slide-settings.yml\nformat:\n  revealjs:\n    theme: default\n---\n\n::: {.my-title}\n# [Multilevel Modeling]{.blue}\nRepeated Measures\n\n::: {.my-grey}\n[{{< meta semester >}} | CLAS | {{< meta course >}}]{}<br />\n[Jeffrey M. Girard | Lecture {{< meta lecture >}}]{}\n:::\n\n![](../../img/city-girl.svg){.absolute bottom=30 right=0 width=\"400\"}\n:::\n\n\n::: {.cell}\n\n:::\n\n\n## Roadmap\n\n::: {.columns .pv4}\n\n::: {.column width=\"60%\"}\n1. Within-Person Variance\n    + *Trial-level Analysis*\n    + *Task-by-Person Effects*\n  \n2. The Structure of Error\n    + *Autocorrelation Tests*\n    + *Drift vs. White Noise*\n    \n:::\n\n::: {.column .tc .pv4 width=\"40%\"}\n{{< lif \"../../icons/map.json\" trigger=hover colors=secondary:#2a76dd class=rc >}}\n:::\n\n:::\n\n# Repeated Measures\n\n## Overview\n\n- Repeated measures designs are ubiquitous in social science\n    + e.g., completing multiple trials of a task\n    + e.g., responding to within-person experimental conditions\n    + e.g., answering daily diary surveys\n    \n:::{.fragment}\n- These are perfect applications for multilevel modeling\n    + Instead of individuals (L1) within larger units (L2)...\n    + ...we have observations (L1) within individuals (L2)\n\n:::\n\n## The Base Example\n\n**Main Variables**\n\n- Outcomes = `performance` (numeric score on a trial)\n- L2 Predictor = `icontrol` (trait inhibitory control)\n\n**Research Question**\n\n- Does a person's trait *inhibitory control* predict their average *intellectual performance* across multiple trials?\n\n## Example Data\n\n\n::: {.cell replace_path='[\"../../data/\",\"\"]'}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(glmmTMB)\nlibrary(easystats)\n\nintell <- read_csv(\"intell_sim.csv\")\nglimpse(intell)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 1,800\nColumns: 5\n$ subject     <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2…\n$ icontrol    <dbl> -0.0848893, -0.0848893, -0.0848893, -0.0848893, -0.0848893…\n$ trial       <dbl> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 1, 2, 3, 4, 5, 6, 7…\n$ task        <chr> \"Perceptual Reasoning\", \"Processing Speed\", \"Working Memor…\n$ performance <dbl> 17.997978, 14.412448, 22.439953, 17.173733, 21.686384, 14.…\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\nEach of 150 (fake) subjects completed 12 experimental trials.\n:::\n\n## The Aggregation Approach\n\n:::{.fsmaller}\nHistorically, researchers would simply average the L1 observations to create a single L2 score for each person, then run a standard linear regression.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Collapse L1 to L2\nintell_avg <- \n  intell |> \n  summarize(\n    .by = subject,\n    icontrol = first(icontrol),\n    perf_avg = mean(performance, na.rm = TRUE)\n  )\n# Fit single-level model\nfit_avg <- lm(perf_avg ~ icontrol, data = intell_avg)\nmodel_parameters(fit_avg)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter   | Coefficient |   SE |         95% CI | t(148) |      p\n-------------------------------------------------------------------\n(Intercept) |       11.05 | 0.48 | [10.10, 12.00] |  22.97 | < .001\nicontrol    |        5.47 | 0.49 | [ 4.49,  6.44] |  11.09 | < .001\n```\n\n\n:::\n:::\n\n\n## Why Multilevel is Better\n\n:::{.fsmaller}\n- **Information Loss:** Averaging collapses all L1 variance into a single point.\n    + We lose the ability to analyze within-person fluctuation or add L1 predictors.\n- **Unbalanced Data:** If some subjects have missing trials, simple aggregation ignores the sample size differences.\n    + A mean based on 2 trials is treated exactly the same as a mean based on 10 trials.\n- **Reliability Weighting:** MLM uses partial pooling (shrinkage).\n    + Estimates for subjects with fewer or more variable observations are mathematically pulled closer to the group average to prevent overfitting.\n\n:::\n\n## Multilevel Equation\n\n:::{.tc .b}\nLevel One (Observation)\n:::\n\n$$\n\\begin{align}\ny_{ti} &= \\beta_{0i} + \\color{#4daf4a}{e_{ti}} \\\\\n\\color{#4daf4a}{e_{ti}} &\\sim \\text{Normal}(0, \\color{#4daf4a}{\\sigma})\n\\end{align}\n$$\n\n:::{.tc .b}\nLevel Two (Cluster)\n:::\n\n$$\n\\begin{align}\n\\beta_{0i} &= \\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} z_{i} +  \\color{#e41a1c}{u_{0i}} \\\\\n\\color{#e41a1c}{u_{0i}} &\\sim \\text{Normal}(0, \\color{#e41a1c}{\\tau_{00}})\n\\end{align}\n$$\n\n:::{.fsmaller}\nNote that we have changed from $i$ within $j$ to $t$ within $i$\n:::\n\n## Path Diagram\n![](../../diagrams/repeated_measures.png)\n\n\n\n## Mixed (or Reduced) Equation\n\n$$\n\\begin{alignat}{2}\n&\\text{L1:} \\quad & y_{ti} &= \\beta_{0i} + \\color{#4daf4a}{e_{ti}} \\\\\n&\\text{L2:} \\quad & \\beta_{0i} &= \\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} z_i + \\color{#e41a1c}{u_{0i}} \\\\\n\\end{alignat}\n$$\n\nSubstitute the L2 equations directly into the L1 equation:\n\n$$\ny_{ti} = (\\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} z_i + \\color{#e41a1c}{u_{0i}}) + \\color{#4daf4a}{e_{ti}}\n$$\n\n:::{.fragment}\nRearrange to group the fixed and random parts:\n\n$$\ny_{ti} = \\underbrace{\\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} z_i}_{\\text{Fixed}} + \\underbrace{\\color{#e41a1c}{u_{0i}}}_{\\text{Random}} + \\color{#4daf4a}{e_{ti}}\n$$\n:::\n\n## Formula\n\n$$\ny_{ti} = \\underbrace{\\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} z_i}_{\\text{Fixed}} + \\underbrace{\\color{#e41a1c}{u_{0i}}}_{\\text{(Random)}} + \\color{#4daf4a}{e_{ti}}\n$$\n\n**Generic**\n\n:::{.tc}\n`y ~ 1 + z + (1 | cluster)`\n\nwhere the [1 + z]{.blue} part is fixed<br>\nand the [(1 | cluster)]{.red} part is random\n:::\n\n:::{.fragment}\n**Example**\n\n:::{.tc}\n`performance ~ 1 + icontrol + (1 | subject)`\n:::\n:::\n\n## Fitting the Model\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_mlm <- glmmTMB(\n  formula = performance ~ 1 + icontrol + (1 | subject),\n  data = intell\n)\nmodel_parameters(fit_mlm, effects = \"all\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Fixed Effects\n\nParameter   | Coefficient |   SE |         95% CI |     z |      p\n------------------------------------------------------------------\n(Intercept) |       11.05 | 0.48 | [10.11, 11.98] | 23.13 | < .001\nicontrol    |        5.47 | 0.49 | [ 4.51,  6.43] | 11.16 | < .001\n\n# Random Effects\n\nParameter               | Coefficient\n-------------------------------------\nSD (Intercept: subject) |        5.66\nSD (Residual)           |        4.71\n```\n\n\n:::\n:::\n\n\n## Visualizing the Results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_relation(fit_mlm, by = \"icontrol\") |> plot() + labs(y = \"performance\")\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-4-1.png){width=960}\n:::\n:::\n\n\n\n## Interpreting the Model\n\n:::{.fsmaller}\n**Fixed Effects (The Average Trend)**\n\n- `(Intercept)` ($\\gamma_{00}$): The expected performance on a trial for a subject with an inhibitory control score of 0.\n- `icontrol` ($\\gamma_{01}$): The expected difference in average performance between subjects who differ by 1 unit in inhibitory control.\n\n:::{.fragment}\n**Random Effects (The Variance)**\n\n- `SD (Intercept)` ($\\tau_{00}$): The standard deviation of the true person-specific means around the overall regression line (L2 variance).\n- `SD (Residual)` ($\\sigma$): The standard deviation of the individual trials around the person-specific means (L1 variance).\n:::\n:::\n\n## Unconditional ICC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit0 <- glmmTMB(performance ~ 1 + (1 | subject), data = intell)\nicc(fit0)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Intraclass Correlation Coefficient\n\n    Adjusted ICC: 0.731\n  Unadjusted ICC: 0.731\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller .mt4}\nThe ICC tells us the proportion of total variance in performance that is attributable to stable differences between people. The remaining variance (1&nbsp;&minus;&nbsp;ICC) is the within-person variability across trials.\n:::\n\n# Adding L1 Predictors\n\n## The \"Many Tasks\" Example\n\n:::{.fsmaller}\nWe can expand our model by adding predictors at Level 1. What if those repeated trials actually came from four different experimental tasks?\n\n**Updated Variables**\n\n- Outcomes = `performance` (numeric)\n- L1 Predictors = `task` (factor with 4 levels)\n- L2 Predictors = `icontrol` (numeric)\n\n**Research Question**\n\n- Some theories say inhibitory control increases all aspects of intellectual performance, while others say it only improves working memory.\n:::\n\n## Multilevel Equation Part 1\n\n:::{.tc .b}\nLevel One (Observation)\n:::\n\n$$y_{ti} = \\beta_{0i} + \\beta_{1i} \\text{TASK2}_{ti} + \\beta_{2i} \\text{TASK3}_{ti} + \\beta_{3i} \\text{TASK4}_{ti} + \\color{#4daf4a}{e_{ti}}$$\n\n:::{.tc .b}\nLevel Two (Cluster)\n:::\n\n$$\\begin{align}\n\\beta_{0i} &= \\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} \\text{ICTL}_{i} +  \\color{#e41a1c}{u_{0i}} \\\\\n\\beta_{1i} &= \\color{#377eb8}{\\gamma_{10}} + \\color{#377eb8}{\\gamma_{11}} \\text{ICTL}_{i} +  \\color{#e41a1c}{u_{1i}} \\\\\n\\beta_{2i} &= \\color{#377eb8}{\\gamma_{20}} + \\color{#377eb8}{\\gamma_{21}} \\text{ICTL}_{i} +  \\color{#e41a1c}{u_{2i}} \\\\\n\\beta_{3i} &= \\color{#377eb8}{\\gamma_{30}} + \\color{#377eb8}{\\gamma_{31}} \\text{ICTL}_{i} +  \\color{#e41a1c}{u_{3i}} \\\\\n\\end{align}$$\n\n## Multilevel Equation Part 2\n\n:::{.tc .b}\nLevel One (Observation)\n:::\n\n$$\n\\color{#4daf4a}{e_{ti}} \\sim \\text{Normal}(0, \\color{#4daf4a}{\\sigma})\n$$\n\n:::{.tc .b}\nLevel Two (Cluster)\n:::\n\n$$\\begin{bmatrix}\n\\color{#e41a1c}{u_{0i}}\\\\ \n\\color{#e41a1c}{u_{1i}}\\\\ \n\\color{#e41a1c}{u_{2i}}\\\\ \n\\color{#e41a1c}{u_{3i}}\n\\end{bmatrix} \n\\sim \\text{MVN}\\left(\n\\begin{bmatrix}\n0\\\\\n0\\\\\n0\\\\\n0\n\\end{bmatrix}, \n\\begin{bmatrix}\n\\color{#e41a1c}{\\tau_{00}} & & & \\\\ \n\\color{#e41a1c}{\\tau_{10}} & \\color{#e41a1c}{\\tau_{11}} & & \\\\\n\\color{#e41a1c}{\\tau_{20}} & \\color{#e41a1c}{\\tau_{21}} & \\color{#e41a1c}{\\tau_{22}} & \\\\\n\\color{#e41a1c}{\\tau_{30}} & \\color{#e41a1c}{\\tau_{31}} & \\color{#e41a1c}{\\tau_{32}} & \\color{#e41a1c}{\\tau_{33}}\n\\end{bmatrix}\n\\right)$$\n\n## Path Diagram\n\n![](../../diagrams/repeated_measures2.png)\n\n## Mixed (or Reduced) Equation {.smaller}\n\nSubstitute the L2 equations directly into the L1 equation:\n\n$$\\begin{align}\ny_{ti} &= (\\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}} \\text{ICTL}_{i} +  \\color{#e41a1c}{u_{0i}}) \\\\\n&\\quad + (\\color{#377eb8}{\\gamma_{10}} + \\color{#377eb8}{\\gamma_{11}} \\text{ICTL}_{i} +  \\color{#e41a1c}{u_{1i}})\\text{TASK2}_{ti} \\\\\n&\\quad + (\\color{#377eb8}{\\gamma_{20}} + \\color{#377eb8}{\\gamma_{21}} \\text{ICTL}_{i} +  \\color{#e41a1c}{u_{2i}})\\text{TASK3}_{ti} \\\\\n&\\quad + (\\color{#377eb8}{\\gamma_{30}} + \\color{#377eb8}{\\gamma_{31}} \\text{ICTL}_{i} +  \\color{#e41a1c}{u_{3i}})\\text{TASK4}_{ti} + \\color{#4daf4a}{e_{ti}}\n\\end{align}$$\n\n:::{.fragment}\nRearrange to group the fixed and random parts:\n\n$$\\begin{align}\ny_{ti} &= \\underbrace{\\color{#377eb8}{\\gamma_{00}} + \\color{#377eb8}{\\gamma_{01}}\\text{ICTL}_{i} + \\color{#377eb8}{\\gamma_{10}}\\text{TASK2}_{ti} + \\dots + \\color{#377eb8}{\\gamma_{31}}\\text{ICTL}_{i}\\text{TASK4}_{ti}}_{\\text{Fixed}} \\\\\n&\\quad + \\underbrace{\\color{#e41a1c}{u_{0i}} + \\color{#e41a1c}{u_{1i}}\\text{TASK2}_{ti} + \\color{#e41a1c}{u_{2i}}\\text{TASK3}_{ti} + \\color{#e41a1c}{u_{3i}}\\text{TASK4}_{ti}}_{\\text{Random}} + \\color{#4daf4a}{e_{ti}}\n\\end{align}$$\n:::\n\n## Formula\n\n**Generic**\n\n:::{.tc}\n`y ~ 1 + w * z + (1 + w | cluster)`\n\nwhere the [1 + w * z]{.blue} part is fixed<br>\nand the [(1 + w | cluster)]{.red} part is random\n:::\n\n:::{.fragment}\n**Example**\n\n:::{.tc}\n`performance ~ 1 + task * icontrol`<br>\n`+ (1 + task | subject)`\n:::\n:::\n\n## Fitting the Model\n\n:::{.fsmaller}\n\n::: {.cell}\n\n```{.r .cell-code}\nfit1 <- glmmTMB(\n  formula = performance ~ 1 + task * icontrol + (1 + task | subject),\n  data = intell\n)\nmodel_parameters(fit1, effects = \"fixed\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Fixed Effects\n\nParameter                          | Coefficient |   SE |        95% CI |     z |      p\n----------------------------------------------------------------------------------------\n(Intercept)                        |        7.71 | 0.53 | [ 6.68, 8.75] | 14.62 | < .001\ntask [Processing Speed]            |        2.92 | 0.41 | [ 2.12, 3.72] |  7.17 | < .001\ntask [Verbal Reasoning]            |        2.61 | 0.31 | [ 2.00, 3.22] |  8.34 | < .001\ntask [Working Memory]              |        7.81 | 0.38 | [ 7.07, 8.54] | 20.81 | < .001\nicontrol                           |        4.89 | 0.54 | [ 3.83, 5.95] |  9.05 | < .001\ntask [Processing Speed] × icontrol |        0.11 | 0.42 | [-0.70, 0.93] |  0.27 | 0.784 \ntask [Verbal Reasoning] × icontrol |        0.10 | 0.32 | [-0.53, 0.73] |  0.32 | 0.749 \ntask [Working Memory] × icontrol   |        2.07 | 0.38 | [ 1.32, 2.83] |  5.39 | < .001\n```\n\n\n:::\n:::\n\n:::\n\n## Simple Slopes Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_slopes(fit1, trend = \"icontrol\", by = \"task\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nEstimated Marginal Effects\n\ntask                 | Slope |   SE |       95% CI |     z |      p\n-------------------------------------------------------------------\nPerceptual Reasoning |  4.89 | 0.54 | [3.83, 5.95] |  9.05 | < .001\nProcessing Speed     |  5.01 | 0.60 | [3.83, 6.19] |  8.33 | < .001\nVerbal Reasoning     |  5.00 | 0.46 | [4.10, 5.89] | 10.91 | < .001\nWorking Memory       |  6.97 | 0.54 | [5.91, 8.02] | 12.96 | < .001\n\nMarginal effects estimated for icontrol\nType of slope was dY/dX\n```\n\n\n:::\n:::\n\n\n## Visualize Results\n\n\n::: {.cell}\n\n```{.r .cell-code}\nestimate_relation(fit1, by = c(\"icontrol\", \"task\")) |> plot()\n```\n\n::: {.cell-output-display}\n![](a_Slides_files/figure-revealjs/unnamed-chunk-8-1.png){width=960}\n:::\n:::\n\n\n## Interpreting Results\n\n:::{.fsmaller}\n1. Inhibitory control was positively associated with performance in *all four* tasks (see simple slopes analysis), which supports the first theory.\n\n:::{.fragment}\n2. However, the effect was strongest by far in the working memory task, as evidenced in the marginal effects plot. This may explain where the second theory came from.\n\n:::\n:::{.fragment}\n3. These (fake) results suggest a hybrid theory where inhibitory control helps everything somewhat, but helps working memory the most.\n\n:::\n:::\n\n# Addressing Autocorrelation\n\n## The Independence Assumption\n\n- MLM assumes that the Level 1 residuals ($e_{ti}$) are independent **after** accounting for the cluster variances ($u_{0i}$).\n- But what if the observations happen in a sequence over time?\n- Even among observations in the same cluster, trials that are closer together in time might be more similar to one another.\n- This creates **autocorrelation**, violating our assumption.\n\n## Incorporating Time\n\n:::{.fsmaller}\nTo test for and model this, we need a variable that represents the sequence of observations. Luckily, our dataset has a `trial` column that tracks the randomized order in which the tasks were completed by each subject.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintell |> print(n = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,800 × 5\n  subject icontrol trial task                 performance\n    <dbl>    <dbl> <dbl> <chr>                      <dbl>\n1       1  -0.0849     1 Perceptual Reasoning        18.0\n2       1  -0.0849     2 Processing Speed            14.4\n3       1  -0.0849     3 Working Memory              22.4\n4       1  -0.0849     4 Working Memory              17.2\n5       1  -0.0849     5 Working Memory              21.7\n6       1  -0.0849     6 Perceptual Reasoning        14.8\n# ℹ 1,794 more rows\n```\n\n\n:::\n:::\n\n\n## Checking Autocorrelation\n\nWe can perform a formal test on the residuals of our model to see if this sequence matters.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_autocorrelation(fit1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nWarning: Autocorrelated residuals detected (p < .001).\n```\n\n\n:::\n:::\n\n\n:::{.fragment .pv4}\nBecause this flags a violation, we should refit the model and explicitly account for the correlation between adjacent trials.\n:::\n\n## Partitioning the Error\n\n:::{.fsmaller}\nTo fix the autocorrelation, we split our unmeasured error into two piles:\n\n$$y_{ti} = \\text{Fixed} + \\text{Random} + \\color{#4daf4a}{(v_{ti} + e_{ti})}$$\n\n:::{.fragment}\n- **White Noise:** The independent, unpredictable noise for a specific trial.\n$$\\color{#4daf4a}{e_{ti}} \\sim \\text{Normal}(0, \\color{#4daf4a}{\\sigma_e})$$\n:::\n\n:::{.fragment}\n- **Autocorrelated Error:** The portion of the error that correlates with adjacent trials. Adding this requires two new parameters: the *amount* of this error $(\\sigma_v)$ and the *strength* of the correlation $(\\rho)$.\n$$\\color{#4daf4a}{\\mathbf{v}_i} \\sim \\text{AR1}(0, \\color{#4daf4a}{\\sigma_v}, \\color{#4daf4a}{\\rho})$$\n:::\n:::\n\n## Prepping the Time Factor\n\n\n::: {.cell}\n\n```{.r .cell-code}\nintell <- \n  intell |> \n  # Sort by trial within subject\n  arrange(subject, trial) |> \n  # Create a factor for ar1()\n  mutate(time = factor(trial)) |> \n  print(n = 6)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1,800 × 6\n  subject icontrol trial task                 performance time \n    <dbl>    <dbl> <dbl> <chr>                      <dbl> <fct>\n1       1  -0.0849     1 Perceptual Reasoning        18.0 1    \n2       1  -0.0849     2 Processing Speed            14.4 2    \n3       1  -0.0849     3 Working Memory              22.4 3    \n4       1  -0.0849     4 Working Memory              17.2 4    \n5       1  -0.0849     5 Working Memory              21.7 5    \n6       1  -0.0849     6 Perceptual Reasoning        14.8 6    \n# ℹ 1,794 more rows\n```\n\n\n:::\n:::\n\n\n## Fitting the AR(1) Model\n\n:::{.fsmaller}\nIn `glmmTMB`, we handle this by simply adding an `ar1()` term to our random effects. The software will automatically estimate $\\sigma_v$ and $\\rho$ for us.\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_ar1 <- glmmTMB(\n  formula = performance ~ \n    1 + task * icontrol +    # fixed effects\n    (1 + task | subject) +   # random effects\n    ar1(0 + time | subject), # ar1 by time (no intercept)\n  data = intell\n)\n```\n:::\n\n\n## Comparing Fixed Effects\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncompare_parameters(fit1, fit_ar1, effects = \"fixed\", select = \"{estimate} ({se})\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nParameter                          |        fit1 |     fit_ar1\n--------------------------------------------------------------\n(Intercept)                        | 7.71 (0.53) | 7.68 (0.52)\ntask [Processing Speed]            | 2.92 (0.41) | 2.91 (0.40)\ntask [Verbal Reasoning]            | 2.61 (0.31) | 2.66 (0.30)\ntask [Working Memory]              | 7.81 (0.38) | 7.87 (0.36)\nicontrol                           | 4.89 (0.54) | 4.86 (0.54)\ntask [Processing Speed] × icontrol | 0.11 (0.42) | 0.22 (0.41)\ntask [Verbal Reasoning] × icontrol | 0.10 (0.32) | 0.09 (0.31)\ntask [Working Memory] × icontrol   | 2.07 (0.38) | 2.16 (0.37)\n--------------------------------------------------------------\nObservations                       |        1800 |        1800\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller}\nOur estimates have shifted. Accounting for autocorrelation re-weights the data, treating correlated adjacent trials as partially redundant.\n:::\n\n## Did the model improve?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntest_lrt(fit1, fit_ar1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Likelihood-Ratio-Test (LRT) for Model Comparison (ML-estimator)\n\nName    |   Model | df | df_diff |   Chi2 |      p\n--------------------------------------------------\nfit1    | glmmTMB | 19 |         |        |       \nfit_ar1 | glmmTMB | 21 |       2 | 205.58 | < .001\n```\n\n\n:::\n:::\n\n\n:::{.fsmaller .pv4}\n**Yes!** Adding the two parameters for the Autocorrelated Error (the amount and the strength) resulted in a significant improvement to model fit\n:::\n\n## AR1 Parameter Estimates\n\n\n::: {.cell}\n\n```{.r .cell-code}\nVarCorr(fit_ar1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nConditional model:\n Groups    Name                 Std.Dev. Corr                      \n subject   (Intercept)          6.0856                             \n           taskProcessing Speed 4.4658   -0.205                    \n           taskVerbal Reasoning 3.0375   -0.569       0.625        \n           taskWorking Memory   3.9521   -0.337       0.627  0.703 \n subject.1 time1                2.8056   0.606 (ar1)               \n Residual                       1.3276                             \n```\n\n\n:::\n:::\n\n\n:::{.fragment .fsmaller .mt4}\nLook to the `subject.1 time1` row:\n\n- $\\color{#4daf4a}{\\sigma_v}=2.8056$: The amount of autocorrelated error.\n- $\\color{#4daf4a}{\\rho}=0.606$: The strength of the autocorrelation.\n:::\n\n## A Warning About AR(1)\n\n:::{.fsmaller}\nDiscrete AR(1) models make a key assumption: [Time steps are integers.]{.b .red}\n\n:::{.fragment}\n- `ar1()` can handle missing observations (e.g., Trial 1, 2, and 4) *if* we carefully format the factor levels to explicitly include the missing Trial 3.\n- But what happens in the real world when time isn't a simple integer sequence?\n    + A subject completes Survey 1 at 9:00 AM.\n    + They complete Survey 2 at 10:30 AM (1.5 hours later).\n    + They complete Survey 3 at 6:00 PM (7.5 hours later).\n    \n:::\n:::\n\n## The Continuous Time Problem\n\n- Because `ar1()` requires a discrete factor, we can't easily pass it continuous or fractional time gaps (1.5 vs. 7.5 hours).\n- If we just force those surveys into consecutive levels (1, 2, and 3), the AR(1) model blindly treats the 1.5-hour jump exactly the same as the 7.5-hour jump.\n- **Next Lecture:** We will dive into Longitudinal Data and learn how to use continuous-time autocorrelation structures (like Spatial Exponential) to handle real-world fractional time!\n",
    "supporting": [
      "a_Slides_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\n<script>\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\n  // slide changes (different for each slide format).\n  (function () {\n    // dispatch for htmlwidgets\n    function fireSlideEnter() {\n      const event = window.document.createEvent(\"Event\");\n      event.initEvent(\"slideenter\", true, true);\n      window.document.dispatchEvent(event);\n    }\n\n    function fireSlideChanged(previousSlide, currentSlide) {\n      fireSlideEnter();\n\n      // dispatch for shiny\n      if (window.jQuery) {\n        if (previousSlide) {\n          window.jQuery(previousSlide).trigger(\"hidden\");\n        }\n        if (currentSlide) {\n          window.jQuery(currentSlide).trigger(\"shown\");\n        }\n      }\n    }\n\n    // hookup for slidy\n    if (window.w3c_slidy) {\n      window.w3c_slidy.add_observer(function (slide_num) {\n        // slide_num starts at position 1\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\n      });\n    }\n\n  })();\n</script>\n\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}